export const pairKey = (aId, bId) => [aId, bId].sort().join(':');

export const RECIPES = {

  // ════════════════════════════════════════════════════════
  // STARTING ELEMENTS — original core
  // ════════════════════════════════════════════════════════
  [pairKey('fire', 'water')]: 'steam',
  [pairKey('water', 'earth')]: 'mud',
  [pairKey('air', 'water')]: 'cloud',
  [pairKey('air', 'earth')]: 'atmosphere',
  [pairKey('air', 'fire')]: 'smoke',
  [pairKey('earth', 'fire')]: 'volcano',
  [pairKey('water', 'water')]: 'ocean',
  [pairKey('air', 'air')]: 'oxygen',
  [pairKey('fire', 'fire')]: 'inferno',
  [pairKey('earth', 'earth')]: 'mountain',

  // ════════════════════════════════════════════════════════
  // TIER 2 — secondary elemental chains
  // ════════════════════════════════════════════════════════
  [pairKey('atmosphere', 'fire')]: 'plasma',
  [pairKey('smoke', 'earth')]: 'smog',
  [pairKey('mud', 'atmosphere')]: 'smog',
  [pairKey('mud', 'air')]: 'dust',
  [pairKey('cloud', 'earth')]: 'atmosphere',
  [pairKey('ocean', 'air')]: 'atmosphere',
  [pairKey('smoke', 'atmosphere')]: 'smog',
  [pairKey('inferno', 'earth')]: 'volcano',
  [pairKey('atmosphere', 'sea')]: 'ocean',
  [pairKey('atmosphere', 'air')]: 'sky',
  [pairKey('steam', 'fire')]: 'dragon',
  [pairKey('oxygen', 'ocean')]: 'sea',
  [pairKey('ocean', 'water')]: 'sea',
  [pairKey('steam', 'air')]: 'vapor',
  [pairKey('mud', 'earth')]: 'clay',
  [pairKey('mud', 'fire')]: 'lava',
  [pairKey('ocean', 'fire')]: 'lava',
  [pairKey('fire', 'volcano')]: 'lava',
  [pairKey('atmosphere', 'water')]: 'humidity',
  [pairKey('humidity', 'plasma')]: 'steam',
  [pairKey('sky', 'fire')]: 'sun',
  [pairKey('fire', 'plasma')]: 'sun',
  [pairKey('air', 'inferno')]: 'wildfire',
  [pairKey('air', 'volcano')]: 'ashCloud',
  [pairKey('lava', 'air')]: 'magma',
  [pairKey('lava', 'plasma')]: 'magma',
  [pairKey('steam', 'vapor')]: 'mist',
  [pairKey('smoke', 'lava')]: 'volcano',
  [pairKey('ocean', 'plasma')]: 'bioluminescense',
  [pairKey('oxygen', 'plasma')]: 'fire',
  [pairKey('earth', 'smog')]: 'dystopia',
  [pairKey('fire', 'mountain')]: 'volcano',
  [pairKey('clay', 'humidity')]: 'mud',
  [pairKey('sea', 'inferno')]: 'lavaOcean',
  [pairKey('humidity', 'mountain')]: 'cloud',
  [pairKey('cloud', 'clay')]: 'cumulus',
  [pairKey('dust', 'air')]: 'pollution',
  [pairKey('atmosphere', 'volcano')]: 'eruption',
  [pairKey('oxygen', 'steam')]: 'waterVapor',
  [pairKey('atmosphere', 'clay')]: 'terraCotta',
  [pairKey('fire', 'inferno')]: 'blaze',
  [pairKey('steam', 'earth')]: 'geothermal',

  // ════════════════════════════════════════════════════════
  // WEATHER
  // ════════════════════════════════════════════════════════
  [pairKey('cloud', 'water')]: 'rain',
  [pairKey('cloud', 'ocean')]: 'rain',
  [pairKey('cloud', 'mist')]: 'rain',
  [pairKey('mountain', 'water')]: 'ice',
  [pairKey('water', 'cold')]: 'ice',
  [pairKey('cloud', 'ice')]: 'snow',
  [pairKey('atmosphere', 'ice')]: 'snow',
  [pairKey('cloud', 'cloud')]: 'storm',
  [pairKey('air', 'rain')]: 'storm',
  [pairKey('lightning', 'rain')]: 'storm',
  [pairKey('lightning', 'thunder')]: 'storm',
  [pairKey('cloud', 'fire')]: 'lightning',
  [pairKey('cloud', 'plasma')]: 'lightning',
  [pairKey('air', 'lightning')]: 'thunder',
  [pairKey('air', 'storm')]: 'tornado',
  [pairKey('storm', 'storm')]: 'hurricane',
  [pairKey('ocean', 'storm')]: 'typhoon',
  [pairKey('hurricane', 'water')]: 'typhoon',
  [pairKey('air', 'ice')]: 'frost',
  [pairKey('earth', 'ice')]: 'tundra',
  [pairKey('snow', 'storm')]: 'blizzard',
  [pairKey('ice', 'storm')]: 'hail',
  [pairKey('rain', 'sun')]: 'rainbow',
  [pairKey('mist', 'sun')]: 'rainbow',
  [pairKey('earth', 'mist')]: 'fog',
  [pairKey('earth', 'vapor')]: 'fog',
  [pairKey('atmosphere', 'plasma')]: 'aurora',
  [pairKey('ocean', 'rain')]: 'monsoon',
  [pairKey('cloud', 'monsoon')]: 'monsoon',
  [pairKey('fire', 'ice')]: 'water',
  [pairKey('ice', 'sun')]: 'water',
  [pairKey('fire', 'snow')]: 'water',
  [pairKey('snow', 'sun')]: 'water',
  [pairKey('sand', 'storm')]: 'sandstorm',
  [pairKey('desert', 'storm')]: 'sandstorm',
  [pairKey('desert', 'air')]: 'sandstorm',
  [pairKey('sun', 'desert')]: 'drought',
  [pairKey('sun', 'sand')]: 'drought',
  [pairKey('sun', 'earth')]: 'heatwave',
  [pairKey('fire', 'drought')]: 'heatwave',
  [pairKey('rain', 'river')]: 'flood',
  [pairKey('glacier', 'sun')]: 'flood',
  [pairKey('storm', 'water')]: 'flood',
  [pairKey('grass', 'water')]: 'dew',
  [pairKey('flower', 'rain')]: 'dew',
  [pairKey('fog', 'sun')]: 'dew',
  [pairKey('humidity', 'cloud')]: 'cumulus',

  // ════════════════════════════════════════════════════════
  // GEOLOGY / MATERIALS
  // ════════════════════════════════════════════════════════
  [pairKey('earth', 'lava')]: 'rock',
  [pairKey('magma', 'earth')]: 'rock',
  [pairKey('lava', 'water')]: 'obsidian',
  [pairKey('magma', 'ocean')]: 'obsidian',
  [pairKey('rock', 'mountain')]: 'stone',
  [pairKey('stone', 'ocean')]: 'sand',
  [pairKey('rock', 'wave')]: 'sand',
  [pairKey('rock', 'river')]: 'sand',
  [pairKey('fire', 'sand')]: 'glass',
  [pairKey('lava', 'sand')]: 'glass',
  [pairKey('earth', 'blaze')]: 'coal',
  [pairKey('mud', 'inferno')]: 'coal',
  [pairKey('plant', 'earth')]: 'coal',
  [pairKey('wood', 'earth')]: 'coal',
  [pairKey('rock', 'fire')]: 'mineral',
  [pairKey('fire', 'mineral')]: 'metal',
  [pairKey('inferno', 'rock')]: 'metal',
  [pairKey('earth', 'metal')]: 'iron',
  [pairKey('metal', 'rock')]: 'iron',
  [pairKey('metal', 'water')]: 'copper',
  [pairKey('metal', 'sun')]: 'gold',
  [pairKey('iron', 'sun')]: 'gold',
  [pairKey('metal', 'moon')]: 'silver',
  [pairKey('iron', 'moon')]: 'silver',
  [pairKey('coal', 'iron')]: 'steel',
  [pairKey('iron', 'iron')]: 'steel',
  [pairKey('iron', 'rain')]: 'rust',
  [pairKey('steel', 'rain')]: 'rust',
  [pairKey('iron', 'water')]: 'rust',
  [pairKey('mineral', 'water')]: 'crystal',
  [pairKey('glass', 'earth')]: 'crystal',
  [pairKey('glass', 'glass')]: 'crystal',
  [pairKey('crystal', 'fire')]: 'gem',
  [pairKey('cave', 'crystal')]: 'gem',
  [pairKey('gem', 'inferno')]: 'diamond',
  [pairKey('crystal', 'volcano')]: 'diamond',
  [pairKey('copper', 'iron')]: 'bronze',
  [pairKey('fire', 'stone')]: 'marble',
  [pairKey('rock', 'rock')]: 'cave',
  [pairKey('earth', 'rock')]: 'soil',
  [pairKey('clay', 'earth')]: 'soil',
  [pairKey('cave', 'water')]: 'stalactite',
  [pairKey('mineral', 'cave')]: 'stalactite',
  [pairKey('rock', 'ocean')]: 'salt',
  [pairKey('ocean', 'sun')]: 'salt',
  [pairKey('fire', 'sea')]: 'salt',
  [pairKey('smoke', 'fire')]: 'ash',
  [pairKey('wood', 'fire')]: 'ash',
  [pairKey('wildfire', 'forest')]: 'ashCloud',
  [pairKey('volcano', 'forest')]: 'ashCloud',
  [pairKey('earth', 'swamp')]: 'peat',
  [pairKey('plant', 'swamp')]: 'peat',
  [pairKey('tree', 'swamp')]: 'peat',
  [pairKey('resin', 'time')]: 'amber',
  [pairKey('insect', 'resin')]: 'amber',
  [pairKey('sand', 'water')]: 'quicksand',
  [pairKey('oil', 'earth')]: 'tar',
  [pairKey('rock', 'heat')]: 'chalk',
  [pairKey('mineral', 'water')]: 'quartz',
  [pairKey('crystal', 'earth')]: 'quartz',
  [pairKey('ice', 'earth')]: 'permafrost',
  [pairKey('glacier', 'earth')]: 'permafrost',
  [pairKey('rock', 'flint')]: 'fire',
  [pairKey('flint', 'flint')]: 'fire',

  // ════════════════════════════════════════════════════════
  // WATER FEATURES
  // ════════════════════════════════════════════════════════
  [pairKey('mountain', 'rain')]: 'river',
  [pairKey('glacier', 'sun')]: 'river',
  [pairKey('ice', 'mountain')]: 'glacier',
  [pairKey('snow', 'mountain')]: 'glacier',
  [pairKey('storm', 'water')]: 'wave',
  [pairKey('wind', 'ocean')]: 'wave',
  [pairKey('mud', 'tree')]: 'swamp',
  [pairKey('water', 'forest')]: 'swamp',
  [pairKey('mountain', 'river')]: 'waterfall',
  [pairKey('cliff', 'river')]: 'waterfall',
  [pairKey('earth', 'rain')]: 'pond',
  [pairKey('grass', 'rain')]: 'pond',
  [pairKey('moon', 'ocean')]: 'tide',
  [pairKey('moon', 'sea')]: 'tide',
  [pairKey('ocean', 'river')]: 'delta',
  [pairKey('river', 'grass')]: 'marsh',
  [pairKey('grass', 'water')]: 'marsh',
  [pairKey('river', 'river')]: 'lake',
  [pairKey('pond', 'pond')]: 'lake',
  [pairKey('geothermal', 'water')]: 'geyser',
  [pairKey('volcano', 'water')]: 'geyser',
  [pairKey('hotSpring', 'water')]: 'geyser',
  [pairKey('storm', 'ocean')]: 'whirlpool',
  [pairKey('tornado', 'ocean')]: 'whirlpool',
  [pairKey('geothermal', 'earth')]: 'hotSpring',
  [pairKey('steam', 'rock')]: 'hotSpring',

  // ════════════════════════════════════════════════════════
  // LANDFORMS
  // ════════════════════════════════════════════════════════
  [pairKey('ocean', 'volcano')]: 'island',
  [pairKey('mountain', 'ocean')]: 'island',
  [pairKey('sand', 'sun')]: 'desert',
  [pairKey('earth', 'drought')]: 'desert',
  [pairKey('river', 'rock')]: 'canyon',
  [pairKey('water', 'stone')]: 'canyon',
  [pairKey('ocean', 'sand')]: 'beach',
  [pairKey('sea', 'sand')]: 'beach',
  [pairKey('desert', 'water')]: 'oasis',
  [pairKey('desert', 'plant')]: 'oasis',
  [pairKey('earth', 'grass')]: 'prairie',
  [pairKey('grass', 'prairie')]: 'prairie',
  [pairKey('mountain', 'stone')]: 'cliff',
  [pairKey('mountain', 'wave')]: 'cliff',
  [pairKey('mountain', 'mountain')]: 'plateau',
  [pairKey('earth', 'mountain')]: 'valley',
  [pairKey('river', 'mountain')]: 'valley',
  [pairKey('ice', 'desert')]: 'tundra',
  [pairKey('earth', 'tundra')]: 'permafrost',

  // ════════════════════════════════════════════════════════
  // LIFE ORIGIN
  // ════════════════════════════════════════════════════════
  [pairKey('lightning', 'ocean')]: 'life',
  [pairKey('lightning', 'sea')]: 'life',
  [pairKey('lightning', 'water')]: 'life',
  [pairKey('mud', 'lightning')]: 'life',
  [pairKey('ocean', 'sun')]: 'life',
  [pairKey('water', 'sun')]: 'life',

  // ════════════════════════════════════════════════════════
  // PLANTS / NATURE
  // ════════════════════════════════════════════════════════
  [pairKey('soil', 'sun')]: 'plant',
  [pairKey('soil', 'water')]: 'plant',
  [pairKey('earth', 'life')]: 'plant',
  [pairKey('plant', 'earth')]: 'grass',
  [pairKey('plant', 'sun')]: 'grass',
  [pairKey('grass', 'sun')]: 'flower',
  [pairKey('plant', 'rain')]: 'flower',
  [pairKey('plant', 'water')]: 'flower',
  [pairKey('seed', 'soil')]: 'tree',
  [pairKey('seed', 'earth')]: 'tree',
  [pairKey('plant', 'time')]: 'tree',
  [pairKey('rain', 'tree')]: 'forest',
  [pairKey('tree', 'tree')]: 'forest',
  [pairKey('forest', 'humidity')]: 'jungle',
  [pairKey('forest', 'rain')]: 'jungle',
  [pairKey('forest', 'heat')]: 'jungle',
  [pairKey('rock', 'tree')]: 'wood',
  [pairKey('axe', 'tree')]: 'wood',
  [pairKey('fire', 'wood')]: 'charcoal',
  [pairKey('wood', 'inferno')]: 'charcoal',
  [pairKey('air', 'tree')]: 'leaf',
  [pairKey('tree', 'wind')]: 'leaf',
  [pairKey('stone', 'water')]: 'moss',
  [pairKey('cave', 'water')]: 'moss',
  [pairKey('lake', 'sun')]: 'algae',
  [pairKey('water', 'plant')]: 'algae',
  [pairKey('algae', 'ocean')]: 'seaweed',
  [pairKey('algae', 'sea')]: 'seaweed',
  [pairKey('algae', 'kelp')]: 'kelp',
  [pairKey('soil', 'humidity')]: 'mushroom',
  [pairKey('wood', 'water')]: 'mushroom',
  [pairKey('spore', 'earth')]: 'mushroom',
  [pairKey('flower', 'tree')]: 'fruit',
  [pairKey('flower', 'sun')]: 'fruit',
  [pairKey('fruit', 'earth')]: 'seed',
  [pairKey('fruit', 'wind')]: 'seed',
  [pairKey('air', 'flower')]: 'pollen',
  [pairKey('bee', 'flower')]: 'pollen',
  [pairKey('plant', 'tree')]: 'vine',
  [pairKey('plant', 'rock')]: 'vine',
  [pairKey('plant', 'desert')]: 'cactus',
  [pairKey('cactus', 'sun')]: 'cactus',
  [pairKey('grass', 'humidity')]: 'bamboo',
  [pairKey('grass', 'jungle')]: 'bamboo',
  [pairKey('stone', 'sea')]: 'coral',
  [pairKey('life', 'ocean')]: 'coral',
  [pairKey('coral', 'ocean')]: 'reef',
  [pairKey('coral', 'rock')]: 'reef',
  [pairKey('mushroom', 'air')]: 'spore',
  [pairKey('mushroom', 'wind')]: 'spore',
  [pairKey('forest', 'fire')]: 'wildfire',
  [pairKey('plant', 'sun')]: 'grain',
  [pairKey('grass', 'farm')]: 'wheat',
  [pairKey('grain', 'sun')]: 'wheat',
  [pairKey('grain', 'water')]: 'rice',
  [pairKey('wheat', 'water')]: 'rice',
  [pairKey('plant', 'medicine')]: 'herb',
  [pairKey('mushroom', 'forest')]: 'herb',
  [pairKey('seaweed', 'ocean')]: 'kelp',
  [pairKey('plant', 'cold')]: 'fern',
  [pairKey('forest', 'water')]: 'fern',
  [pairKey('flower', 'love')]: 'rose',
  [pairKey('flower', 'magic')]: 'rose',
  [pairKey('vine', 'tree')]: 'ivy',
  [pairKey('vine', 'castle')]: 'ivy',
  [pairKey('tree', 'mountain')]: 'oak',
  [pairKey('tree', 'forest')]: 'pine',
  [pairKey('tree', 'snow')]: 'pine',
  [pairKey('plant', 'fiber')]: 'cotton',
  [pairKey('grass', 'warmth')]: 'cotton',
  [pairKey('plant', 'smoke')]: 'tobacco',
  [pairKey('leaf', 'fire')]: 'tobacco',
  [pairKey('flower', 'water')]: 'lily',
  [pairKey('pond', 'flower')]: 'lily',
  [pairKey('flower', 'sun')]: 'sunflower',
  [pairKey('flower', 'light')]: 'sunflower',
  [pairKey('forest', 'ocean')]: 'mangrove',
  [pairKey('tree', 'swamp')]: 'mangrove',

  // ════════════════════════════════════════════════════════
  // ANIMALS — aquatic
  // ════════════════════════════════════════════════════════
  [pairKey('life', 'water')]: 'fish',
  [pairKey('life', 'sea')]: 'fish',
  [pairKey('fish', 'river')]: 'salmon',
  [pairKey('fish', 'ocean')]: 'whale',
  [pairKey('fish', 'fish')]: 'whale',
  [pairKey('fish', 'storm')]: 'shark',
  [pairKey('shark', 'ocean')]: 'shark',
  [pairKey('fish', 'wave')]: 'dolphin',
  [pairKey('dolphin', 'ocean')]: 'dolphin',
  [pairKey('earth', 'ocean')]: 'crab',
  [pairKey('beach', 'life')]: 'crab',
  [pairKey('rock', 'sea')]: 'turtle',
  [pairKey('ocean', 'rock')]: 'turtle',
  [pairKey('sea', 'plant')]: 'octopus',
  [pairKey('ocean', 'life')]: 'octopus',
  [pairKey('water', 'fire')]: 'jellyfish',
  [pairKey('ocean', 'electricity')]: 'jellyfish',
  [pairKey('crab', 'ocean')]: 'lobster',
  [pairKey('clam', 'ocean')]: 'pearl',
  [pairKey('sea', 'sand')]: 'clam',
  [pairKey('algae', 'fish')]: 'squid',
  [pairKey('fish', 'darkness')]: 'squid',
  [pairKey('coral', 'fish')]: 'clam',
  [pairKey('ocean', 'coral')]: 'clam',

  // ════════════════════════════════════════════════════════
  // ANIMALS — insects
  // ════════════════════════════════════════════════════════
  [pairKey('life', 'plant')]: 'insect',
  [pairKey('life', 'soil')]: 'worm',
  [pairKey('flower', 'insect')]: 'bee',
  [pairKey('insect', 'pollen')]: 'bee',
  [pairKey('insect', 'sun')]: 'butterfly',
  [pairKey('butterfly', 'flower')]: 'butterfly',
  [pairKey('insect', 'moon')]: 'moth',
  [pairKey('moth', 'candle')]: 'moth',
  [pairKey('insect', 'music')]: 'cricket',
  [pairKey('insect', 'night')]: 'cricket',
  [pairKey('insect', 'fire')]: 'firefly',
  [pairKey('insect', 'light')]: 'firefly',
  [pairKey('insect', 'water')]: 'mosquito',
  [pairKey('swamp', 'insect')]: 'mosquito',
  [pairKey('life', 'sand')]: 'ant',
  [pairKey('insect', 'earth')]: 'ant',
  [pairKey('ant', 'ant')]: 'ant',
  [pairKey('insect', 'web')]: 'spider',
  [pairKey('insect', 'cave')]: 'spider',
  [pairKey('desert', 'insect')]: 'scorpion',
  [pairKey('scorpion', 'desert')]: 'scorpion',
  [pairKey('insect', 'drought')]: 'locust',
  [pairKey('ant', 'drought')]: 'locust',

  // ════════════════════════════════════════════════════════
  // ANIMALS — birds
  // ════════════════════════════════════════════════════════
  [pairKey('life', 'sky')]: 'bird',
  [pairKey('life', 'tree')]: 'bird',
  [pairKey('bird', 'mountain')]: 'eagle',
  [pairKey('bird', 'storm')]: 'hawk',
  [pairKey('bird', 'moon')]: 'owl',
  [pairKey('bird', 'darkness')]: 'owl',
  [pairKey('bird', 'night')]: 'raven',
  [pairKey('raven', 'moon')]: 'raven',
  [pairKey('owl', 'wisdom')]: 'owl',

  // ════════════════════════════════════════════════════════
  // ANIMALS — reptiles
  // ════════════════════════════════════════════════════════
  [pairKey('life', 'rock')]: 'snake',
  [pairKey('desert', 'life')]: 'snake',
  [pairKey('snake', 'sun')]: 'lizard',
  [pairKey('lizard', 'desert')]: 'lizard',
  [pairKey('earth', 'lizard')]: 'dinosaur',
  [pairKey('lizard', 'mountain')]: 'dinosaur',
  [pairKey('fire', 'lizard')]: 'dragon',
  [pairKey('snake', 'water')]: 'crocodile',
  [pairKey('lizard', 'river')]: 'crocodile',

  // ════════════════════════════════════════════════════════
  // ANIMALS — amphibians / small
  // ════════════════════════════════════════════════════════
  [pairKey('life', 'pond')]: 'frog',
  [pairKey('life', 'swamp')]: 'frog',
  [pairKey('frog', 'swamp')]: 'frog',

  // ════════════════════════════════════════════════════════
  // ANIMALS — mammals
  // ════════════════════════════════════════════════════════
  [pairKey('life', 'mountain')]: 'wolf',
  [pairKey('forest', 'mountain')]: 'bear',
  [pairKey('forest', 'life')]: 'bear',
  [pairKey('forest', 'grass')]: 'deer',
  [pairKey('grass', 'life')]: 'horse',
  [pairKey('prairie', 'life')]: 'horse',
  [pairKey('wolf', 'moon')]: 'werewolf',
  [pairKey('glacier', 'horse')]: 'mammoth',
  [pairKey('horse', 'ice')]: 'mammoth',
  [pairKey('forest', 'cat')]: 'panther',
  [pairKey('lion', 'darkness')]: 'panther',
  [pairKey('life', 'jungle')]: 'gorilla',
  [pairKey('forest', 'gorilla')]: 'gorilla',
  [pairKey('life', 'farm')]: 'pig',
  [pairKey('human', 'wolf')]: 'dog',
  [pairKey('dog', 'human')]: 'dog',
  [pairKey('life', 'grass')]: 'rabbit',
  [pairKey('rabbit', 'grass')]: 'rabbit',
  [pairKey('life', 'ocean')]: 'seal',
  [pairKey('seal', 'ice')]: 'penguin',
  [pairKey('bird', 'ice')]: 'penguin',
  [pairKey('cat', 'desert')]: 'lion',
  [pairKey('lion', 'forest')]: 'tiger',
  [pairKey('cat', 'grass')]: 'lion',
  [pairKey('life', 'prairie')]: 'elephant',
  [pairKey('deer', 'mountain')]: 'goat',
  [pairKey('wolf', 'forest')]: 'fox',
  [pairKey('rabbit', 'forest')]: 'fox',
  [pairKey('life', 'night')]: 'bat',
  [pairKey('bird', 'cave')]: 'bat',
  [pairKey('wolf', 'human')]: 'dog',
  [pairKey('life', 'village')]: 'cat',
  [pairKey('human', 'cat')]: 'cat',
  [pairKey('grass', 'human')]: 'cow',
  [pairKey('life', 'cow')]: 'milk',
  [pairKey('grass', 'sheep')]: 'sheep',

  // ════════════════════════════════════════════════════════
  // MYTHICAL ANIMALS
  // ════════════════════════════════════════════════════════
  [pairKey('bird', 'fire')]: 'phoenix',
  [pairKey('eagle', 'fire')]: 'phoenix',
  [pairKey('phoenix', 'ash')]: 'phoenix',
  [pairKey('squid', 'ocean')]: 'kraken',
  [pairKey('kraken', 'ocean')]: 'leviathan',
  [pairKey('dragon', 'ocean')]: 'leviathan',
  [pairKey('crystal', 'horse')]: 'unicorn',
  [pairKey('magic', 'horse')]: 'unicorn',
  [pairKey('eagle', 'lion')]: 'griffin',
  [pairKey('eagle', 'wolf')]: 'griffin',
  [pairKey('dragon', 'sea')]: 'seaDragon',
  [pairKey('dragon', 'ice')]: 'iceDragon',
  [pairKey('dragon', 'glacier')]: 'iceDragon',
  [pairKey('dragon', 'storm')]: 'stormDragon',
  [pairKey('dragon', 'lightning')]: 'stormDragon',
  [pairKey('snake', 'magic')]: 'hydra',
  [pairKey('snake', 'snake')]: 'hydra',
  [pairKey('lion', 'fire')]: 'chimera',
  [pairKey('lion', 'snake')]: 'chimera',
  [pairKey('lion', 'desert')]: 'sphinx',
  [pairKey('lion', 'pyramid')]: 'sphinx',
  [pairKey('cow', 'human')]: 'minotaur',
  [pairKey('horse', 'human')]: 'centaur',
  [pairKey('horse', 'warrior')]: 'centaur',
  [pairKey('fish', 'human')]: 'siren',
  [pairKey('ocean', 'music')]: 'siren',
  [pairKey('snake', 'legend')]: 'basilisk',
  [pairKey('dragon', 'snake')]: 'basilisk',
  [pairKey('lion', 'scorpion')]: 'manticore',
  [pairKey('warrior', 'storm')]: 'valkyrie',

  // ════════════════════════════════════════════════════════
  // HUMAN / CIVILIZATION
  // ════════════════════════════════════════════════════════
  [pairKey('earth', 'life')]: 'human',
  [pairKey('fire', 'life')]: 'human',
  [pairKey('clay', 'life')]: 'golem',
  [pairKey('rock', 'life')]: 'golem',
  [pairKey('human', 'human')]: 'tribe',
  [pairKey('earth', 'tribe')]: 'village',
  [pairKey('tribe', 'wood')]: 'village',
  [pairKey('tribe', 'fire')]: 'village',
  [pairKey('village', 'village')]: 'city',
  [pairKey('village', 'knowledge')]: 'city',
  [pairKey('wood', 'wood')]: 'house',
  [pairKey('house', 'stone')]: 'castle',
  [pairKey('castle', 'stone')]: 'fortress',
  [pairKey('castle', 'iron')]: 'fortress',
  [pairKey('human', 'stone')]: 'tool',
  [pairKey('human', 'wood')]: 'tool',
  [pairKey('metal', 'tool')]: 'weapon',
  [pairKey('iron', 'tool')]: 'sword',
  [pairKey('forge', 'iron')]: 'sword',
  [pairKey('forge', 'steel')]: 'armor',
  [pairKey('metal', 'armor')]: 'armor',
  [pairKey('ocean', 'wood')]: 'ship',
  [pairKey('sea', 'wood')]: 'ship',
  [pairKey('fire', 'metal')]: 'forge',
  [pairKey('human', 'mountain')]: 'mine',
  [pairKey('human', 'rock')]: 'mine',
  [pairKey('rock', 'wood')]: 'wheel',
  [pairKey('river', 'stone')]: 'bridge',
  [pairKey('metal', 'bridge')]: 'bridge',
  [pairKey('clay', 'human')]: 'writing',
  [pairKey('human', 'leaf')]: 'writing',
  [pairKey('human', 'paper')]: 'writing',
  [pairKey('human', 'writing')]: 'knowledge',
  [pairKey('knowledge', 'knowledge')]: 'science',
  [pairKey('army', 'city')]: 'empire',
  [pairKey('city', 'city')]: 'empire',
  [pairKey('human', 'weapon')]: 'army',
  [pairKey('tribe', 'weapon')]: 'army',
  [pairKey('army', 'army')]: 'war',
  [pairKey('empire', 'empire')]: 'war',
  [pairKey('human', 'village')]: 'market',
  [pairKey('human', 'mushroom')]: 'medicine',
  [pairKey('human', 'plant')]: 'medicine',
  [pairKey('human', 'herb')]: 'medicine',
  [pairKey('human', 'sun')]: 'religion',
  [pairKey('human', 'volcano')]: 'religion',
  [pairKey('human', 'lightning')]: 'religion',
  [pairKey('grass', 'human')]: 'farm',
  [pairKey('human', 'plow')]: 'farm',
  [pairKey('city', 'ocean')]: 'harbor',
  [pairKey('ship', 'city')]: 'harbor',
  [pairKey('fire', 'glass')]: 'lighthouse',
  [pairKey('harbor', 'fire')]: 'lighthouse',
  [pairKey('gold', 'human')]: 'crown',
  [pairKey('empire', 'human')]: 'crown',
  [pairKey('city', 'knowledge')]: 'library',
  [pairKey('book', 'house')]: 'library',
  [pairKey('knowledge', 'house')]: 'school',
  [pairKey('medicine', 'house')]: 'hospital',
  [pairKey('gold', 'house')]: 'bank',
  [pairKey('city', 'gold')]: 'bank',
  [pairKey('art', 'house')]: 'museum',
  [pairKey('glass', 'sky')]: 'telescope',
  [pairKey('human', 'knowledge')]: 'science',
  [pairKey('metal', 'science')]: 'technology',
  [pairKey('city', 'electricity')]: 'technology',
  [pairKey('human', 'sand')]: 'pyramid',
  [pairKey('desert', 'religion')]: 'pyramid',
  [pairKey('water', 'wheel')]: 'mill',
  [pairKey('grain', 'mill')]: 'flour',
  [pairKey('grain', 'stone')]: 'flour',
  [pairKey('earth', 'iron')]: 'compass',
  [pairKey('empire', 'knowledge')]: 'civilization',
  [pairKey('city', 'science')]: 'civilization',
  [pairKey('human', 'religion')]: 'temple',
  [pairKey('religion', 'stone')]: 'temple',
  [pairKey('desert', 'tomb')]: 'pyramid',
  [pairKey('human', 'death')]: 'tomb',
  [pairKey('human', 'plant')]: 'garden',
  [pairKey('city', 'flower')]: 'garden',
  [pairKey('city', 'army')]: 'prison',
  [pairKey('stone', 'statue')]: 'monument',
  [pairKey('city', 'water')]: 'aqueduct',
  [pairKey('river', 'city')]: 'aqueduct',
  [pairKey('human', 'weapon')]: 'warrior',
  [pairKey('army', 'human')]: 'warrior',

  // ════════════════════════════════════════════════════════
  // TOOLS & OBJECTS
  // ════════════════════════════════════════════════════════
  [pairKey('wood', 'rope')]: 'bow',
  [pairKey('wood', 'metal')]: 'arrow',
  [pairKey('bow', 'wood')]: 'arrow',
  [pairKey('metal', 'wood')]: 'axe',
  [pairKey('stone', 'wood')]: 'axe',
  [pairKey('iron', 'wood')]: 'hammer',
  [pairKey('iron', 'earth')]: 'plow',
  [pairKey('metal', 'earth')]: 'plow',
  [pairKey('metal', 'explosion')]: 'gun',
  [pairKey('gunpowder', 'metal')]: 'gun',
  [pairKey('gun', 'metal')]: 'cannon',
  [pairKey('catapult', 'stone')]: 'catapult',
  [pairKey('horse', 'wheel')]: 'chariot',
  [pairKey('wheel', 'wood')]: 'chariot',
  [pairKey('glass', 'moon')]: 'telescope',
  [pairKey('crystal', 'time')]: 'clock',
  [pairKey('paper', 'knowledge')]: 'map',
  [pairKey('iron', 'lock')]: 'key',
  [pairKey('metal', 'key')]: 'lock',
  [pairKey('vine', 'vine')]: 'rope',
  [pairKey('rope', 'water')]: 'net',
  [pairKey('honey', 'fire')]: 'candle',
  [pairKey('glass', 'fire')]: 'lantern',
  [pairKey('candle', 'glass')]: 'lantern',
  [pairKey('wood', 'fire')]: 'torch',
  [pairKey('glass', 'water')]: 'mirror',
  [pairKey('silver', 'glass')]: 'mirror',
  [pairKey('gold', 'gem')]: 'ring',
  [pairKey('metal', 'gem')]: 'ring',
  [pairKey('stone', 'artist')]: 'statue',
  [pairKey('metal', 'music')]: 'bell',
  [pairKey('wood', 'music')]: 'drum',
  [pairKey('metal', 'music')]: 'harp',
  [pairKey('wood', 'pulp')]: 'paper',
  [pairKey('tree', 'water')]: 'paper',
  [pairKey('paper', 'knowledge')]: 'book',
  [pairKey('writing', 'paper')]: 'book',
  [pairKey('paper', 'history')]: 'scroll',
  [pairKey('writing', 'ancient')]: 'scroll',

  // ════════════════════════════════════════════════════════
  // FOOD / COOKING
  // ════════════════════════════════════════════════════════
  [pairKey('fire', 'flour')]: 'bread',
  [pairKey('flour', 'water')]: 'bread',
  [pairKey('bee', 'flower')]: 'honey',
  [pairKey('bee', 'tree')]: 'honey',
  [pairKey('fruit', 'sun')]: 'wine',
  [pairKey('grain', 'water')]: 'beer',
  [pairKey('wheat', 'water')]: 'beer',
  [pairKey('fish', 'water')]: 'soup',
  [pairKey('mushroom', 'water')]: 'soup',
  [pairKey('meat', 'water')]: 'soup',
  [pairKey('leaf', 'water')]: 'tea',
  [pairKey('herb', 'water')]: 'tea',
  [pairKey('fire', 'seed')]: 'oil',
  [pairKey('fire', 'animal')]: 'meat',
  [pairKey('deer', 'fire')]: 'meat',
  [pairKey('fish', 'fire')]: 'meat',
  [pairKey('fire', 'wine')]: 'alcohol',
  [pairKey('beer', 'grain')]: 'alcohol',
  [pairKey('cow', 'human')]: 'milk',
  [pairKey('milk', 'time')]: 'cheese',
  [pairKey('milk', 'salt')]: 'cheese',
  [pairKey('milk', 'fire')]: 'butter',
  [pairKey('plant', 'fire')]: 'sugar',
  [pairKey('sugar', 'bean')]: 'chocolate',
  [pairKey('cacao', 'fire')]: 'chocolate',
  [pairKey('bean', 'fire')]: 'coffee',
  [pairKey('fire', 'plant')]: 'spice',
  [pairKey('herb', 'fire')]: 'spice',
  [pairKey('fish', 'salt')]: 'soup',

  // ════════════════════════════════════════════════════════
  // ALCHEMY / POTIONS
  // ════════════════════════════════════════════════════════
  [pairKey('crystal', 'water')]: 'potion',
  [pairKey('gem', 'water')]: 'potion',
  [pairKey('herb', 'magic')]: 'potion',
  [pairKey('potion', 'magic')]: 'elixir',
  [pairKey('life', 'potion')]: 'elixir',
  [pairKey('rain', 'volcano')]: 'acid',
  [pairKey('smoke', 'water')]: 'acid',
  [pairKey('chemistry', 'fire')]: 'acid',
  [pairKey('coal', 'salt')]: 'gunpowder',
  [pairKey('coal', 'smoke')]: 'gunpowder',
  [pairKey('charcoal', 'salt')]: 'gunpowder',
  [pairKey('snake', 'poison')]: 'venom',
  [pairKey('scorpion', 'venom')]: 'venom',
  [pairKey('plant', 'death')]: 'poison',
  [pairKey('mushroom', 'death')]: 'poison',
  [pairKey('venom', 'water')]: 'poison',
  [pairKey('knowledge', 'potion')]: 'alchemy',
  [pairKey('fire', 'gold')]: 'alchemy',

  // ════════════════════════════════════════════════════════
  // ABSTRACT / ENERGY
  // ════════════════════════════════════════════════════════
  [pairKey('iron', 'lightning')]: 'electricity',
  [pairKey('steel', 'lightning')]: 'electricity',
  [pairKey('copper', 'lightning')]: 'electricity',
  [pairKey('fire', 'gunpowder')]: 'explosion',
  [pairKey('gunpowder', 'lightning')]: 'explosion',
  [pairKey('bomb', 'fire')]: 'explosion',
  [pairKey('fire', 'tornado')]: 'firestorm',
  [pairKey('wildfire', 'tornado')]: 'firestorm',
  [pairKey('storm', 'fire')]: 'firestorm',
  [pairKey('earth', 'volcano')]: 'earthquake',
  [pairKey('earth', 'mountain')]: 'earthquake',
  [pairKey('earthquake', 'ocean')]: 'tsunami',
  [pairKey('volcano', 'ocean')]: 'tsunami',
  [pairKey('mountain', 'snow')]: 'avalanche',
  [pairKey('earthquake', 'mountain')]: 'avalanche',
  [pairKey('sun', 'night')]: 'eclipse',
  [pairKey('radiation', 'fire')]: 'nuclear',
  [pairKey('atom', 'fire')]: 'nuclear',
  [pairKey('electricity', 'sun')]: 'solar',
  [pairKey('sun', 'technology')]: 'solar',
  [pairKey('sun', 'energy')]: 'energy',
  [pairKey('fire', 'energy')]: 'energy',
  [pairKey('atom', 'atom')]: 'molecule',
  [pairKey('molecule', 'molecule')]: 'chemistry',
  [pairKey('atom', 'fire')]: 'radiation',
  [pairKey('radiation', 'earth')]: 'mutation',
  [pairKey('sun', 'earth')]: 'light',
  [pairKey('fire', 'darkness')]: 'light',
  [pairKey('eclipse', 'sun')]: 'darkness',
  [pairKey('void', 'night')]: 'darkness',

  // ════════════════════════════════════════════════════════
  // TECHNOLOGY
  // ════════════════════════════════════════════════════════
  [pairKey('iron', 'steam')]: 'steamEngine',
  [pairKey('steam', 'steel')]: 'steamEngine',
  [pairKey('steamEngine', 'wheel')]: 'train',
  [pairKey('steamEngine', 'iron')]: 'engine',
  [pairKey('engine', 'metal')]: 'car',
  [pairKey('electricity', 'engine')]: 'car',
  [pairKey('steamEngine', 'city')]: 'factory',
  [pairKey('engine', 'factory')]: 'machine',
  [pairKey('metal', 'machine')]: 'machine',
  [pairKey('engine', 'air')]: 'airplane',
  [pairKey('airplane', 'sky')]: 'airplane',
  [pairKey('engine', 'space')]: 'rocket',
  [pairKey('rocket', 'sky')]: 'rocket',
  [pairKey('rocket', 'planet')]: 'satellite',
  [pairKey('electricity', 'machine')]: 'computer',
  [pairKey('computer', 'computer')]: 'internet',
  [pairKey('machine', 'human')]: 'robot',
  [pairKey('computer', 'metal')]: 'robot',
  [pairKey('electricity', 'radio')]: 'phone',
  [pairKey('computer', 'phone')]: 'phone',
  [pairKey('light', 'glass')]: 'camera',
  [pairKey('mirror', 'light')]: 'camera',
  [pairKey('electricity', 'air')]: 'radio',
  [pairKey('electricity', 'wave')]: 'radio',
  [pairKey('radio', 'glass')]: 'television',
  [pairKey('camera', 'radio')]: 'television',
  [pairKey('electricity', 'metal')]: 'battery',
  [pairKey('battery', 'machine')]: 'generator',
  [pairKey('electricity', 'crystal')]: 'laser',
  [pairKey('light', 'crystal')]: 'laser',
  [pairKey('gunpowder', 'metal')]: 'bomb',
  [pairKey('explosion', 'metal')]: 'bomb',
  [pairKey('robot', 'sky')]: 'drone',
  [pairKey('ship', 'engine')]: 'submarine',
  [pairKey('ship', 'ocean')]: 'submarine',
  [pairKey('glass', 'light')]: 'microscope',
  [pairKey('crystal', 'science')]: 'microscope',
  [pairKey('nuclear', 'energy')]: 'reactor',
  [pairKey('atom', 'electricity')]: 'reactor',
  [pairKey('water', 'turbine')]: 'generator',
  [pairKey('computer', 'writing')]: 'code',
  [pairKey('human', 'computer')]: 'code',
  [pairKey('computer', 'intelligence')]: 'ai',
  [pairKey('robot', 'knowledge')]: 'ai',
  [pairKey('metal', 'fire')]: 'forge',

  // ════════════════════════════════════════════════════════
  // SPACE
  // ════════════════════════════════════════════════════════
  [pairKey('earth', 'sun')]: 'moon',
  [pairKey('sky', 'water')]: 'moon',
  [pairKey('plasma', 'sky')]: 'star',
  [pairKey('sun', 'sky')]: 'star',
  [pairKey('rock', 'star')]: 'planet',
  [pairKey('earth', 'star')]: 'planet',
  [pairKey('ice', 'sky')]: 'comet',
  [pairKey('ice', 'star')]: 'comet',
  [pairKey('star', 'star')]: 'galaxy',
  [pairKey('nebula', 'star')]: 'galaxy',
  [pairKey('cloud', 'star')]: 'nebula',
  [pairKey('dust', 'star')]: 'nebula',
  [pairKey('rock', 'sky')]: 'meteor',
  [pairKey('asteroid', 'atmosphere')]: 'meteor',
  [pairKey('moon', 'sun')]: 'eclipse',
  [pairKey('galaxy', 'galaxy')]: 'cosmos',
  [pairKey('galaxy', 'star')]: 'cosmos',
  [pairKey('comet', 'rock')]: 'asteroid',
  [pairKey('comet', 'earth')]: 'asteroid',
  [pairKey('fire', 'star')]: 'supernova',
  [pairKey('star', 'volcano')]: 'supernova',
  [pairKey('galaxy', 'sun')]: 'blackHole',
  [pairKey('supernova', 'star')]: 'blackHole',
  [pairKey('blackHole', 'star')]: 'quasar',
  [pairKey('energy', 'blackHole')]: 'quasar',
  [pairKey('blackHole', 'cosmos')]: 'wormhole',
  [pairKey('rocket', 'human')]: 'spaceship',
  [pairKey('technology', 'rocket')]: 'spaceship',
  [pairKey('human', 'spaceship')]: 'astronaut',
  [pairKey('science', 'space')]: 'astronaut',
  [pairKey('planet', 'life')]: 'alien',
  [pairKey('cosmos', 'life')]: 'alien',

  // ════════════════════════════════════════════════════════
  // MYTHOLOGY / RELIGION
  // ════════════════════════════════════════════════════════
  [pairKey('life', 'smoke')]: 'spirit',
  [pairKey('human', 'smoke')]: 'spirit',
  [pairKey('death', 'human')]: 'spirit',
  [pairKey('dragon', 'human')]: 'myth',
  [pairKey('human', 'lightning')]: 'myth',
  [pairKey('knowledge', 'myth')]: 'legend',
  [pairKey('human', 'myth')]: 'legend',
  [pairKey('crystal', 'moon')]: 'magic',
  [pairKey('gem', 'moon')]: 'magic',
  [pairKey('religion', 'sun')]: 'sunGod',
  [pairKey('empire', 'sun')]: 'sunGod',
  [pairKey('magic', 'human')]: 'wizard',
  [pairKey('knowledge', 'magic')]: 'wizard',
  [pairKey('herb', 'moon')]: 'witch',
  [pairKey('flower', 'magic')]: 'fairy',
  [pairKey('giant', 'mountain')]: 'titan',
  [pairKey('giant', 'earth')]: 'titan',
  [pairKey('human', 'mountain')]: 'giant',
  [pairKey('stone', 'life')]: 'giant',
  [pairKey('light', 'human')]: 'angel',
  [pairKey('darkness', 'human')]: 'demon',
  [pairKey('forest', 'magic')]: 'elf',
  [pairKey('mine', 'human')]: 'dwarf',
  [pairKey('mountain', 'human')]: 'dwarf',
  [pairKey('war', 'human')]: 'orc',
  [pairKey('darkness', 'warrior')]: 'orc',
  [pairKey('bridge', 'giant')]: 'troll',
  [pairKey('cave', 'giant')]: 'troll',
  [pairKey('death', 'magic')]: 'necromancer',
  [pairKey('death', 'wizard')]: 'necromancer',
  [pairKey('soul', 'darkness')]: 'wraith',
  [pairKey('spirit', 'death')]: 'banshee',
  [pairKey('soul', 'fear')]: 'banshee',
  [pairKey('witch', 'magic')]: 'curse',
  [pairKey('stone', 'magic')]: 'rune',
  [pairKey('writing', 'magic')]: 'rune',
  [pairKey('human', 'night')]: 'vampire',
  [pairKey('bat', 'human')]: 'vampire',
  [pairKey('human', 'death')]: 'zombie',
  [pairKey('necromancer', 'human')]: 'zombie',

  // ════════════════════════════════════════════════════════
  // SCIENCE
  // ════════════════════════════════════════════════════════
  [pairKey('molecule', 'life')]: 'dna',
  [pairKey('cell', 'cell')]: 'dna',
  [pairKey('dna', 'time')]: 'evolution',
  [pairKey('life', 'time')]: 'evolution',
  [pairKey('earth', 'physics')]: 'gravity',
  [pairKey('iron', 'electricity')]: 'magnetism',
  [pairKey('metal', 'electricity')]: 'magnetism',
  [pairKey('molecule', 'fire')]: 'chemistry',
  [pairKey('mineral', 'science')]: 'chemistry',
  [pairKey('cell', 'science')]: 'biology',
  [pairKey('life', 'science')]: 'biology',
  [pairKey('energy', 'science')]: 'physics',
  [pairKey('atom', 'science')]: 'physics',
  [pairKey('bacteria', 'life')]: 'virus',
  [pairKey('water', 'life')]: 'bacteria',
  [pairKey('atom', 'life')]: 'cell',
  [pairKey('bacteria', 'light')]: 'cell',
  [pairKey('cell', 'life')]: 'gene',
  [pairKey('dna', 'science')]: 'gene',
  [pairKey('medicine', 'virus')]: 'vaccine',
  [pairKey('science', 'medicine')]: 'vaccine',
  [pairKey('atom', 'energy')]: 'radiation',
  [pairKey('nuclear', 'atom')]: 'radiation',

  // ════════════════════════════════════════════════════════
  // ABSTRACT / EMOTIONS
  // ════════════════════════════════════════════════════════
  [pairKey('air', 'electricity')]: 'sound',
  [pairKey('wave', 'air')]: 'sound',
  [pairKey('sound', 'human')]: 'music',
  [pairKey('drum', 'harp')]: 'music',
  [pairKey('human', 'heart')]: 'love',
  [pairKey('love', 'human')]: 'emotion',
  [pairKey('human', 'danger')]: 'fear',
  [pairKey('storm', 'order')]: 'chaos',
  [pairKey('void', 'life')]: 'chaos',
  [pairKey('chaos', 'order')]: 'balance',
  [pairKey('light', 'darkness')]: 'balance',
  [pairKey('life', 'time')]: 'death',
  [pairKey('void', 'life')]: 'death',
  [pairKey('death', 'spirit')]: 'soul',
  [pairKey('human', 'dream')]: 'soul',
  [pairKey('human', 'knowledge')]: 'mind',
  [pairKey('mind', 'sleep')]: 'dream',
  [pairKey('soul', 'night')]: 'dream',
  [pairKey('star', 'human')]: 'time',
  [pairKey('blackHole', 'universe')]: 'void',
  [pairKey('cosmos', 'cosmos')]: 'infinity',
  [pairKey('void', 'cosmos')]: 'infinity',
  [pairKey('knowledge', 'time')]: 'wisdom',
  [pairKey('chaos', 'mind')]: 'madness',
  [pairKey('void', 'mind')]: 'madness',
  [pairKey('sun', 'soul')]: 'hope',
  [pairKey('rainbow', 'human')]: 'hope',
  [pairKey('void', 'soul')]: 'despair',
  [pairKey('darkness', 'soul')]: 'despair',
  [pairKey('mind', 'time')]: 'memory',
  [pairKey('mind', 'question')]: 'thought',
  [pairKey('love', 'fear')]: 'emotion',
  [pairKey('soul', 'mind')]: 'consciousness',
  [pairKey('mind', 'life')]: 'consciousness',

  // ════════════════════════════════════════════════════════
  // CROSS-CATEGORY CHAINS
  // ════════════════════════════════════════════════════════
  [pairKey('forge', 'science')]: 'technology',
  [pairKey('warrior', 'horse')]: 'chariot',
  [pairKey('warrior', 'metal')]: 'armor',
  [pairKey('science', 'magic')]: 'alchemy',
  [pairKey('ocean', 'magic')]: 'siren',
  [pairKey('desert', 'magic')]: 'sphinx',
  [pairKey('storm', 'dragon')]: 'stormDragon',
  [pairKey('ocean', 'dragon')]: 'seaDragon',
  [pairKey('snow', 'dragon')]: 'iceDragon',
  [pairKey('human', 'computer')]: 'ai',
  [pairKey('electricity', 'computer')]: 'code',
  [pairKey('satellite', 'computer')]: 'internet',
  [pairKey('library', 'internet')]: 'internet',
};