let instanceCounter = 0;
export const generateInstanceId = () => `instance-${instanceCounter++}`;

export const STARTING_CONCEPT_IDS = ['fire', 'water', 'earth', 'air'];

export const createStartingInstances = () => {
  const instances = {};
  STARTING_CONCEPT_IDS.forEach((conceptId) => {
    for (let i = 0; i < 2; i++) {
      const instanceId = generateInstanceId();
      instances[instanceId] = { instanceId, conceptId };
    }
  });
  return instances;
};

export const CONCEPTS = {
  // ── STARTING ELEMENTS ──────────────────────────────────────────────
  fire:         { id: 'fire',         name: 'Fire',         emoji: '🔥',  category: 'Nature' },
  water:        { id: 'water',        name: 'Water',        emoji: '💧',  category: 'Nature' },
  earth:        { id: 'earth',        name: 'Earth',        emoji: '🌍',  category: 'Nature' },
  air:          { id: 'air',          name: 'Air',          emoji: '🌬️', category: 'Nature' },

  // ── WEATHER ────────────────────────────────────────────────────────
  steam:        { id: 'steam',        name: 'Steam',        emoji: '♨️',  category: 'Weather' },
  cloud:        { id: 'cloud',        name: 'Cloud',        emoji: '☁️',  category: 'Weather' },
  rain:         { id: 'rain',         name: 'Rain',         emoji: '🌧️', category: 'Weather' },
  snow:         { id: 'snow',         name: 'Snow',         emoji: '❄️',  category: 'Weather' },
  ice:          { id: 'ice',          name: 'Ice',          emoji: '🧊',  category: 'Weather' },
  lightning:    { id: 'lightning',    name: 'Lightning',    emoji: '⚡',  category: 'Weather' },
  thunder:      { id: 'thunder',      name: 'Thunder',      emoji: '🌩️', category: 'Weather' },
  storm:        { id: 'storm',        name: 'Storm',        emoji: '⛈️', category: 'Weather' },
  tornado:      { id: 'tornado',      name: 'Tornado',      emoji: '🌪️', category: 'Weather' },
  hurricane:    { id: 'hurricane',    name: 'Hurricane',    emoji: '🌀',  category: 'Weather' },
  typhoon:      { id: 'typhoon',      name: 'Typhoon',      emoji: '🌀',  category: 'Weather' },
  frost:        { id: 'frost',        name: 'Frost',        emoji: '🌨️', category: 'Weather' },
  blizzard:     { id: 'blizzard',     name: 'Blizzard',     emoji: '🌨️', category: 'Weather' },
  hail:         { id: 'hail',         name: 'Hail',         emoji: '🌨️', category: 'Weather' },
  rainbow:      { id: 'rainbow',      name: 'Rainbow',      emoji: '🌈',  category: 'Weather' },
  fog:          { id: 'fog',          name: 'Fog',          emoji: '🌫️', category: 'Weather' },
  aurora:       { id: 'aurora',       name: 'Aurora',       emoji: '🌌',  category: 'Weather' },
  monsoon:      { id: 'monsoon',      name: 'Monsoon',      emoji: '🌧️', category: 'Weather' },
  drought:      { id: 'drought',      name: 'Drought',      emoji: '🌵',  category: 'Weather' },
  heatwave:     { id: 'heatwave',     name: 'Heatwave',     emoji: '🌡️', category: 'Weather' },
  dew:          { id: 'dew',          name: 'Dew',          emoji: '💦',  category: 'Weather' },
  sandstorm:    { id: 'sandstorm',    name: 'Sandstorm',    emoji: '🌪️', category: 'Weather' },
  humidity:     { id: 'humidity',     name: 'Humidity',     emoji: '💧',  category: 'Weather' },
  mist:         { id: 'mist',         name: 'Mist',         emoji: '🌫️', category: 'Weather' },
  cumulus:      { id: 'cumulus',      name: 'Cumulus',      emoji: '☁️',  category: 'Weather' },

  // ── GEOLOGY / MATERIALS ────────────────────────────────────────────
  mud:          { id: 'mud',          name: 'Mud',          emoji: '🟤',  category: 'Nature' },
  lava:         { id: 'lava',         name: 'Lava',         emoji: '🌋🔥', category: 'Nature' },
  magma:        { id: 'magma',        name: 'Magma',        emoji: '🌋',  category: 'Nature' },
  volcano:      { id: 'volcano',      name: 'Volcano',      emoji: '🌋',  category: 'Nature' },
  eruption:     { id: 'eruption',     name: 'Eruption',     emoji: '🌋',  category: 'Nature' },
  rock:         { id: 'rock',         name: 'Rock',         emoji: '🪨',  category: 'Nature' },
  stone:        { id: 'stone',        name: 'Stone',        emoji: '🪨',  category: 'Nature' },
  sand:         { id: 'sand',         name: 'Sand',         emoji: '🏖️', category: 'Nature' },
  clay:         { id: 'clay',         name: 'Clay',         emoji: '🟤',  category: 'Nature' },
  soil:         { id: 'soil',         name: 'Soil',         emoji: '🌱',  category: 'Nature' },
  dust:         { id: 'dust',         name: 'Dust',         emoji: '💨',  category: 'Nature' },
  cave:         { id: 'cave',         name: 'Cave',         emoji: '🕳️', category: 'Nature' },
  coal:         { id: 'coal',         name: 'Coal',         emoji: '⬛',  category: 'Nature' },
  mineral:      { id: 'mineral',      name: 'Mineral',      emoji: '💎',  category: 'Nature' },
  metal:        { id: 'metal',        name: 'Metal',        emoji: '🔩',  category: 'Nature' },
  iron:         { id: 'iron',         name: 'Iron',         emoji: '⚙️',  category: 'Nature' },
  copper:       { id: 'copper',       name: 'Copper',       emoji: '🟠',  category: 'Nature' },
  gold:         { id: 'gold',         name: 'Gold',         emoji: '🥇',  category: 'Nature' },
  silver:       { id: 'silver',       name: 'Silver',       emoji: '🥈',  category: 'Nature' },
  bronze:       { id: 'bronze',       name: 'Bronze',       emoji: '🥉',  category: 'Nature' },
  steel:        { id: 'steel',        name: 'Steel',        emoji: '⚔️',  category: 'Nature' },
  rust:         { id: 'rust',         name: 'Rust',         emoji: '🟫',  category: 'Nature' },
  glass:        { id: 'glass',        name: 'Glass',        emoji: '🪟',  category: 'Nature' },
  obsidian:     { id: 'obsidian',     name: 'Obsidian',     emoji: '🖤',  category: 'Nature' },
  crystal:      { id: 'crystal',      name: 'Crystal',      emoji: '💎',  category: 'Nature' },
  gem:          { id: 'gem',          name: 'Gem',          emoji: '💎',  category: 'Nature' },
  diamond:      { id: 'diamond',      name: 'Diamond',      emoji: '💠',  category: 'Nature' },
  marble:       { id: 'marble',       name: 'Marble',       emoji: '🔷',  category: 'Nature' },
  quartz:       { id: 'quartz',       name: 'Quartz',       emoji: '🔹',  category: 'Nature' },
  amber:        { id: 'amber',        name: 'Amber',        emoji: '🟡',  category: 'Nature' },
  flint:        { id: 'flint',        name: 'Flint',        emoji: '🪨',  category: 'Nature' },
  salt:         { id: 'salt',         name: 'Salt',         emoji: '🧂',  category: 'Nature' },
  ash:          { id: 'ash',          name: 'Ash',          emoji: '💨',  category: 'Nature' },
  ashCloud:     { id: 'ashCloud',     name: 'Ash Cloud',    emoji: '☁️🌫️', category: 'Nature' },
  smoke:        { id: 'smoke',        name: 'Smoke',        emoji: '💨',  category: 'Nature' },
  peat:         { id: 'peat',         name: 'Peat',         emoji: '🟫',  category: 'Nature' },
  stalactite:   { id: 'stalactite',   name: 'Stalactite',   emoji: '🪨',  category: 'Nature' },
  hotSpring:    { id: 'hotSpring',    name: 'Hot Spring',   emoji: '♨️',  category: 'Nature' },
  quicksand:    { id: 'quicksand',    name: 'Quicksand',    emoji: '🟡',  category: 'Nature' },
  tar:          { id: 'tar',          name: 'Tar',          emoji: '⬛',  category: 'Nature' },
  chalk:        { id: 'chalk',        name: 'Chalk',        emoji: '⬜',  category: 'Nature' },
  permafrost:   { id: 'permafrost',   name: 'Permafrost',   emoji: '🧊',  category: 'Nature' },

  // ── ATMOSPHERE / AIR ────────────────────────────────────────────────
  atmosphere:   { id: 'atmosphere',   name: 'Atmosphere',   emoji: '🌍',  category: 'Nature' },
  oxygen:       { id: 'oxygen',       name: 'Oxygen',       emoji: '🫧',  category: 'Science' },
  plasma:       { id: 'plasma',       name: 'Plasma',       emoji: '⚡',  category: 'Science' },
  smog:         { id: 'smog',         name: 'Smog',         emoji: '🌫️', category: 'Nature' },
  pollution:    { id: 'pollution',    name: 'Pollution',    emoji: '☣️',  category: 'Nature' },
  sky:          { id: 'sky',          name: 'Sky',          emoji: '🌤️', category: 'Nature' },
  vapor:        { id: 'vapor',        name: 'Vapor',        emoji: '💨',  category: 'Nature' },
  waterVapor:   { id: 'waterVapor',   name: 'Water Vapor',  emoji: '💨',  category: 'Nature' },

  // ── WATER FEATURES ────────────────────────────────────────────────
  ocean:        { id: 'ocean',        name: 'Ocean',        emoji: '🌊',  category: 'Nature' },
  sea:          { id: 'sea',          name: 'Sea',          emoji: '🌊',  category: 'Nature' },
  river:        { id: 'river',        name: 'River',        emoji: '🏞️', category: 'Nature' },
  lake:         { id: 'lake',         name: 'Lake',         emoji: '🏞️', category: 'Nature' },
  pond:         { id: 'pond',         name: 'Pond',         emoji: '🌊',  category: 'Nature' },
  glacier:      { id: 'glacier',      name: 'Glacier',      emoji: '🏔️', category: 'Nature' },
  waterfall:    { id: 'waterfall',    name: 'Waterfall',    emoji: '💦',  category: 'Nature' },
  swamp:        { id: 'swamp',        name: 'Swamp',        emoji: '🌿',  category: 'Nature' },
  marsh:        { id: 'marsh',        name: 'Marsh',        emoji: '🌿',  category: 'Nature' },
  delta:        { id: 'delta',        name: 'Delta',        emoji: '🌊',  category: 'Nature' },
  tide:         { id: 'tide',         name: 'Tide',         emoji: '🌊',  category: 'Nature' },
  flood:        { id: 'flood',        name: 'Flood',        emoji: '🌊',  category: 'Nature' },
  wave:         { id: 'wave',         name: 'Wave',         emoji: '🌊',  category: 'Nature' },
  geyser:       { id: 'geyser',       name: 'Geyser',       emoji: '💦',  category: 'Nature' },
  whirlpool:    { id: 'whirlpool',    name: 'Whirlpool',    emoji: '🌀',  category: 'Nature' },

  // ── LANDFORMS ──────────────────────────────────────────────────────
  mountain:     { id: 'mountain',     name: 'Mountain',     emoji: '⛰️',  category: 'Nature' },
  island:       { id: 'island',       name: 'Island',       emoji: '🏝️', category: 'Nature' },
  desert:       { id: 'desert',       name: 'Desert',       emoji: '🏜️', category: 'Nature' },
  beach:        { id: 'beach',        name: 'Beach',        emoji: '🏖️', category: 'Nature' },
  canyon:       { id: 'canyon',       name: 'Canyon',       emoji: '🏜️', category: 'Nature' },
  oasis:        { id: 'oasis',        name: 'Oasis',        emoji: '🌴',  category: 'Nature' },
  prairie:      { id: 'prairie',      name: 'Prairie',      emoji: '🌾',  category: 'Nature' },
  cliff:        { id: 'cliff',        name: 'Cliff',        emoji: '⛰️',  category: 'Nature' },
  tundra:       { id: 'tundra',       name: 'Tundra',       emoji: '🌨️', category: 'Nature' },
  plateau:      { id: 'plateau',      name: 'Plateau',      emoji: '🏔️', category: 'Nature' },
  valley:       { id: 'valley',       name: 'Valley',       emoji: '🏞️', category: 'Nature' },

  // ── LIFE ────────────────────────────────────────────────────────────
  life:         { id: 'life',         name: 'Life',         emoji: '✨',  category: 'Nature' },

  // ── PLANTS / NATURE ─────────────────────────────────────────────────
  plant:        { id: 'plant',        name: 'Plant',        emoji: '🌿',  category: 'Nature' },
  grass:        { id: 'grass',        name: 'Grass',        emoji: '🌿',  category: 'Nature' },
  flower:       { id: 'flower',       name: 'Flower',       emoji: '🌸',  category: 'Nature' },
  seed:         { id: 'seed',         name: 'Seed',         emoji: '🌱',  category: 'Nature' },
  tree:         { id: 'tree',         name: 'Tree',         emoji: '🌳',  category: 'Nature' },
  forest:       { id: 'forest',       name: 'Forest',       emoji: '🌲',  category: 'Nature' },
  jungle:       { id: 'jungle',       name: 'Jungle',       emoji: '🌴',  category: 'Nature' },
  wood:         { id: 'wood',         name: 'Wood',         emoji: '🪵',  category: 'Nature' },
  charcoal:     { id: 'charcoal',     name: 'Charcoal',     emoji: '⬛',  category: 'Nature' },
  leaf:         { id: 'leaf',         name: 'Leaf',         emoji: '🍃',  category: 'Nature' },
  moss:         { id: 'moss',         name: 'Moss',         emoji: '🌿',  category: 'Nature' },
  algae:        { id: 'algae',        name: 'Algae',        emoji: '🌿',  category: 'Nature' },
  seaweed:      { id: 'seaweed',      name: 'Seaweed',      emoji: '🌿',  category: 'Nature' },
  mushroom:     { id: 'mushroom',     name: 'Mushroom',     emoji: '🍄',  category: 'Nature' },
  fruit:        { id: 'fruit',        name: 'Fruit',        emoji: '🍎',  category: 'Nature' },
  vine:         { id: 'vine',         name: 'Vine',         emoji: '🌿',  category: 'Nature' },
  cactus:       { id: 'cactus',       name: 'Cactus',       emoji: '🌵',  category: 'Nature' },
  bamboo:       { id: 'bamboo',       name: 'Bamboo',       emoji: '🎋',  category: 'Nature' },
  coral:        { id: 'coral',        name: 'Coral',        emoji: '🪸',  category: 'Nature' },
  reef:         { id: 'reef',         name: 'Reef',         emoji: '🪸',  category: 'Nature' },
  spore:        { id: 'spore',        name: 'Spore',        emoji: '🍄',  category: 'Nature' },
  grain:        { id: 'grain',        name: 'Grain',        emoji: '🌾',  category: 'Nature' },
  pollen:       { id: 'pollen',       name: 'Pollen',       emoji: '🌼',  category: 'Nature' },
  herb:         { id: 'herb',         name: 'Herb',         emoji: '🌿',  category: 'Nature' },
  kelp:         { id: 'kelp',         name: 'Kelp',         emoji: '🌿',  category: 'Nature' },
  wheat:        { id: 'wheat',        name: 'Wheat',        emoji: '🌾',  category: 'Nature' },
  fern:         { id: 'fern',         name: 'Fern',         emoji: '🌿',  category: 'Nature' },
  rose:         { id: 'rose',         name: 'Rose',         emoji: '🌹',  category: 'Nature' },
  ivy:          { id: 'ivy',          name: 'Ivy',          emoji: '🌿',  category: 'Nature' },
  oak:          { id: 'oak',          name: 'Oak',          emoji: '🌳',  category: 'Nature' },
  pine:         { id: 'pine',         name: 'Pine',         emoji: '🌲',  category: 'Nature' },
  cotton:       { id: 'cotton',       name: 'Cotton',       emoji: '🌸',  category: 'Nature' },
  tobacco:      { id: 'tobacco',      name: 'Tobacco',      emoji: '🌿',  category: 'Nature' },
  lily:         { id: 'lily',         name: 'Lily',         emoji: '🌸',  category: 'Nature' },
  sunflower:    { id: 'sunflower',    name: 'Sunflower',    emoji: '🌻',  category: 'Nature' },
  rice:         { id: 'rice',         name: 'Rice',         emoji: '🌾',  category: 'Nature' },
  mangrove:     { id: 'mangrove',     name: 'Mangrove',     emoji: '🌴',  category: 'Nature' },

  // ── ANIMALS ─────────────────────────────────────────────────────────
  fish:         { id: 'fish',         name: 'Fish',         emoji: '🐟',  category: 'Animals' },
  insect:       { id: 'insect',       name: 'Insect',       emoji: '🐛',  category: 'Animals' },
  worm:         { id: 'worm',         name: 'Worm',         emoji: '🪱',  category: 'Animals' },
  bee:          { id: 'bee',          name: 'Bee',          emoji: '🐝',  category: 'Animals' },
  butterfly:    { id: 'butterfly',    name: 'Butterfly',    emoji: '🦋',  category: 'Animals' },
  bird:         { id: 'bird',         name: 'Bird',         emoji: '🐦',  category: 'Animals' },
  eagle:        { id: 'eagle',        name: 'Eagle',        emoji: '🦅',  category: 'Animals' },
  owl:          { id: 'owl',          name: 'Owl',          emoji: '🦉',  category: 'Animals' },
  hawk:         { id: 'hawk',         name: 'Hawk',         emoji: '🦅',  category: 'Animals' },
  snake:        { id: 'snake',        name: 'Snake',        emoji: '🐍',  category: 'Animals' },
  lizard:       { id: 'lizard',       name: 'Lizard',       emoji: '🦎',  category: 'Animals' },
  frog:         { id: 'frog',         name: 'Frog',         emoji: '🐸',  category: 'Animals' },
  wolf:         { id: 'wolf',         name: 'Wolf',         emoji: '🐺',  category: 'Animals' },
  bear:         { id: 'bear',         name: 'Bear',         emoji: '🐻',  category: 'Animals' },
  deer:         { id: 'deer',         name: 'Deer',         emoji: '🦌',  category: 'Animals' },
  horse:        { id: 'horse',        name: 'Horse',        emoji: '🐴',  category: 'Animals' },
  whale:        { id: 'whale',        name: 'Whale',        emoji: '🐋',  category: 'Animals' },
  shark:        { id: 'shark',        name: 'Shark',        emoji: '🦈',  category: 'Animals' },
  dolphin:      { id: 'dolphin',      name: 'Dolphin',      emoji: '🐬',  category: 'Animals' },
  crab:         { id: 'crab',         name: 'Crab',         emoji: '🦀',  category: 'Animals' },
  turtle:       { id: 'turtle',       name: 'Turtle',       emoji: '🐢',  category: 'Animals' },
  dinosaur:     { id: 'dinosaur',     name: 'Dinosaur',     emoji: '🦕',  category: 'Animals' },
  mammoth:      { id: 'mammoth',      name: 'Mammoth',      emoji: '🦣',  category: 'Animals' },
  cat:          { id: 'cat',          name: 'Cat',          emoji: '🐱',  category: 'Animals' },
  dog:          { id: 'dog',          name: 'Dog',          emoji: '🐶',  category: 'Animals' },
  rabbit:       { id: 'rabbit',       name: 'Rabbit',       emoji: '🐰',  category: 'Animals' },
  pig:          { id: 'pig',          name: 'Pig',          emoji: '🐷',  category: 'Animals' },
  cow:          { id: 'cow',          name: 'Cow',          emoji: '🐄',  category: 'Animals' },
  sheep:        { id: 'sheep',        name: 'Sheep',        emoji: '🐑',  category: 'Animals' },
  lion:         { id: 'lion',         name: 'Lion',         emoji: '🦁',  category: 'Animals' },
  tiger:        { id: 'tiger',        name: 'Tiger',        emoji: '🐯',  category: 'Animals' },
  elephant:     { id: 'elephant',     name: 'Elephant',     emoji: '🐘',  category: 'Animals' },
  penguin:      { id: 'penguin',      name: 'Penguin',      emoji: '🐧',  category: 'Animals' },
  seal:         { id: 'seal',         name: 'Seal',         emoji: '🦭',  category: 'Animals' },
  octopus:      { id: 'octopus',      name: 'Octopus',      emoji: '🐙',  category: 'Animals' },
  jellyfish:    { id: 'jellyfish',    name: 'Jellyfish',    emoji: '🪼',  category: 'Animals' },
  lobster:      { id: 'lobster',      name: 'Lobster',      emoji: '🦞',  category: 'Animals' },
  ant:          { id: 'ant',          name: 'Ant',          emoji: '🐜',  category: 'Animals' },
  spider:       { id: 'spider',       name: 'Spider',       emoji: '🕷️', category: 'Animals' },
  scorpion:     { id: 'scorpion',     name: 'Scorpion',     emoji: '🦂',  category: 'Animals' },
  firefly:      { id: 'firefly',      name: 'Firefly',      emoji: '✨',  category: 'Animals' },
  moth:         { id: 'moth',         name: 'Moth',         emoji: '🦋',  category: 'Animals' },
  cricket:      { id: 'cricket',      name: 'Cricket',      emoji: '🦗',  category: 'Animals' },
  mosquito:     { id: 'mosquito',     name: 'Mosquito',     emoji: '🦟',  category: 'Animals' },
  salmon:       { id: 'salmon',       name: 'Salmon',       emoji: '🐟',  category: 'Animals' },
  squid:        { id: 'squid',        name: 'Squid',        emoji: '🦑',  category: 'Animals' },
  clam:         { id: 'clam',         name: 'Clam',         emoji: '🦪',  category: 'Animals' },
  fox:          { id: 'fox',          name: 'Fox',          emoji: '🦊',  category: 'Animals' },
  bat:          { id: 'bat',          name: 'Bat',          emoji: '🦇',  category: 'Animals' },
  raven:        { id: 'raven',        name: 'Raven',        emoji: '🐦‍⬛', category: 'Animals' },
  crocodile:    { id: 'crocodile',    name: 'Crocodile',    emoji: '🐊',  category: 'Animals' },
  gorilla:      { id: 'gorilla',      name: 'Gorilla',      emoji: '🦍',  category: 'Animals' },
  panther:      { id: 'panther',      name: 'Panther',      emoji: '🐆',  category: 'Animals' },

  // ── MYTHICAL CREATURES ──────────────────────────────────────────────
  dragon:       { id: 'dragon',       name: 'Dragon',       emoji: '🐉',  category: 'Fantasy' },
  phoenix:      { id: 'phoenix',      name: 'Phoenix',      emoji: '🔥🦅', category: 'Fantasy' },
  kraken:       { id: 'kraken',       name: 'Kraken',       emoji: '🐙',  category: 'Fantasy' },
  leviathan:    { id: 'leviathan',    name: 'Leviathan',    emoji: '🐉🌊', category: 'Fantasy' },
  unicorn:      { id: 'unicorn',      name: 'Unicorn',      emoji: '🦄',  category: 'Fantasy' },
  griffin:      { id: 'griffin',      name: 'Griffin',      emoji: '🦅🦁', category: 'Fantasy' },
  hydra:        { id: 'hydra',        name: 'Hydra',        emoji: '🐉',  category: 'Fantasy' },
  chimera:      { id: 'chimera',      name: 'Chimera',      emoji: '🔥🦁', category: 'Fantasy' },
  sphinx:       { id: 'sphinx',       name: 'Sphinx',       emoji: '🦁',  category: 'Fantasy' },
  minotaur:     { id: 'minotaur',     name: 'Minotaur',     emoji: '🐂',  category: 'Fantasy' },
  centaur:      { id: 'centaur',      name: 'Centaur',      emoji: '🐴',  category: 'Fantasy' },
  siren:        { id: 'siren',        name: 'Siren',        emoji: '🧜',  category: 'Fantasy' },
  basilisk:     { id: 'basilisk',     name: 'Basilisk',     emoji: '🐍',  category: 'Fantasy' },
  manticore:    { id: 'manticore',    name: 'Manticore',    emoji: '🦂🦁', category: 'Fantasy' },
  seaDragon:    { id: 'seaDragon',    name: 'Sea Dragon',   emoji: '🐉🌊', category: 'Fantasy' },
  iceDragon:    { id: 'iceDragon',    name: 'Ice Dragon',   emoji: '🐉❄️', category: 'Fantasy' },
  stormDragon:  { id: 'stormDragon',  name: 'Storm Dragon', emoji: '🐉⚡', category: 'Fantasy' },

  // ── CIVILIZATION ────────────────────────────────────────────────────
  human:        { id: 'human',        name: 'Human',        emoji: '🧑',  category: 'Civilization' },
  tribe:        { id: 'tribe',        name: 'Tribe',        emoji: '👥',  category: 'Civilization' },
  village:      { id: 'village',      name: 'Village',      emoji: '🏘️', category: 'Civilization' },
  city:         { id: 'city',         name: 'City',         emoji: '🏙️', category: 'Civilization' },
  empire:       { id: 'empire',       name: 'Empire',       emoji: '👑',  category: 'Civilization' },
  civilization: { id: 'civilization', name: 'Civilization', emoji: '🏛️', category: 'Civilization' },
  house:        { id: 'house',        name: 'House',        emoji: '🏠',  category: 'Civilization' },
  castle:       { id: 'castle',       name: 'Castle',       emoji: '🏰',  category: 'Civilization' },
  fortress:     { id: 'fortress',     name: 'Fortress',     emoji: '🏯',  category: 'Civilization' },
  temple:       { id: 'temple',       name: 'Temple',       emoji: '🛕',  category: 'Civilization' },
  pyramid:      { id: 'pyramid',      name: 'Pyramid',      emoji: '🔺',  category: 'Civilization' },
  colosseum:    { id: 'colosseum',    name: 'Colosseum',    emoji: '🏟️', category: 'Civilization' },
  lighthouse:   { id: 'lighthouse',   name: 'Lighthouse',   emoji: '🗼',  category: 'Civilization' },
  harbor:       { id: 'harbor',       name: 'Harbor',       emoji: '⚓',  category: 'Civilization' },
  market:       { id: 'market',       name: 'Market',       emoji: '🏪',  category: 'Civilization' },
  library:      { id: 'library',      name: 'Library',      emoji: '📚',  category: 'Civilization' },
  school:       { id: 'school',       name: 'School',       emoji: '🏫',  category: 'Civilization' },
  hospital:     { id: 'hospital',     name: 'Hospital',     emoji: '🏥',  category: 'Civilization' },
  bank:         { id: 'bank',         name: 'Bank',         emoji: '🏦',  category: 'Civilization' },
  museum:       { id: 'museum',       name: 'Museum',       emoji: '🏛️', category: 'Civilization' },
  prison:       { id: 'prison',       name: 'Prison',       emoji: '⛓️', category: 'Civilization' },
  arena:        { id: 'arena',        name: 'Arena',        emoji: '⚔️',  category: 'Civilization' },
  monument:     { id: 'monument',     name: 'Monument',     emoji: '🗿',  category: 'Civilization' },
  aqueduct:     { id: 'aqueduct',     name: 'Aqueduct',     emoji: '🌉',  category: 'Civilization' },
  tomb:         { id: 'tomb',         name: 'Tomb',         emoji: '⛩️', category: 'Civilization' },
  throne:       { id: 'throne',       name: 'Throne',       emoji: '💺',  category: 'Civilization' },
  garden:       { id: 'garden',       name: 'Garden',       emoji: '🌷',  category: 'Civilization' },
  farm:         { id: 'farm',         name: 'Farm',         emoji: '🌾',  category: 'Civilization' },
  mine:         { id: 'mine',         name: 'Mine',         emoji: '⛏️', category: 'Civilization' },

  // ── TOOLS / OBJECTS ─────────────────────────────────────────────────
  tool:         { id: 'tool',         name: 'Tool',         emoji: '🔧',  category: 'Objects' },
  weapon:       { id: 'weapon',       name: 'Weapon',       emoji: '⚔️',  category: 'Objects' },
  sword:        { id: 'sword',        name: 'Sword',        emoji: '⚔️',  category: 'Objects' },
  armor:        { id: 'armor',        name: 'Armor',        emoji: '🛡️', category: 'Objects' },
  bow:          { id: 'bow',          name: 'Bow',          emoji: '🏹',  category: 'Objects' },
  arrow:        { id: 'arrow',        name: 'Arrow',        emoji: '➡️',  category: 'Objects' },
  axe:          { id: 'axe',          name: 'Axe',          emoji: '🪓',  category: 'Objects' },
  hammer:       { id: 'hammer',       name: 'Hammer',       emoji: '🔨',  category: 'Objects' },
  plow:         { id: 'plow',         name: 'Plow',         emoji: '⚙️',  category: 'Objects' },
  gun:          { id: 'gun',          name: 'Gun',          emoji: '🔫',  category: 'Objects' },
  cannon:       { id: 'cannon',       name: 'Cannon',       emoji: '💣',  category: 'Objects' },
  catapult:     { id: 'catapult',     name: 'Catapult',     emoji: '⚙️',  category: 'Objects' },
  chariot:      { id: 'chariot',      name: 'Chariot',      emoji: '🏇',  category: 'Objects' },
  ship:         { id: 'ship',         name: 'Ship',         emoji: '⛵',  category: 'Objects' },
  wheel:        { id: 'wheel',        name: 'Wheel',        emoji: '⚙️',  category: 'Objects' },
  mill:         { id: 'mill',         name: 'Mill',         emoji: '⚙️',  category: 'Objects' },
  bridge:       { id: 'bridge',       name: 'Bridge',       emoji: '🌉',  category: 'Objects' },
  forge:        { id: 'forge',        name: 'Forge',        emoji: '🔥⚙️', category: 'Objects' },
  compass:      { id: 'compass',      name: 'Compass',      emoji: '🧭',  category: 'Objects' },
  telescope:    { id: 'telescope',    name: 'Telescope',    emoji: '🔭',  category: 'Objects' },
  clock:        { id: 'clock',        name: 'Clock',        emoji: '🕐',  category: 'Objects' },
  map:          { id: 'map',          name: 'Map',          emoji: '🗺️', category: 'Objects' },
  key:          { id: 'key',          name: 'Key',          emoji: '🗝️', category: 'Objects' },
  lock:         { id: 'lock',         name: 'Lock',         emoji: '🔒',  category: 'Objects' },
  rope:         { id: 'rope',         name: 'Rope',         emoji: '🪢',  category: 'Objects' },
  net:          { id: 'net',          name: 'Net',          emoji: '🕸️', category: 'Objects' },
  candle:       { id: 'candle',       name: 'Candle',       emoji: '🕯️', category: 'Objects' },
  lantern:      { id: 'lantern',      name: 'Lantern',      emoji: '🏮',  category: 'Objects' },
  torch:        { id: 'torch',        name: 'Torch',        emoji: '🔦',  category: 'Objects' },
  mirror:       { id: 'mirror',       name: 'Mirror',       emoji: '🪞',  category: 'Objects' },
  coin:         { id: 'coin',         name: 'Coin',         emoji: '🪙',  category: 'Objects' },
  ring:         { id: 'ring',         name: 'Ring',         emoji: '💍',  category: 'Objects' },
  crown:        { id: 'crown',        name: 'Crown',        emoji: '👑',  category: 'Objects' },
  flag:         { id: 'flag',         name: 'Flag',         emoji: '🚩',  category: 'Objects' },
  statue:       { id: 'statue',       name: 'Statue',       emoji: '🗿',  category: 'Objects' },
  bell:         { id: 'bell',         name: 'Bell',         emoji: '🔔',  category: 'Objects' },
  drum:         { id: 'drum',         name: 'Drum',         emoji: '🥁',  category: 'Objects' },
  harp:         { id: 'harp',         name: 'Harp',         emoji: '🎵',  category: 'Objects' },
  paper:        { id: 'paper',        name: 'Paper',        emoji: '📄',  category: 'Objects' },
  book:         { id: 'book',         name: 'Book',         emoji: '📚',  category: 'Objects' },
  scroll:       { id: 'scroll',       name: 'Scroll',       emoji: '📜',  category: 'Objects' },

  // ── KNOWLEDGE / SOCIETY ─────────────────────────────────────────────
  writing:      { id: 'writing',      name: 'Writing',      emoji: '✍️',  category: 'Civilization' },
  knowledge:    { id: 'knowledge',    name: 'Knowledge',    emoji: '📖',  category: 'Civilization' },
  science:      { id: 'science',      name: 'Science',      emoji: '🔬',  category: 'Science' },
  technology:   { id: 'technology',   name: 'Technology',   emoji: '💻',  category: 'Technology' },
  medicine:     { id: 'medicine',     name: 'Medicine',     emoji: '💊',  category: 'Civilization' },
  religion:     { id: 'religion',     name: 'Religion',     emoji: '🙏',  category: 'Civilization' },
  army:         { id: 'army',         name: 'Army',         emoji: '⚔️',  category: 'Civilization' },
  war:          { id: 'war',          name: 'War',          emoji: '💥',  category: 'Civilization' },
  myth:         { id: 'myth',         name: 'Myth',         emoji: '📖✨', category: 'Fantasy' },
  legend:       { id: 'legend',       name: 'Legend',       emoji: '📜✨', category: 'Fantasy' },
  magic:        { id: 'magic',        name: 'Magic',        emoji: '✨',  category: 'Fantasy' },
  alchemy:      { id: 'alchemy',      name: 'Alchemy',      emoji: '⚗️',  category: 'Fantasy' },
  sunGod:       { id: 'sunGod',       name: 'Sun God',      emoji: '☀️🙏', category: 'Mythology' },

  // ── FOOD / ALCHEMY ──────────────────────────────────────────────────
  flour:        { id: 'flour',        name: 'Flour',        emoji: '🌾',  category: 'Food' },
  bread:        { id: 'bread',        name: 'Bread',        emoji: '🍞',  category: 'Food' },
  honey:        { id: 'honey',        name: 'Honey',        emoji: '🍯',  category: 'Food' },
  wine:         { id: 'wine',         name: 'Wine',         emoji: '🍷',  category: 'Food' },
  beer:         { id: 'beer',         name: 'Beer',         emoji: '🍺',  category: 'Food' },
  soup:         { id: 'soup',         name: 'Soup',         emoji: '🍲',  category: 'Food' },
  tea:          { id: 'tea',          name: 'Tea',          emoji: '🍵',  category: 'Food' },
  oil:          { id: 'oil',          name: 'Oil',          emoji: '🫙',  category: 'Food' },
  potion:       { id: 'potion',       name: 'Potion',       emoji: '⚗️',  category: 'Fantasy' },
  elixir:       { id: 'elixir',       name: 'Elixir',       emoji: '✨⚗️', category: 'Fantasy' },
  acid:         { id: 'acid',         name: 'Acid',         emoji: '⚗️',  category: 'Science' },
  gunpowder:    { id: 'gunpowder',    name: 'Gunpowder',    emoji: '💥',  category: 'Objects' },
  meat:         { id: 'meat',         name: 'Meat',         emoji: '🥩',  category: 'Food' },
  alcohol:      { id: 'alcohol',      name: 'Alcohol',      emoji: '🍾',  category: 'Food' },
  milk:         { id: 'milk',         name: 'Milk',         emoji: '🥛',  category: 'Food' },
  cheese:       { id: 'cheese',       name: 'Cheese',       emoji: '🧀',  category: 'Food' },
  butter:       { id: 'butter',       name: 'Butter',       emoji: '🧈',  category: 'Food' },
  sugar:        { id: 'sugar',        name: 'Sugar',        emoji: '🍬',  category: 'Food' },
  chocolate:    { id: 'chocolate',    name: 'Chocolate',    emoji: '🍫',  category: 'Food' },
  coffee:       { id: 'coffee',       name: 'Coffee',       emoji: '☕',  category: 'Food' },
  spice:        { id: 'spice',        name: 'Spice',        emoji: '🌶️', category: 'Food' },
  venom:        { id: 'venom',        name: 'Venom',        emoji: '🐍',  category: 'Science' },
  poison:       { id: 'poison',       name: 'Poison',       emoji: '☠️',  category: 'Science' },

  // ── ENERGY / DISASTERS ──────────────────────────────────────────────
  electricity:  { id: 'electricity',  name: 'Electricity',  emoji: '⚡',  category: 'Energy' },
  explosion:    { id: 'explosion',    name: 'Explosion',    emoji: '💥',  category: 'Energy' },
  firestorm:    { id: 'firestorm',    name: 'Firestorm',    emoji: '🔥🌪️', category: 'Energy' },
  earthquake:   { id: 'earthquake',   name: 'Earthquake',   emoji: '🌍💥', category: 'Energy' },
  tsunami:      { id: 'tsunami',      name: 'Tsunami',      emoji: '🌊',  category: 'Energy' },
  avalanche:    { id: 'avalanche',    name: 'Avalanche',    emoji: '🏔️💥', category: 'Energy' },
  energy:       { id: 'energy',       name: 'Energy',       emoji: '⚡',  category: 'Energy' },
  light:        { id: 'light',        name: 'Light',        emoji: '💡',  category: 'Energy' },
  darkness:     { id: 'darkness',     name: 'Darkness',     emoji: '🌑',  category: 'Energy' },
  radiation:    { id: 'radiation',    name: 'Radiation',    emoji: '☢️',  category: 'Science' },
  nuclear:      { id: 'nuclear',      name: 'Nuclear',      emoji: '☢️',  category: 'Technology' },
  solar:        { id: 'solar',        name: 'Solar',        emoji: '☀️',  category: 'Energy' },

  // ── TECHNOLOGY ──────────────────────────────────────────────────────
  steamEngine:  { id: 'steamEngine',  name: 'Steam Engine', emoji: '🚂',  category: 'Technology' },
  engine:       { id: 'engine',       name: 'Engine',       emoji: '⚙️',  category: 'Technology' },
  machine:      { id: 'machine',      name: 'Machine',      emoji: '⚙️',  category: 'Technology' },
  factory:      { id: 'factory',      name: 'Factory',      emoji: '🏭',  category: 'Technology' },
  car:          { id: 'car',          name: 'Car',          emoji: '🚗',  category: 'Technology' },
  train:        { id: 'train',        name: 'Train',        emoji: '🚂',  category: 'Technology' },
  airplane:     { id: 'airplane',     name: 'Airplane',     emoji: '✈️',  category: 'Technology' },
  rocket:       { id: 'rocket',       name: 'Rocket',       emoji: '🚀',  category: 'Technology' },
  satellite:    { id: 'satellite',    name: 'Satellite',    emoji: '🛰️', category: 'Technology' },
  computer:     { id: 'computer',     name: 'Computer',     emoji: '💻',  category: 'Technology' },
  internet:     { id: 'internet',     name: 'Internet',     emoji: '🌐',  category: 'Technology' },
  robot:        { id: 'robot',        name: 'Robot',        emoji: '🤖',  category: 'Technology' },
  phone:        { id: 'phone',        name: 'Phone',        emoji: '📱',  category: 'Technology' },
  camera:       { id: 'camera',       name: 'Camera',       emoji: '📷',  category: 'Technology' },
  radio:        { id: 'radio',        name: 'Radio',        emoji: '📻',  category: 'Technology' },
  television:   { id: 'television',   name: 'Television',   emoji: '📺',  category: 'Technology' },
  battery:      { id: 'battery',      name: 'Battery',      emoji: '🔋',  category: 'Technology' },
  laser:        { id: 'laser',        name: 'Laser',        emoji: '🔴',  category: 'Technology' },
  bomb:         { id: 'bomb',         name: 'Bomb',         emoji: '💣',  category: 'Technology' },
  drone:        { id: 'drone',        name: 'Drone',        emoji: '🚁',  category: 'Technology' },
  submarine:    { id: 'submarine',    name: 'Submarine',    emoji: '🤿',  category: 'Technology' },
  microscope:   { id: 'microscope',   name: 'Microscope',   emoji: '🔬',  category: 'Technology' },
  reactor:      { id: 'reactor',      name: 'Reactor',      emoji: '☢️',  category: 'Technology' },
  generator:    { id: 'generator',    name: 'Generator',    emoji: '⚡',  category: 'Technology' },
  code:         { id: 'code',         name: 'Code',         emoji: '💻',  category: 'Technology' },
  ai:           { id: 'ai',           name: 'AI',           emoji: '🤖',  category: 'Technology' },

  // ── SPACE ────────────────────────────────────────────────────────────
  sun:          { id: 'sun',          name: 'Sun',          emoji: '☀️',  category: 'Space' },
  moon:         { id: 'moon',         name: 'Moon',         emoji: '🌕',  category: 'Space' },
  star:         { id: 'star',         name: 'Star',         emoji: '⭐',  category: 'Space' },
  planet:       { id: 'planet',       name: 'Planet',       emoji: '🪐',  category: 'Space' },
  comet:        { id: 'comet',        name: 'Comet',        emoji: '☄️',  category: 'Space' },
  nebula:       { id: 'nebula',       name: 'Nebula',       emoji: '🌌',  category: 'Space' },
  galaxy:       { id: 'galaxy',       name: 'Galaxy',       emoji: '🌌',  category: 'Space' },
  cosmos:       { id: 'cosmos',       name: 'Cosmos',       emoji: '🌌',  category: 'Space' },
  meteor:       { id: 'meteor',       name: 'Meteor',       emoji: '☄️',  category: 'Space' },
  asteroid:     { id: 'asteroid',     name: 'Asteroid',     emoji: '🪨',  category: 'Space' },
  eclipse:      { id: 'eclipse',      name: 'Eclipse',      emoji: '🌑',  category: 'Space' },
  supernova:    { id: 'supernova',    name: 'Supernova',    emoji: '💥⭐', category: 'Space' },
  blackHole:    { id: 'blackHole',    name: 'Black Hole',   emoji: '🕳️', category: 'Space' },
  quasar:       { id: 'quasar',       name: 'Quasar',       emoji: '🌌',  category: 'Space' },
  wormhole:     { id: 'wormhole',     name: 'Wormhole',     emoji: '🕳️', category: 'Space' },
  spaceship:    { id: 'spaceship',    name: 'Spaceship',    emoji: '🛸',  category: 'Space' },
  astronaut:    { id: 'astronaut',    name: 'Astronaut',    emoji: '👨‍🚀', category: 'Space' },
  alien:        { id: 'alien',        name: 'Alien',        emoji: '👽',  category: 'Space' },

  // ── MYTHOLOGY / FANTASY ─────────────────────────────────────────────
  golem:        { id: 'golem',        name: 'Golem',        emoji: '🗿',  category: 'Fantasy' },
  spirit:       { id: 'spirit',       name: 'Spirit',       emoji: '👻',  category: 'Fantasy' },
  vampire:      { id: 'vampire',      name: 'Vampire',      emoji: '🧛',  category: 'Fantasy' },
  werewolf:     { id: 'werewolf',     name: 'Werewolf',     emoji: '🐺',  category: 'Fantasy' },
  zombie:       { id: 'zombie',       name: 'Zombie',       emoji: '🧟',  category: 'Fantasy' },
  witch:        { id: 'witch',        name: 'Witch',        emoji: '🧙‍♀️', category: 'Fantasy' },
  wizard:       { id: 'wizard',       name: 'Wizard',       emoji: '🧙',  category: 'Fantasy' },
  fairy:        { id: 'fairy',        name: 'Fairy',        emoji: '🧚',  category: 'Fantasy' },
  giant:        { id: 'giant',        name: 'Giant',        emoji: '🗿',  category: 'Fantasy' },
  titan:        { id: 'titan',        name: 'Titan',        emoji: '⛰️',  category: 'Fantasy' },
  angel:        { id: 'angel',        name: 'Angel',        emoji: '👼',  category: 'Fantasy' },
  demon:        { id: 'demon',        name: 'Demon',        emoji: '😈',  category: 'Fantasy' },
  elf:          { id: 'elf',          name: 'Elf',          emoji: '🧝',  category: 'Fantasy' },
  dwarf:        { id: 'dwarf',        name: 'Dwarf',        emoji: '⛏️', category: 'Fantasy' },
  orc:          { id: 'orc',          name: 'Orc',          emoji: '👹',  category: 'Fantasy' },
  troll:        { id: 'troll',        name: 'Troll',        emoji: '👹',  category: 'Fantasy' },
  necromancer:  { id: 'necromancer',  name: 'Necromancer',  emoji: '💀',  category: 'Fantasy' },
  wraith:       { id: 'wraith',       name: 'Wraith',       emoji: '👻',  category: 'Fantasy' },
  banshee:      { id: 'banshee',      name: 'Banshee',      emoji: '👻',  category: 'Fantasy' },
  curse:        { id: 'curse',        name: 'Curse',        emoji: '💀',  category: 'Fantasy' },
  rune:         { id: 'rune',         name: 'Rune',         emoji: '🔮',  category: 'Fantasy' },
  valkyrie:     { id: 'valkyrie',     name: 'Valkyrie',     emoji: '⚔️',  category: 'Fantasy' },

  // ── SCIENCE / ABSTRACT ──────────────────────────────────────────────
  atom:         { id: 'atom',         name: 'Atom',         emoji: '⚛️',  category: 'Science' },
  molecule:     { id: 'molecule',     name: 'Molecule',     emoji: '⚗️',  category: 'Science' },
  dna:          { id: 'dna',          name: 'DNA',          emoji: '🧬',  category: 'Science' },
  evolution:    { id: 'evolution',    name: 'Evolution',    emoji: '🧬',  category: 'Science' },
  gravity:      { id: 'gravity',      name: 'Gravity',      emoji: '🌍',  category: 'Science' },
  magnetism:    { id: 'magnetism',    name: 'Magnetism',    emoji: '🧲',  category: 'Science' },
  chemistry:    { id: 'chemistry',    name: 'Chemistry',    emoji: '⚗️',  category: 'Science' },
  biology:      { id: 'biology',      name: 'Biology',      emoji: '🦠',  category: 'Science' },
  physics:      { id: 'physics',      name: 'Physics',      emoji: '⚛️',  category: 'Science' },
  math:         { id: 'math',         name: 'Math',         emoji: '🔢',  category: 'Science' },
  virus:        { id: 'virus',        name: 'Virus',        emoji: '🦠',  category: 'Science' },
  bacteria:     { id: 'bacteria',     name: 'Bacteria',     emoji: '🦠',  category: 'Science' },
  cell:         { id: 'cell',         name: 'Cell',         emoji: '🔬',  category: 'Science' },
  gene:         { id: 'gene',         name: 'Gene',         emoji: '🧬',  category: 'Science' },
  vaccine:      { id: 'vaccine',      name: 'Vaccine',      emoji: '💉',  category: 'Science' },

  // ── ABSTRACT / PHILOSOPHY ──────────────────────────────────────────
  sound:        { id: 'sound',        name: 'Sound',        emoji: '🔊',  category: 'Abstract' },
  music:        { id: 'music',        name: 'Music',        emoji: '🎵',  category: 'Abstract' },
  art:          { id: 'art',          name: 'Art',          emoji: '🎨',  category: 'Abstract' },
  love:         { id: 'love',         name: 'Love',         emoji: '❤️',  category: 'Emotions' },
  fear:         { id: 'fear',         name: 'Fear',         emoji: '😱',  category: 'Emotions' },
  chaos:        { id: 'chaos',        name: 'Chaos',        emoji: '🌪️', category: 'Abstract' },
  order:        { id: 'order',        name: 'Order',        emoji: '⚖️',  category: 'Abstract' },
  balance:      { id: 'balance',      name: 'Balance',      emoji: '⚖️',  category: 'Abstract' },
  death:        { id: 'death',        name: 'Death',        emoji: '💀',  category: 'Abstract' },
  soul:         { id: 'soul',         name: 'Soul',         emoji: '👻',  category: 'Abstract' },
  mind:         { id: 'mind',         name: 'Mind',         emoji: '🧠',  category: 'Abstract' },
  dream:        { id: 'dream',        name: 'Dream',        emoji: '💭',  category: 'Abstract' },
  time:         { id: 'time',         name: 'Time',         emoji: '⏰',  category: 'Abstract' },
  void:         { id: 'void',         name: 'Void',         emoji: '🕳️', category: 'Abstract' },
  infinity:     { id: 'infinity',     name: 'Infinity',     emoji: '♾️',  category: 'Abstract' },
  wisdom:       { id: 'wisdom',       name: 'Wisdom',       emoji: '🦉',  category: 'Emotions' },
  madness:      { id: 'madness',      name: 'Madness',      emoji: '🌀',  category: 'Emotions' },
  hope:         { id: 'hope',         name: 'Hope',         emoji: '🌅',  category: 'Emotions' },
  despair:      { id: 'despair',      name: 'Despair',      emoji: '😔',  category: 'Emotions' },
  memory:       { id: 'memory',       name: 'Memory',       emoji: '💭',  category: 'Abstract' },
  thought:      { id: 'thought',      name: 'Thought',      emoji: '💭',  category: 'Abstract' },
  emotion:      { id: 'emotion',      name: 'Emotion',      emoji: '❤️',  category: 'Emotions' },
  consciousness:{ id: 'consciousness',name: 'Consciousness', emoji: '🧠',  category: 'Abstract' },

  // ── LEGACY + ADDITIONAL ─────────────────────────────────────────────
  inferno:      { id: 'inferno',      name: 'Inferno',      emoji: '💥🔥', category: 'Nature' },
  blaze:        { id: 'blaze',        name: 'Blaze',        emoji: '🔥',  category: 'Nature' },
  wildfire:     { id: 'wildfire',     name: 'Wildfire',     emoji: '🔥🌲', category: 'Nature' },
  geothermal:   { id: 'geothermal',   name: 'Geothermal',   emoji: '♨️',  category: 'Energy' },
  bioluminescense:{ id: 'bioluminescense', name: 'Bioluminescence', emoji: '💧✨', category: 'Nature' },
  lavaOcean:    { id: 'lavaOcean',    name: 'Lava Ocean',   emoji: '🌋🌊', category: 'Nature' },
  dystopia:     { id: 'dystopia',     name: 'Dystopia',     emoji: '🌆',  category: 'Abstract' },
  terraCotta:   { id: 'terraCotta',   name: 'Terra Cotta',  emoji: '🏺',  category: 'Objects' },
  pearl:        { id: 'pearl',        name: 'Pearl',        emoji: '🫧',  category: 'Nature' },
  locust:       { id: 'locust',       name: 'Locust',       emoji: '🦗',  category: 'Animals' },
  goat:         { id: 'goat',         name: 'Goat',         emoji: '🐐',  category: 'Animals' },
  mutation:     { id: 'mutation',     name: 'Mutation',     emoji: '🧬',  category: 'Science' },
  warrior:      { id: 'warrior',      name: 'Warrior',      emoji: '⚔️',  category: 'Civilization' },

  // ── MISSING BASIC ELEMENTS (referenced in existing recipes) ──────────
  night:        { id: 'night',        name: 'Night',        emoji: '🌙',  category: 'Nature' },
  day:          { id: 'day',          name: 'Day',          emoji: '☀️',  category: 'Nature' },
  cold:         { id: 'cold',         name: 'Cold',         emoji: '🥶',  category: 'Weather' },
  heat:         { id: 'heat',         name: 'Heat',         emoji: '🌡️', category: 'Weather' },
  wind:         { id: 'wind',         name: 'Wind',         emoji: '💨',  category: 'Nature' },
  space:        { id: 'space',        name: 'Space',        emoji: '🌌',  category: 'Space' },
  gas:          { id: 'gas',          name: 'Gas',          emoji: '💨',  category: 'Science' },
  mass:         { id: 'mass',         name: 'Mass',         emoji: '⚖️',  category: 'Science' },
  wax:          { id: 'wax',          name: 'Wax',          emoji: '🕯️', category: 'Nature' },
  resin:        { id: 'resin',        name: 'Resin',        emoji: '🌲',  category: 'Nature' },
  fiber:        { id: 'fiber',        name: 'Fiber',        emoji: '🌿',  category: 'Nature' },

  // ── MATERIALS ────────────────────────────────────────────────────────
  rubber:       { id: 'rubber',       name: 'Rubber',       emoji: '⚫',  category: 'Nature' },
  wool:         { id: 'wool',         name: 'Wool',         emoji: '🧶',  category: 'Nature' },
  silk:         { id: 'silk',         name: 'Silk',         emoji: '🧵',  category: 'Objects' },
  leather:      { id: 'leather',      name: 'Leather',      emoji: '🟫',  category: 'Objects' },
  cloth:        { id: 'cloth',        name: 'Cloth',        emoji: '🧣',  category: 'Objects' },
  brick:        { id: 'brick',        name: 'Brick',        emoji: '🧱',  category: 'Objects' },
  cement:       { id: 'cement',       name: 'Cement',       emoji: '🏗️', category: 'Objects' },
  concrete:     { id: 'concrete',     name: 'Concrete',     emoji: '🏗️', category: 'Technology' },
  plastic:      { id: 'plastic',      name: 'Plastic',      emoji: '♻️',  category: 'Technology' },
  ink:          { id: 'ink',          name: 'Ink',          emoji: '✒️',  category: 'Objects' },
  dye:          { id: 'dye',          name: 'Dye',          emoji: '🎨',  category: 'Objects' },
  paint:        { id: 'paint',        name: 'Paint',        emoji: '🖌️', category: 'Objects' },
  color:        { id: 'color',        name: 'Color',        emoji: '🌈',  category: 'Abstract' },
  glue:         { id: 'glue',         name: 'Glue',         emoji: '🪣',  category: 'Objects' },
  soap:         { id: 'soap',         name: 'Soap',         emoji: '🧼',  category: 'Objects' },
  bubble:       { id: 'bubble',       name: 'Bubble',       emoji: '🫧',  category: 'Science' },

  // ── HUMAN ROLES ──────────────────────────────────────────────────────
  child:        { id: 'child',        name: 'Child',        emoji: '👶',  category: 'Civilization' },
  elder:        { id: 'elder',        name: 'Elder',        emoji: '👴',  category: 'Civilization' },
  doctor:       { id: 'doctor',       name: 'Doctor',       emoji: '🩺',  category: 'Civilization' },
  fisherman:    { id: 'fisherman',    name: 'Fisherman',    emoji: '🎣',  category: 'Civilization' },
  merchant:     { id: 'merchant',     name: 'Merchant',     emoji: '💼',  category: 'Civilization' },
  king:         { id: 'king',         name: 'King',         emoji: '👑',  category: 'Civilization' },
  knight:       { id: 'knight',       name: 'Knight',       emoji: '⚔️',  category: 'Civilization' },
  pirate:       { id: 'pirate',       name: 'Pirate',       emoji: '🏴‍☠️', category: 'Civilization' },
  sailor:       { id: 'sailor',       name: 'Sailor',       emoji: '⚓',  category: 'Civilization' },
  farmer:       { id: 'farmer',       name: 'Farmer',       emoji: '🌾',  category: 'Civilization' },
  hunter:       { id: 'hunter',       name: 'Hunter',       emoji: '🏹',  category: 'Civilization' },
  explorer:     { id: 'explorer',     name: 'Explorer',     emoji: '🧭',  category: 'Civilization' },
  scholar:      { id: 'scholar',      name: 'Scholar',      emoji: '📖',  category: 'Civilization' },
  engineer:     { id: 'engineer',     name: 'Engineer',     emoji: '⚙️',  category: 'Technology' },
  chef:         { id: 'chef',         name: 'Chef',         emoji: '👨‍🍳', category: 'Civilization' },
  priest:       { id: 'priest',       name: 'Priest',       emoji: '⛪',  category: 'Civilization' },
  shaman:       { id: 'shaman',       name: 'Shaman',       emoji: '🔮',  category: 'Fantasy' },
  alchemist:    { id: 'alchemist',    name: 'Alchemist',    emoji: '⚗️',  category: 'Fantasy' },
  gladiator:    { id: 'gladiator',    name: 'Gladiator',    emoji: '⚔️',  category: 'Civilization' },
  monk:         { id: 'monk',         name: 'Monk',         emoji: '🧘',  category: 'Civilization' },
  spy:          { id: 'spy',          name: 'Spy',          emoji: '🕵️', category: 'Civilization' },
  pilot:        { id: 'pilot',        name: 'Pilot',        emoji: '✈️',  category: 'Technology' },

  // ── CIVILIZATION STRUCTURES ──────────────────────────────────────────
  palace:       { id: 'palace',       name: 'Palace',       emoji: '🏯',  category: 'Civilization' },
  cathedral:    { id: 'cathedral',    name: 'Cathedral',    emoji: '⛪',  category: 'Civilization' },
  tavern:       { id: 'tavern',       name: 'Tavern',       emoji: '🍺',  category: 'Civilization' },
  port:         { id: 'port',         name: 'Port',         emoji: '⚓',  category: 'Civilization' },
  wall:         { id: 'wall',         name: 'Wall',         emoji: '🧱',  category: 'Civilization' },
  camp:         { id: 'camp',         name: 'Camp',         emoji: '⛺',  category: 'Civilization' },
  road:         { id: 'road',         name: 'Road',         emoji: '🛣️', category: 'Civilization' },
  university:   { id: 'university',   name: 'University',   emoji: '🎓',  category: 'Civilization' },
  theater:      { id: 'theater',      name: 'Theater',      emoji: '🎭',  category: 'Civilization' },
  parliament:   { id: 'parliament',   name: 'Parliament',   emoji: '🏛️', category: 'Civilization' },
  guild:        { id: 'guild',        name: 'Guild',        emoji: '🏛️', category: 'Civilization' },
  dungeon:      { id: 'dungeon',      name: 'Dungeon',      emoji: '🕳️', category: 'Fantasy' },
  graveyard:    { id: 'graveyard',    name: 'Graveyard',    emoji: '🪦',  category: 'Fantasy' },
  tower:        { id: 'tower',        name: 'Tower',        emoji: '🗼',  category: 'Civilization' },

  // ── FOOD / INGREDIENTS ───────────────────────────────────────────────
  grape:        { id: 'grape',        name: 'Grape',        emoji: '🍇',  category: 'Food' },
  apple:        { id: 'apple',        name: 'Apple',        emoji: '🍎',  category: 'Food' },
  orange:       { id: 'orange',       name: 'Orange',       emoji: '🍊',  category: 'Food' },
  lemon:        { id: 'lemon',        name: 'Lemon',        emoji: '🍋',  category: 'Food' },
  berry:        { id: 'berry',        name: 'Berry',        emoji: '🫐',  category: 'Food' },
  corn:         { id: 'corn',         name: 'Corn',         emoji: '🌽',  category: 'Food' },
  potato:       { id: 'potato',       name: 'Potato',       emoji: '🥔',  category: 'Food' },
  bean:         { id: 'bean',         name: 'Bean',         emoji: '🫘',  category: 'Food' },
  olive:        { id: 'olive',        name: 'Olive',        emoji: '🫒',  category: 'Food' },
  cacao:        { id: 'cacao',        name: 'Cacao',        emoji: '🍫',  category: 'Food' },
  cane:         { id: 'cane',         name: 'Cane',         emoji: '🎋',  category: 'Food' },
  egg:          { id: 'egg',          name: 'Egg',          emoji: '🥚',  category: 'Food' },
  nut:          { id: 'nut',          name: 'Nut',          emoji: '🥜',  category: 'Food' },
  iceCream:     { id: 'iceCream',     name: 'Ice Cream',    emoji: '🍦',  category: 'Food' },
  cake:         { id: 'cake',         name: 'Cake',         emoji: '🎂',  category: 'Food' },
  cookie:       { id: 'cookie',       name: 'Cookie',       emoji: '🍪',  category: 'Food' },
  pizza:        { id: 'pizza',        name: 'Pizza',        emoji: '🍕',  category: 'Food' },
  noodle:       { id: 'noodle',       name: 'Noodle',       emoji: '🍜',  category: 'Food' },
  salad:        { id: 'salad',        name: 'Salad',        emoji: '🥗',  category: 'Food' },
  stew:         { id: 'stew',         name: 'Stew',         emoji: '🍲',  category: 'Food' },
  juice:        { id: 'juice',        name: 'Juice',        emoji: '🧃',  category: 'Food' },
  cider:        { id: 'cider',        name: 'Cider',        emoji: '🍺',  category: 'Food' },
  whiskey:      { id: 'whiskey',      name: 'Whiskey',      emoji: '🥃',  category: 'Food' },
  rum:          { id: 'rum',          name: 'Rum',          emoji: '🍾',  category: 'Food' },
  vinegar:      { id: 'vinegar',      name: 'Vinegar',      emoji: '🫙',  category: 'Food' },
  jam:          { id: 'jam',          name: 'Jam',          emoji: '🍓',  category: 'Food' },
  yogurt:       { id: 'yogurt',       name: 'Yogurt',       emoji: '🥛',  category: 'Food' },
  pasta:        { id: 'pasta',        name: 'Pasta',        emoji: '🍝',  category: 'Food' },

  // ── EMOTIONS / ABSTRACT ──────────────────────────────────────────────
  peace:        { id: 'peace',        name: 'Peace',        emoji: '🕊️', category: 'Abstract' },
  freedom:      { id: 'freedom',      name: 'Freedom',      emoji: '🗽',  category: 'Abstract' },
  power:        { id: 'power',        name: 'Power',        emoji: '⚡',  category: 'Abstract' },
  justice:      { id: 'justice',      name: 'Justice',      emoji: '⚖️',  category: 'Abstract' },
  truth:        { id: 'truth',        name: 'Truth',        emoji: '💡',  category: 'Abstract' },
  fate:         { id: 'fate',         name: 'Fate',         emoji: '🎲',  category: 'Abstract' },
  luck:         { id: 'luck',         name: 'Luck',         emoji: '🍀',  category: 'Abstract' },
  joy:          { id: 'joy',          name: 'Joy',          emoji: '😊',  category: 'Emotions' },
  anger:        { id: 'anger',        name: 'Anger',        emoji: '😠',  category: 'Emotions' },
  pride:        { id: 'pride',        name: 'Pride',        emoji: '🦁',  category: 'Emotions' },
  greed:        { id: 'greed',        name: 'Greed',        emoji: '💰',  category: 'Emotions' },
  courage:      { id: 'courage',      name: 'Courage',      emoji: '🦁',  category: 'Emotions' },
  glory:        { id: 'glory',        name: 'Glory',        emoji: '🌟',  category: 'Abstract' },
  honor:        { id: 'honor',        name: 'Honor',        emoji: '🏅',  category: 'Abstract' },
  beauty:       { id: 'beauty',       name: 'Beauty',       emoji: '✨',  category: 'Abstract' },

  // ── FANTASY (new) ────────────────────────────────────────────────────
  ritual:       { id: 'ritual',       name: 'Ritual',       emoji: '🕯️', category: 'Fantasy' },
  prophecy:     { id: 'prophecy',     name: 'Prophecy',     emoji: '📜',  category: 'Fantasy' },
  blessing:     { id: 'blessing',     name: 'Blessing',     emoji: '✨',  category: 'Fantasy' },
  artifact:     { id: 'artifact',     name: 'Artifact',     emoji: '🏺',  category: 'Fantasy' },
  quest:        { id: 'quest',        name: 'Quest',        emoji: '⚔️',  category: 'Fantasy' },
  treasure:     { id: 'treasure',     name: 'Treasure',     emoji: '💰',  category: 'Fantasy' },
  ghost:        { id: 'ghost',        name: 'Ghost',        emoji: '👻',  category: 'Fantasy' },
  skeleton:     { id: 'skeleton',     name: 'Skeleton',     emoji: '💀',  category: 'Fantasy' },
  spell:        { id: 'spell',        name: 'Spell',        emoji: '✨',  category: 'Fantasy' },
  enchantment:  { id: 'enchantment',  name: 'Enchantment',  emoji: '🔮',  category: 'Fantasy' },
  portal:       { id: 'portal',       name: 'Portal',       emoji: '🌀',  category: 'Fantasy' },
  labyrinth:    { id: 'labyrinth',    name: 'Labyrinth',    emoji: '🌀',  category: 'Fantasy' },

  // ── SCIENCE (new) ────────────────────────────────────────────────────
  pressure:     { id: 'pressure',     name: 'Pressure',     emoji: '💢',  category: 'Science' },
  catalyst:     { id: 'catalyst',     name: 'Catalyst',     emoji: '⚗️',  category: 'Science' },
  fossil:       { id: 'fossil',       name: 'Fossil',       emoji: '🦕',  category: 'Science' },
  experiment:   { id: 'experiment',   name: 'Experiment',   emoji: '🔬',  category: 'Science' },
  theory:       { id: 'theory',       name: 'Theory',       emoji: '📖',  category: 'Science' },
  discovery:    { id: 'discovery',    name: 'Discovery',    emoji: '💡',  category: 'Science' },
  invention:    { id: 'invention',    name: 'Invention',    emoji: '💡',  category: 'Technology' },

  // ── ANIMALS (new) ────────────────────────────────────────────────────
  zebra:        { id: 'zebra',        name: 'Zebra',        emoji: '🦓',  category: 'Animals' },
  giraffe:      { id: 'giraffe',      name: 'Giraffe',      emoji: '🦒',  category: 'Animals' },
  camel:        { id: 'camel',        name: 'Camel',        emoji: '🐫',  category: 'Animals' },
  kangaroo:     { id: 'kangaroo',     name: 'Kangaroo',     emoji: '🦘',  category: 'Animals' },
  koala:        { id: 'koala',        name: 'Koala',        emoji: '🐨',  category: 'Animals' },
  panda:        { id: 'panda',        name: 'Panda',        emoji: '🐼',  category: 'Animals' },
  monkey:       { id: 'monkey',       name: 'Monkey',       emoji: '🐒',  category: 'Animals' },
  parrot:       { id: 'parrot',       name: 'Parrot',       emoji: '🦜',  category: 'Animals' },
  flamingo:     { id: 'flamingo',     name: 'Flamingo',     emoji: '🦩',  category: 'Animals' },
  swan:         { id: 'swan',         name: 'Swan',         emoji: '🦢',  category: 'Animals' },
  duck:         { id: 'duck',         name: 'Duck',         emoji: '🦆',  category: 'Animals' },
  chicken:      { id: 'chicken',      name: 'Chicken',      emoji: '🐔',  category: 'Animals' },
  rat:          { id: 'rat',          name: 'Rat',          emoji: '🐀',  category: 'Animals' },
  mouse:        { id: 'mouse',        name: 'Mouse',        emoji: '🐭',  category: 'Animals' },
  hedgehog:     { id: 'hedgehog',     name: 'Hedgehog',     emoji: '🦔',  category: 'Animals' },
  beaver:       { id: 'beaver',       name: 'Beaver',       emoji: '🦫',  category: 'Animals' },
  otter:        { id: 'otter',        name: 'Otter',        emoji: '🦦',  category: 'Animals' },
  raccoon:      { id: 'raccoon',      name: 'Raccoon',      emoji: '🦝',  category: 'Animals' },
  moose:        { id: 'moose',        name: 'Moose',        emoji: '🦌',  category: 'Animals' },
  bison:        { id: 'bison',        name: 'Bison',        emoji: '🦬',  category: 'Animals' },
  rhino:        { id: 'rhino',        name: 'Rhino',        emoji: '🦏',  category: 'Animals' },
  hippo:        { id: 'hippo',        name: 'Hippo',        emoji: '🦛',  category: 'Animals' },
  llama:        { id: 'llama',        name: 'Llama',        emoji: '🦙',  category: 'Animals' },
  peacock:      { id: 'peacock',      name: 'Peacock',      emoji: '🦚',  category: 'Animals' },
  crow:         { id: 'crow',         name: 'Crow',         emoji: '🐦‍⬛', category: 'Animals' },
  seahorse:     { id: 'seahorse',     name: 'Seahorse',     emoji: '🐠',  category: 'Animals' },
  narwhal:      { id: 'narwhal',      name: 'Narwhal',      emoji: '🐋',  category: 'Animals' },
  walrus:       { id: 'walrus',       name: 'Walrus',       emoji: '🦭',  category: 'Animals' },
  orca:         { id: 'orca',         name: 'Orca',         emoji: '🐋',  category: 'Animals' },
  axolotl:      { id: 'axolotl',      name: 'Axolotl',      emoji: '🦎',  category: 'Animals' },
  chameleon:    { id: 'chameleon',    name: 'Chameleon',    emoji: '🦎',  category: 'Animals' },
  iguana:       { id: 'iguana',       name: 'Iguana',       emoji: '🦎',  category: 'Animals' },
  capybara:     { id: 'capybara',     name: 'Capybara',     emoji: '🐿️', category: 'Animals' },
  sloth:        { id: 'sloth',        name: 'Sloth',        emoji: '🦥',  category: 'Animals' },
  toucan:       { id: 'toucan',       name: 'Toucan',       emoji: '🦜',  category: 'Animals' },
  stork:        { id: 'stork',        name: 'Stork',        emoji: '🦢',  category: 'Animals' },
  vulture:      { id: 'vulture',      name: 'Vulture',      emoji: '🦅',  category: 'Animals' },

  // ── MISSING RESULT CONCEPTS ──────────────────────────────────────────
  autumn:       { id: 'autumn',       name: 'Autumn',       emoji: '🍂',  category: 'Nature' },
  bakery:       { id: 'bakery',       name: 'Bakery',       emoji: '🥖',  category: 'Civilization' },
  corruption:   { id: 'corruption',   name: 'Corruption',   emoji: '💀',  category: 'Abstract' },
  dam:          { id: 'dam',          name: 'Dam',          emoji: '🏗️', category: 'Civilization' },
  dance:        { id: 'dance',        name: 'Dance',        emoji: '💃',  category: 'Abstract' },
  defense:      { id: 'defense',      name: 'Defense',      emoji: '🛡️', category: 'Civilization' },
  enlightenment:{ id: 'enlightenment',name: 'Enlightenment',emoji: '💡',  category: 'Abstract' },
  famine:       { id: 'famine',       name: 'Famine',       emoji: '💀',  category: 'Abstract' },
  flavor:       { id: 'flavor',       name: 'Flavor',       emoji: '🌶️', category: 'Food' },
  foam:         { id: 'foam',         name: 'Foam',         emoji: '🫧',  category: 'Science' },
  food:         { id: 'food',         name: 'Food',         emoji: '🍽️', category: 'Food' },
  fur:          { id: 'fur',          name: 'Fur',          emoji: '🟫',  category: 'Nature' },
  harvest:      { id: 'harvest',      name: 'Harvest',      emoji: '🌾',  category: 'Civilization' },
  haunting:     { id: 'haunting',     name: 'Haunting',     emoji: '👻',  category: 'Fantasy' },
  healing:      { id: 'healing',      name: 'Healing',      emoji: '💚',  category: 'Fantasy' },
  hero:         { id: 'hero',         name: 'Hero',         emoji: '🦸',  category: 'Fantasy' },
  history:      { id: 'history',      name: 'History',      emoji: '📜',  category: 'Civilization' },
  incense:      { id: 'incense',      name: 'Incense',      emoji: '🪔',  category: 'Fantasy' },
  jewelry:      { id: 'jewelry',      name: 'Jewelry',      emoji: '💎',  category: 'Objects' },
  kiln:         { id: 'kiln',         name: 'Kiln',         emoji: '🔥',  category: 'Objects' },
  laughter:     { id: 'laughter',     name: 'Laughter',     emoji: '😂',  category: 'Emotions' },
  law:          { id: 'law',          name: 'Law',          emoji: '⚖️',  category: 'Civilization' },
  monastery:    { id: 'monastery',    name: 'Monastery',    emoji: '⛪',  category: 'Civilization' },
  meditation:   { id: 'meditation',   name: 'Meditation',   emoji: '🧘',  category: 'Abstract' },
  omen:         { id: 'omen',         name: 'Omen',         emoji: '🌑',  category: 'Fantasy' },
  painting:     { id: 'painting',     name: 'Painting',     emoji: '🖼️', category: 'Abstract' },
  pest:         { id: 'pest',         name: 'Pest',         emoji: '🦗',  category: 'Animals' },
  philosophy:   { id: 'philosophy',   name: 'Philosophy',   emoji: '🧠',  category: 'Abstract' },
  plague:       { id: 'plague',       name: 'Plague',       emoji: '☣️',  category: 'Science' },
  popcorn:      { id: 'popcorn',      name: 'Popcorn',      emoji: '🍿',  category: 'Food' },
  pottery:      { id: 'pottery',      name: 'Pottery',      emoji: '🏺',  category: 'Objects' },
  pudding:      { id: 'pudding',      name: 'Pudding',      emoji: '🍮',  category: 'Food' },
  reaction:     { id: 'reaction',     name: 'Reaction',     emoji: '⚗️',  category: 'Science' },
  ruin:         { id: 'ruin',         name: 'Ruin',         emoji: '🏚️', category: 'Civilization' },
  safari:       { id: 'safari',       name: 'Safari',       emoji: '🦁',  category: 'Nature' },
  sail:         { id: 'sail',         name: 'Sail',         emoji: '⛵',  category: 'Objects' },
  savanna:      { id: 'savanna',      name: 'Savanna',      emoji: '🌾',  category: 'Nature' },
  scent:        { id: 'scent',        name: 'Scent',        emoji: '🌸',  category: 'Abstract' },
  shipwreck:    { id: 'shipwreck',    name: 'Shipwreck',    emoji: '⛵',  category: 'Objects' },
  song:         { id: 'song',         name: 'Song',         emoji: '🎵',  category: 'Abstract' },
  tapestry:     { id: 'tapestry',     name: 'Tapestry',     emoji: '🖼️', category: 'Objects' },
  totem:        { id: 'totem',        name: 'Totem',        emoji: '🗿',  category: 'Fantasy' },
  undead:       { id: 'undead',       name: 'Undead',       emoji: '💀',  category: 'Fantasy' },
  vitamin:      { id: 'vitamin',      name: 'Vitamin',      emoji: '💊',  category: 'Science' },
  warmth:       { id: 'warmth',       name: 'Warmth',       emoji: '🌡️', category: 'Abstract' },
  wealth:       { id: 'wealth',       name: 'Wealth',       emoji: '💰',  category: 'Abstract' },
  zoo:          { id: 'zoo',          name: 'Zoo',          emoji: '🦁',  category: 'Civilization' },
};

export const getConcept = (id) => CONCEPTS[id] || null;
