export const pairKey = (aId, bId) => [aId, bId].sort().join(':');

export const RECIPES = {

  // ════════════════════════════════════════════════════════
  // STARTING ELEMENTS — original core
  // ════════════════════════════════════════════════════════
  [pairKey('fire', 'water')]: 'steam',
  [pairKey('water', 'earth')]: 'mud',
  [pairKey('air', 'water')]: 'cloud',
  [pairKey('air', 'earth')]: 'atmosphere',
  [pairKey('air', 'fire')]: 'smoke',
  [pairKey('earth', 'fire')]: 'volcano',
  [pairKey('water', 'water')]: 'ocean',
  [pairKey('air', 'air')]: 'oxygen',
  [pairKey('fire', 'fire')]: 'inferno',
  [pairKey('earth', 'earth')]: 'mountain',

  // ════════════════════════════════════════════════════════
  // TIER 2 — secondary elemental chains
  // ════════════════════════════════════════════════════════
  [pairKey('atmosphere', 'fire')]: 'plasma',
  [pairKey('smoke', 'earth')]: 'smog',
  [pairKey('mud', 'atmosphere')]: 'smog',
  [pairKey('mud', 'air')]: 'dust',
  [pairKey('cloud', 'earth')]: 'atmosphere',
  [pairKey('ocean', 'air')]: 'atmosphere',
  [pairKey('smoke', 'atmosphere')]: 'smog',
  [pairKey('inferno', 'earth')]: 'volcano',
  [pairKey('atmosphere', 'sea')]: 'ocean',
  [pairKey('atmosphere', 'air')]: 'sky',
  [pairKey('steam', 'fire')]: 'dragon',
  [pairKey('oxygen', 'ocean')]: 'sea',
  [pairKey('ocean', 'water')]: 'sea',
  [pairKey('steam', 'air')]: 'vapor',
  [pairKey('mud', 'earth')]: 'clay',
  [pairKey('mud', 'fire')]: 'lava',
  [pairKey('ocean', 'fire')]: 'lava',
  [pairKey('fire', 'volcano')]: 'lava',
  [pairKey('atmosphere', 'water')]: 'humidity',
  [pairKey('humidity', 'plasma')]: 'steam',
  [pairKey('sky', 'fire')]: 'sun',
  [pairKey('fire', 'plasma')]: 'sun',
  [pairKey('air', 'inferno')]: 'wildfire',
  [pairKey('air', 'volcano')]: 'ashCloud',
  [pairKey('lava', 'air')]: 'magma',
  [pairKey('lava', 'plasma')]: 'magma',
  [pairKey('steam', 'vapor')]: 'mist',
  [pairKey('smoke', 'lava')]: 'volcano',
  [pairKey('ocean', 'plasma')]: 'bioluminescense',
  [pairKey('oxygen', 'plasma')]: 'fire',
  [pairKey('earth', 'smog')]: 'dystopia',
  [pairKey('fire', 'mountain')]: 'volcano',
  [pairKey('clay', 'humidity')]: 'mud',
  [pairKey('sea', 'inferno')]: 'lavaOcean',
  [pairKey('humidity', 'mountain')]: 'cloud',
  [pairKey('cloud', 'clay')]: 'cumulus',
  [pairKey('dust', 'air')]: 'pollution',
  [pairKey('atmosphere', 'volcano')]: 'eruption',
  [pairKey('oxygen', 'steam')]: 'waterVapor',
  [pairKey('atmosphere', 'clay')]: 'terraCotta',
  [pairKey('fire', 'inferno')]: 'blaze',
  [pairKey('steam', 'earth')]: 'geothermal',

  // ════════════════════════════════════════════════════════
  // WEATHER
  // ════════════════════════════════════════════════════════
  [pairKey('cloud', 'water')]: 'rain',
  [pairKey('cloud', 'ocean')]: 'rain',
  [pairKey('cloud', 'mist')]: 'rain',
  [pairKey('mountain', 'water')]: 'ice',
  [pairKey('water', 'cold')]: 'ice',
  [pairKey('cloud', 'ice')]: 'snow',
  [pairKey('atmosphere', 'ice')]: 'snow',
  [pairKey('cloud', 'cloud')]: 'storm',
  [pairKey('air', 'rain')]: 'storm',
  [pairKey('lightning', 'rain')]: 'storm',
  [pairKey('lightning', 'thunder')]: 'storm',
  [pairKey('cloud', 'fire')]: 'lightning',
  [pairKey('cloud', 'plasma')]: 'lightning',
  [pairKey('air', 'lightning')]: 'thunder',
  [pairKey('air', 'storm')]: 'tornado',
  [pairKey('storm', 'storm')]: 'hurricane',
  [pairKey('ocean', 'storm')]: 'typhoon',
  [pairKey('hurricane', 'water')]: 'typhoon',
  [pairKey('air', 'ice')]: 'frost',
  [pairKey('earth', 'ice')]: 'tundra',
  [pairKey('snow', 'storm')]: 'blizzard',
  [pairKey('ice', 'storm')]: 'hail',
  [pairKey('rain', 'sun')]: 'rainbow',
  [pairKey('mist', 'sun')]: 'rainbow',
  [pairKey('earth', 'mist')]: 'fog',
  [pairKey('earth', 'vapor')]: 'fog',
  [pairKey('atmosphere', 'plasma')]: 'aurora',
  [pairKey('ocean', 'rain')]: 'monsoon',
  [pairKey('cloud', 'monsoon')]: 'monsoon',
  [pairKey('fire', 'ice')]: 'water',
  [pairKey('ice', 'sun')]: 'water',
  [pairKey('fire', 'snow')]: 'water',
  [pairKey('snow', 'sun')]: 'water',
  [pairKey('sand', 'storm')]: 'sandstorm',
  [pairKey('desert', 'storm')]: 'sandstorm',
  [pairKey('desert', 'air')]: 'sandstorm',
  [pairKey('sun', 'desert')]: 'drought',
  [pairKey('sun', 'sand')]: 'drought',
  [pairKey('sun', 'earth')]: 'heatwave',
  [pairKey('fire', 'drought')]: 'heatwave',
  [pairKey('rain', 'river')]: 'flood',
  [pairKey('glacier', 'sun')]: 'flood',
  [pairKey('storm', 'water')]: 'flood',
  [pairKey('grass', 'water')]: 'dew',
  [pairKey('flower', 'rain')]: 'dew',
  [pairKey('fog', 'sun')]: 'dew',
  [pairKey('humidity', 'cloud')]: 'cumulus',

  // ════════════════════════════════════════════════════════
  // GEOLOGY / MATERIALS
  // ════════════════════════════════════════════════════════
  [pairKey('earth', 'lava')]: 'rock',
  [pairKey('magma', 'earth')]: 'rock',
  [pairKey('lava', 'water')]: 'obsidian',
  [pairKey('magma', 'ocean')]: 'obsidian',
  [pairKey('rock', 'mountain')]: 'stone',
  [pairKey('stone', 'ocean')]: 'sand',
  [pairKey('rock', 'wave')]: 'sand',
  [pairKey('rock', 'river')]: 'sand',
  [pairKey('fire', 'sand')]: 'glass',
  [pairKey('lava', 'sand')]: 'glass',
  [pairKey('earth', 'blaze')]: 'coal',
  [pairKey('mud', 'inferno')]: 'coal',
  [pairKey('plant', 'earth')]: 'coal',
  [pairKey('wood', 'earth')]: 'coal',
  [pairKey('rock', 'fire')]: 'mineral',
  [pairKey('fire', 'mineral')]: 'metal',
  [pairKey('inferno', 'rock')]: 'metal',
  [pairKey('earth', 'metal')]: 'iron',
  [pairKey('metal', 'rock')]: 'iron',
  [pairKey('metal', 'water')]: 'copper',
  [pairKey('metal', 'sun')]: 'gold',
  [pairKey('iron', 'sun')]: 'gold',
  [pairKey('metal', 'moon')]: 'silver',
  [pairKey('iron', 'moon')]: 'silver',
  [pairKey('coal', 'iron')]: 'steel',
  [pairKey('iron', 'iron')]: 'steel',
  [pairKey('iron', 'rain')]: 'rust',
  [pairKey('steel', 'rain')]: 'rust',
  [pairKey('iron', 'water')]: 'rust',
  [pairKey('mineral', 'water')]: 'crystal',
  [pairKey('glass', 'earth')]: 'crystal',
  [pairKey('glass', 'glass')]: 'crystal',
  [pairKey('crystal', 'fire')]: 'gem',
  [pairKey('cave', 'crystal')]: 'gem',
  [pairKey('gem', 'inferno')]: 'diamond',
  [pairKey('crystal', 'volcano')]: 'diamond',
  [pairKey('copper', 'iron')]: 'bronze',
  [pairKey('fire', 'stone')]: 'marble',
  [pairKey('rock', 'rock')]: 'cave',
  [pairKey('earth', 'rock')]: 'soil',
  [pairKey('clay', 'earth')]: 'soil',
  [pairKey('cave', 'water')]: 'stalactite',
  [pairKey('mineral', 'cave')]: 'stalactite',
  [pairKey('rock', 'ocean')]: 'salt',
  [pairKey('ocean', 'sun')]: 'salt',
  [pairKey('fire', 'sea')]: 'salt',
  [pairKey('smoke', 'fire')]: 'ash',
  [pairKey('wood', 'fire')]: 'ash',
  [pairKey('wildfire', 'forest')]: 'ashCloud',
  [pairKey('volcano', 'forest')]: 'ashCloud',
  [pairKey('earth', 'swamp')]: 'peat',
  [pairKey('plant', 'swamp')]: 'peat',
  [pairKey('tree', 'swamp')]: 'peat',
  [pairKey('resin', 'time')]: 'amber',
  [pairKey('insect', 'resin')]: 'amber',
  [pairKey('sand', 'water')]: 'quicksand',
  [pairKey('oil', 'earth')]: 'tar',
  [pairKey('rock', 'heat')]: 'chalk',
  [pairKey('mineral', 'water')]: 'quartz',
  [pairKey('crystal', 'earth')]: 'quartz',
  [pairKey('ice', 'earth')]: 'permafrost',
  [pairKey('glacier', 'earth')]: 'permafrost',
  [pairKey('rock', 'flint')]: 'fire',
  [pairKey('flint', 'flint')]: 'fire',

  // ════════════════════════════════════════════════════════
  // WATER FEATURES
  // ════════════════════════════════════════════════════════
  [pairKey('mountain', 'rain')]: 'river',
  [pairKey('glacier', 'sun')]: 'river',
  [pairKey('ice', 'mountain')]: 'glacier',
  [pairKey('snow', 'mountain')]: 'glacier',
  [pairKey('storm', 'water')]: 'wave',
  [pairKey('wind', 'ocean')]: 'wave',
  [pairKey('mud', 'tree')]: 'swamp',
  [pairKey('water', 'forest')]: 'swamp',
  [pairKey('mountain', 'river')]: 'waterfall',
  [pairKey('cliff', 'river')]: 'waterfall',
  [pairKey('earth', 'rain')]: 'pond',
  [pairKey('grass', 'rain')]: 'pond',
  [pairKey('moon', 'ocean')]: 'tide',
  [pairKey('moon', 'sea')]: 'tide',
  [pairKey('ocean', 'river')]: 'delta',
  [pairKey('river', 'grass')]: 'marsh',
  [pairKey('grass', 'water')]: 'marsh',
  [pairKey('river', 'river')]: 'lake',
  [pairKey('pond', 'pond')]: 'lake',
  [pairKey('geothermal', 'water')]: 'geyser',
  [pairKey('volcano', 'water')]: 'geyser',
  [pairKey('hotSpring', 'water')]: 'geyser',
  [pairKey('storm', 'ocean')]: 'whirlpool',
  [pairKey('tornado', 'ocean')]: 'whirlpool',
  [pairKey('geothermal', 'earth')]: 'hotSpring',
  [pairKey('steam', 'rock')]: 'hotSpring',

  // ════════════════════════════════════════════════════════
  // LANDFORMS
  // ════════════════════════════════════════════════════════
  [pairKey('ocean', 'volcano')]: 'island',
  [pairKey('mountain', 'ocean')]: 'island',
  [pairKey('sand', 'sun')]: 'desert',
  [pairKey('earth', 'drought')]: 'desert',
  [pairKey('river', 'rock')]: 'canyon',
  [pairKey('water', 'stone')]: 'canyon',
  [pairKey('ocean', 'sand')]: 'beach',
  [pairKey('sea', 'sand')]: 'beach',
  [pairKey('desert', 'water')]: 'oasis',
  [pairKey('desert', 'plant')]: 'oasis',
  [pairKey('earth', 'grass')]: 'prairie',
  [pairKey('grass', 'prairie')]: 'prairie',
  [pairKey('mountain', 'stone')]: 'cliff',
  [pairKey('mountain', 'wave')]: 'cliff',
  [pairKey('mountain', 'mountain')]: 'plateau',
  [pairKey('earth', 'mountain')]: 'valley',
  [pairKey('river', 'mountain')]: 'valley',
  [pairKey('ice', 'desert')]: 'tundra',
  [pairKey('earth', 'tundra')]: 'permafrost',

  // ════════════════════════════════════════════════════════
  // LIFE ORIGIN
  // ════════════════════════════════════════════════════════
  [pairKey('lightning', 'ocean')]: 'life',
  [pairKey('lightning', 'sea')]: 'life',
  [pairKey('lightning', 'water')]: 'life',
  [pairKey('mud', 'lightning')]: 'life',
  [pairKey('ocean', 'sun')]: 'life',
  [pairKey('water', 'sun')]: 'life',

  // ════════════════════════════════════════════════════════
  // PLANTS / NATURE
  // ════════════════════════════════════════════════════════
  [pairKey('soil', 'sun')]: 'plant',
  [pairKey('soil', 'water')]: 'plant',
  [pairKey('earth', 'life')]: 'plant',
  [pairKey('plant', 'earth')]: 'grass',
  [pairKey('plant', 'sun')]: 'grass',
  [pairKey('grass', 'sun')]: 'flower',
  [pairKey('plant', 'rain')]: 'flower',
  [pairKey('plant', 'water')]: 'flower',
  [pairKey('seed', 'soil')]: 'tree',
  [pairKey('seed', 'earth')]: 'tree',
  [pairKey('plant', 'time')]: 'tree',
  [pairKey('rain', 'tree')]: 'forest',
  [pairKey('tree', 'tree')]: 'forest',
  [pairKey('forest', 'humidity')]: 'jungle',
  [pairKey('forest', 'rain')]: 'jungle',
  [pairKey('forest', 'heat')]: 'jungle',
  [pairKey('rock', 'tree')]: 'wood',
  [pairKey('axe', 'tree')]: 'wood',
  [pairKey('fire', 'wood')]: 'charcoal',
  [pairKey('wood', 'inferno')]: 'charcoal',
  [pairKey('air', 'tree')]: 'leaf',
  [pairKey('tree', 'wind')]: 'leaf',
  [pairKey('stone', 'water')]: 'moss',
  [pairKey('cave', 'water')]: 'moss',
  [pairKey('lake', 'sun')]: 'algae',
  [pairKey('water', 'plant')]: 'algae',
  [pairKey('algae', 'ocean')]: 'seaweed',
  [pairKey('algae', 'sea')]: 'seaweed',
  [pairKey('algae', 'kelp')]: 'kelp',
  [pairKey('soil', 'humidity')]: 'mushroom',
  [pairKey('wood', 'water')]: 'mushroom',
  [pairKey('spore', 'earth')]: 'mushroom',
  [pairKey('flower', 'tree')]: 'fruit',
  [pairKey('flower', 'sun')]: 'fruit',
  [pairKey('fruit', 'earth')]: 'seed',
  [pairKey('fruit', 'wind')]: 'seed',
  [pairKey('air', 'flower')]: 'pollen',
  [pairKey('bee', 'flower')]: 'pollen',
  [pairKey('plant', 'tree')]: 'vine',
  [pairKey('plant', 'rock')]: 'vine',
  [pairKey('plant', 'desert')]: 'cactus',
  [pairKey('cactus', 'sun')]: 'cactus',
  [pairKey('grass', 'humidity')]: 'bamboo',
  [pairKey('grass', 'jungle')]: 'bamboo',
  [pairKey('stone', 'sea')]: 'coral',
  [pairKey('life', 'ocean')]: 'coral',
  [pairKey('coral', 'ocean')]: 'reef',
  [pairKey('coral', 'rock')]: 'reef',
  [pairKey('mushroom', 'air')]: 'spore',
  [pairKey('mushroom', 'wind')]: 'spore',
  [pairKey('earth', 'grass')]: 'prairie',
  [pairKey('forest', 'fire')]: 'wildfire',
  [pairKey('plant', 'sun')]: 'grain',
  [pairKey('grass', 'farm')]: 'wheat',
  [pairKey('grain', 'sun')]: 'wheat',
  [pairKey('grain', 'water')]: 'rice',
  [pairKey('wheat', 'water')]: 'rice',
  [pairKey('plant', 'medicine')]: 'herb',
  [pairKey('mushroom', 'forest')]: 'herb',
  [pairKey('seaweed', 'ocean')]: 'kelp',
  [pairKey('plant', 'cold')]: 'fern',
  [pairKey('forest', 'water')]: 'fern',
  [pairKey('flower', 'love')]: 'rose',
  [pairKey('flower', 'magic')]: 'rose',
  [pairKey('vine', 'tree')]: 'ivy',
  [pairKey('vine', 'castle')]: 'ivy',
  [pairKey('tree', 'mountain')]: 'oak',
  [pairKey('tree', 'forest')]: 'pine',
  [pairKey('tree', 'snow')]: 'pine',
  [pairKey('plant', 'fiber')]: 'cotton',
  [pairKey('grass', 'warmth')]: 'cotton',
  [pairKey('plant', 'smoke')]: 'tobacco',
  [pairKey('leaf', 'fire')]: 'tobacco',
  [pairKey('flower', 'water')]: 'lily',
  [pairKey('pond', 'flower')]: 'lily',
  [pairKey('flower', 'sun')]: 'sunflower',
  [pairKey('flower', 'light')]: 'sunflower',
  [pairKey('forest', 'ocean')]: 'mangrove',
  [pairKey('tree', 'swamp')]: 'mangrove',

  // ════════════════════════════════════════════════════════
  // ANIMALS — aquatic
  // ════════════════════════════════════════════════════════
  [pairKey('life', 'water')]: 'fish',
  [pairKey('life', 'sea')]: 'fish',
  [pairKey('fish', 'river')]: 'salmon',
  [pairKey('fish', 'ocean')]: 'whale',
  [pairKey('fish', 'fish')]: 'whale',
  [pairKey('fish', 'storm')]: 'shark',
  [pairKey('shark', 'ocean')]: 'shark',
  [pairKey('fish', 'wave')]: 'dolphin',
  [pairKey('dolphin', 'ocean')]: 'dolphin',
  [pairKey('earth', 'ocean')]: 'crab',
  [pairKey('beach', 'life')]: 'crab',
  [pairKey('rock', 'sea')]: 'turtle',
  [pairKey('ocean', 'rock')]: 'turtle',
  [pairKey('sea', 'plant')]: 'octopus',
  [pairKey('ocean', 'life')]: 'octopus',
  [pairKey('water', 'fire')]: 'jellyfish',
  [pairKey('ocean', 'electricity')]: 'jellyfish',
  [pairKey('ocean', 'electricity')]: 'jellyfish',
  [pairKey('lobster', 'sea')]: 'lobster',
  [pairKey('crab', 'ocean')]: 'lobster',
  [pairKey('clam', 'ocean')]: 'pearl',
  [pairKey('sea', 'sand')]: 'clam',
  [pairKey('algae', 'fish')]: 'squid',
  [pairKey('fish', 'darkness')]: 'squid',
  [pairKey('coral', 'fish')]: 'clam',
  [pairKey('ocean', 'coral')]: 'clam',

  // ════════════════════════════════════════════════════════
  // ANIMALS — insects
  // ════════════════════════════════════════════════════════
  [pairKey('life', 'plant')]: 'insect',
  [pairKey('life', 'soil')]: 'worm',
  [pairKey('flower', 'insect')]: 'bee',
  [pairKey('insect', 'pollen')]: 'bee',
  [pairKey('insect', 'sun')]: 'butterfly',
  [pairKey('butterfly', 'flower')]: 'butterfly',
  [pairKey('insect', 'moon')]: 'moth',
  [pairKey('moth', 'candle')]: 'moth',
  [pairKey('insect', 'music')]: 'cricket',
  [pairKey('insect', 'night')]: 'cricket',
  [pairKey('insect', 'fire')]: 'firefly',
  [pairKey('insect', 'light')]: 'firefly',
  [pairKey('insect', 'water')]: 'mosquito',
  [pairKey('swamp', 'insect')]: 'mosquito',
  [pairKey('life', 'sand')]: 'ant',
  [pairKey('insect', 'earth')]: 'ant',
  [pairKey('ant', 'ant')]: 'ant',
  [pairKey('insect', 'web')]: 'spider',
  [pairKey('insect', 'cave')]: 'spider',
  [pairKey('desert', 'insect')]: 'scorpion',
  [pairKey('scorpion', 'desert')]: 'scorpion',
  [pairKey('insect', 'drought')]: 'locust',
  [pairKey('ant', 'drought')]: 'locust',

  // ════════════════════════════════════════════════════════
  // ANIMALS — birds
  // ════════════════════════════════════════════════════════
  [pairKey('life', 'sky')]: 'bird',
  [pairKey('life', 'tree')]: 'bird',
  [pairKey('bird', 'mountain')]: 'eagle',
  [pairKey('bird', 'storm')]: 'hawk',
  [pairKey('bird', 'moon')]: 'owl',
  [pairKey('bird', 'darkness')]: 'owl',
  [pairKey('bird', 'night')]: 'raven',
  [pairKey('raven', 'moon')]: 'raven',
  [pairKey('owl', 'wisdom')]: 'owl',

  // ════════════════════════════════════════════════════════
  // ANIMALS — reptiles
  // ════════════════════════════════════════════════════════
  [pairKey('life', 'rock')]: 'snake',
  [pairKey('desert', 'life')]: 'snake',
  [pairKey('snake', 'sun')]: 'lizard',
  [pairKey('lizard', 'desert')]: 'lizard',
  [pairKey('earth', 'lizard')]: 'dinosaur',
  [pairKey('lizard', 'mountain')]: 'dinosaur',
  [pairKey('fire', 'lizard')]: 'dragon',
  [pairKey('snake', 'water')]: 'crocodile',
  [pairKey('lizard', 'river')]: 'crocodile',

  // ════════════════════════════════════════════════════════
  // ANIMALS — amphibians / small
  // ════════════════════════════════════════════════════════
  [pairKey('life', 'pond')]: 'frog',
  [pairKey('life', 'swamp')]: 'frog',
  [pairKey('frog', 'swamp')]: 'frog',

  // ════════════════════════════════════════════════════════
  // ANIMALS — mammals
  // ════════════════════════════════════════════════════════
  [pairKey('life', 'mountain')]: 'wolf',
  [pairKey('forest', 'mountain')]: 'bear',
  [pairKey('forest', 'life')]: 'bear',
  [pairKey('forest', 'grass')]: 'deer',
  [pairKey('grass', 'life')]: 'horse',
  [pairKey('prairie', 'life')]: 'horse',
  [pairKey('wolf', 'moon')]: 'werewolf',
  [pairKey('glacier', 'horse')]: 'mammoth',
  [pairKey('horse', 'ice')]: 'mammoth',
  [pairKey('forest', 'cat')]: 'panther',
  [pairKey('lion', 'darkness')]: 'panther',
  [pairKey('life', 'jungle')]: 'gorilla',
  [pairKey('forest', 'gorilla')]: 'gorilla',
  [pairKey('life', 'farm')]: 'pig',
  [pairKey('human', 'wolf')]: 'dog',
  [pairKey('dog', 'human')]: 'dog',
  [pairKey('life', 'grass')]: 'rabbit',
  [pairKey('rabbit', 'grass')]: 'rabbit',
  [pairKey('life', 'ocean')]: 'seal',
  [pairKey('seal', 'ice')]: 'penguin',
  [pairKey('bird', 'ice')]: 'penguin',
  [pairKey('cat', 'desert')]: 'lion',
  [pairKey('lion', 'forest')]: 'tiger',
  [pairKey('cat', 'grass')]: 'lion',
  [pairKey('elephant', 'forest')]: 'elephant',
  [pairKey('life', 'prairie')]: 'elephant',
  [pairKey('life', 'mountain')]: 'goat',
  [pairKey('deer', 'mountain')]: 'goat',
  [pairKey('wolf', 'forest')]: 'fox',
  [pairKey('rabbit', 'forest')]: 'fox',
  [pairKey('life', 'night')]: 'bat',
  [pairKey('bird', 'cave')]: 'bat',
  [pairKey('wolf', 'human')]: 'dog',
  [pairKey('life', 'village')]: 'cat',
  [pairKey('human', 'cat')]: 'cat',
  [pairKey('life', 'pasture')]: 'cow',
  [pairKey('grass', 'human')]: 'cow',
  [pairKey('life', 'mountain')]: 'sheep',
  [pairKey('grass', 'sheep')]: 'sheep',

  // ════════════════════════════════════════════════════════
  // MYTHICAL ANIMALS
  // ════════════════════════════════════════════════════════
  [pairKey('bird', 'fire')]: 'phoenix',
  [pairKey('eagle', 'fire')]: 'phoenix',
  [pairKey('phoenix', 'ash')]: 'phoenix',
  [pairKey('ocean', 'storm')]: 'kraken',
  [pairKey('squid', 'ocean')]: 'kraken',
  [pairKey('kraken', 'ocean')]: 'leviathan',
  [pairKey('dragon', 'ocean')]: 'leviathan',
  [pairKey('crystal', 'horse')]: 'unicorn',
  [pairKey('magic', 'horse')]: 'unicorn',
  [pairKey('eagle', 'lion')]: 'griffin',
  [pairKey('eagle', 'wolf')]: 'griffin',
  [pairKey('dragon', 'ocean')]: 'seaDragon',
  [pairKey('dragon', 'sea')]: 'seaDragon',
  [pairKey('dragon', 'ice')]: 'iceDragon',
  [pairKey('dragon', 'glacier')]: 'iceDragon',
  [pairKey('dragon', 'storm')]: 'stormDragon',
  [pairKey('dragon', 'lightning')]: 'stormDragon',
  [pairKey('snake', 'magic')]: 'hydra',
  [pairKey('snake', 'snake')]: 'hydra',
  [pairKey('lion', 'fire')]: 'chimera',
  [pairKey('lion', 'snake')]: 'chimera',
  [pairKey('lion', 'desert')]: 'sphinx',
  [pairKey('lion', 'pyramid')]: 'sphinx',
  [pairKey('bull', 'human')]: 'minotaur',
  [pairKey('cow', 'human')]: 'minotaur',
  [pairKey('horse', 'human')]: 'centaur',
  [pairKey('horse', 'warrior')]: 'centaur',
  [pairKey('fish', 'human')]: 'siren',
  [pairKey('ocean', 'music')]: 'siren',
  [pairKey('snake', 'legend')]: 'basilisk',
  [pairKey('dragon', 'snake')]: 'basilisk',
  [pairKey('lion', 'scorpion')]: 'manticore',
  [pairKey('lion', 'desert')]: 'manticore',
  [pairKey('eagle', 'valkyrie')]: 'valkyrie',
  [pairKey('warrior', 'storm')]: 'valkyrie',

  // ════════════════════════════════════════════════════════
  // HUMAN / CIVILIZATION
  // ════════════════════════════════════════════════════════
  [pairKey('earth', 'life')]: 'human',
  [pairKey('fire', 'life')]: 'human',
  [pairKey('clay', 'life')]: 'golem',
  [pairKey('rock', 'life')]: 'golem',
  [pairKey('human', 'human')]: 'tribe',
  [pairKey('earth', 'tribe')]: 'village',
  [pairKey('tribe', 'wood')]: 'village',
  [pairKey('tribe', 'fire')]: 'village',
  [pairKey('village', 'village')]: 'city',
  [pairKey('village', 'knowledge')]: 'city',
  [pairKey('wood', 'wood')]: 'house',
  [pairKey('house', 'stone')]: 'castle',
  [pairKey('castle', 'stone')]: 'fortress',
  [pairKey('castle', 'iron')]: 'fortress',
  [pairKey('human', 'stone')]: 'tool',
  [pairKey('human', 'wood')]: 'tool',
  [pairKey('metal', 'tool')]: 'weapon',
  [pairKey('iron', 'tool')]: 'sword',
  [pairKey('forge', 'iron')]: 'sword',
  [pairKey('forge', 'steel')]: 'armor',
  [pairKey('metal', 'armor')]: 'armor',
  [pairKey('ocean', 'wood')]: 'ship',
  [pairKey('sea', 'wood')]: 'ship',
  [pairKey('fire', 'metal')]: 'forge',
  [pairKey('human', 'mountain')]: 'mine',
  [pairKey('human', 'rock')]: 'mine',
  [pairKey('rock', 'wood')]: 'wheel',
  [pairKey('river', 'stone')]: 'bridge',
  [pairKey('metal', 'bridge')]: 'bridge',
  [pairKey('clay', 'human')]: 'writing',
  [pairKey('human', 'leaf')]: 'writing',
  [pairKey('human', 'paper')]: 'writing',
  [pairKey('human', 'writing')]: 'knowledge',
  [pairKey('knowledge', 'knowledge')]: 'science',
  [pairKey('army', 'city')]: 'empire',
  [pairKey('city', 'city')]: 'empire',
  [pairKey('human', 'weapon')]: 'army',
  [pairKey('tribe', 'weapon')]: 'army',
  [pairKey('army', 'army')]: 'war',
  [pairKey('empire', 'empire')]: 'war',
  [pairKey('human', 'village')]: 'market',
  [pairKey('city', 'trade')]: 'market',
  [pairKey('human', 'mushroom')]: 'medicine',
  [pairKey('human', 'plant')]: 'medicine',
  [pairKey('human', 'herb')]: 'medicine',
  [pairKey('human', 'sun')]: 'religion',
  [pairKey('human', 'volcano')]: 'religion',
  [pairKey('human', 'lightning')]: 'religion',
  [pairKey('grass', 'human')]: 'farm',
  [pairKey('human', 'plow')]: 'farm',
  [pairKey('city', 'ocean')]: 'harbor',
  [pairKey('ship', 'city')]: 'harbor',
  [pairKey('fire', 'glass')]: 'lighthouse',
  [pairKey('harbor', 'fire')]: 'lighthouse',
  [pairKey('gold', 'human')]: 'crown',
  [pairKey('empire', 'human')]: 'crown',
  [pairKey('city', 'knowledge')]: 'library',
  [pairKey('book', 'house')]: 'library',
  [pairKey('knowledge', 'house')]: 'school',
  [pairKey('child', 'house')]: 'school',
  [pairKey('medicine', 'house')]: 'hospital',
  [pairKey('doctor', 'house')]: 'hospital',
  [pairKey('gold', 'house')]: 'bank',
  [pairKey('city', 'gold')]: 'bank',
  [pairKey('art', 'house')]: 'museum',
  [pairKey('history', 'house')]: 'museum',
  [pairKey('glass', 'sky')]: 'telescope',
  [pairKey('lens', 'star')]: 'telescope',
  [pairKey('human', 'knowledge')]: 'science',
  [pairKey('metal', 'science')]: 'technology',
  [pairKey('city', 'electricity')]: 'technology',
  [pairKey('human', 'sand')]: 'pyramid',
  [pairKey('desert', 'religion')]: 'pyramid',
  [pairKey('water', 'wheel')]: 'mill',
  [pairKey('grain', 'mill')]: 'flour',
  [pairKey('grain', 'stone')]: 'flour',
  [pairKey('earth', 'iron')]: 'compass',
  [pairKey('iron', 'magnet')]: 'compass',
  [pairKey('empire', 'knowledge')]: 'civilization',
  [pairKey('city', 'science')]: 'civilization',
  [pairKey('human', 'religion')]: 'temple',
  [pairKey('religion', 'stone')]: 'temple',
  [pairKey('desert', 'tomb')]: 'pyramid',
  [pairKey('human', 'death')]: 'tomb',
  [pairKey('king', 'chair')]: 'throne',
  [pairKey('empire', 'palace')]: 'throne',
  [pairKey('human', 'plant')]: 'garden',
  [pairKey('city', 'flower')]: 'garden',
  [pairKey('colosseum', 'war')]: 'arena',
  [pairKey('army', 'stadium')]: 'arena',
  [pairKey('city', 'army')]: 'prison',
  [pairKey('castle', 'prisoner')]: 'prison',
  [pairKey('empire', 'builder')]: 'monument',
  [pairKey('stone', 'statue')]: 'monument',
  [pairKey('city', 'water')]: 'aqueduct',
  [pairKey('river', 'city')]: 'aqueduct',

  // ════════════════════════════════════════════════════════
  // TOOLS & OBJECTS
  // ════════════════════════════════════════════════════════
  [pairKey('wood', 'rope')]: 'bow',
  [pairKey('metal', 'bow')]: 'bow',
  [pairKey('wood', 'metal')]: 'arrow',
  [pairKey('bow', 'wood')]: 'arrow',
  [pairKey('metal', 'wood')]: 'axe',
  [pairKey('stone', 'wood')]: 'axe',
  [pairKey('iron', 'wood')]: 'hammer',
  [pairKey('stone', 'handle')]: 'hammer',
  [pairKey('iron', 'earth')]: 'plow',
  [pairKey('metal', 'earth')]: 'plow',
  [pairKey('metal', 'explosion')]: 'gun',
  [pairKey('gunpowder', 'metal')]: 'gun',
  [pairKey('gun', 'metal')]: 'cannon',
  [pairKey('cannon', 'metal')]: 'cannon',
  [pairKey('wood', 'rope')]: 'catapult',
  [pairKey('catapult', 'stone')]: 'catapult',
  [pairKey('horse', 'wheel')]: 'chariot',
  [pairKey('wheel', 'wood')]: 'chariot',
  [pairKey('wood', 'sail')]: 'ship',
  [pairKey('ship', 'metal')]: 'ship',
  [pairKey('earth', 'iron')]: 'compass',
  [pairKey('glass', 'moon')]: 'telescope',
  [pairKey('crystal', 'time')]: 'clock',
  [pairKey('sun', 'circle')]: 'clock',
  [pairKey('paper', 'knowledge')]: 'map',
  [pairKey('world', 'paper')]: 'map',
  [pairKey('iron', 'lock')]: 'key',
  [pairKey('metal', 'door')]: 'key',
  [pairKey('metal', 'key')]: 'lock',
  [pairKey('door', 'metal')]: 'lock',
  [pairKey('plant', 'fiber')]: 'rope',
  [pairKey('vine', 'vine')]: 'rope',
  [pairKey('rope', 'water')]: 'net',
  [pairKey('fisherman', 'rope')]: 'net',
  [pairKey('wax', 'fire')]: 'candle',
  [pairKey('honey', 'fire')]: 'candle',
  [pairKey('glass', 'fire')]: 'lantern',
  [pairKey('candle', 'glass')]: 'lantern',
  [pairKey('wood', 'fire')]: 'torch',
  [pairKey('candle', 'wind')]: 'torch',
  [pairKey('glass', 'water')]: 'mirror',
  [pairKey('silver', 'glass')]: 'mirror',
  [pairKey('gold', 'trade')]: 'coin',
  [pairKey('metal', 'trade')]: 'coin',
  [pairKey('gold', 'gem')]: 'ring',
  [pairKey('metal', 'gem')]: 'ring',
  [pairKey('gold', 'power')]: 'crown',
  [pairKey('human', 'flag')]: 'flag',
  [pairKey('empire', 'cloth')]: 'flag',
  [pairKey('stone', 'artist')]: 'statue',
  [pairKey('chisel', 'stone')]: 'statue',
  [pairKey('metal', 'music')]: 'bell',
  [pairKey('fire', 'metal')]: 'bell',
  [pairKey('wood', 'music')]: 'drum',
  [pairKey('animal', 'skin')]: 'drum',
  [pairKey('string', 'music')]: 'harp',
  [pairKey('metal', 'music')]: 'harp',
  [pairKey('wood', 'pulp')]: 'paper',
  [pairKey('tree', 'water')]: 'paper',
  [pairKey('paper', 'knowledge')]: 'book',
  [pairKey('writing', 'paper')]: 'book',
  [pairKey('paper', 'history')]: 'scroll',
  [pairKey('writing', 'ancient')]: 'scroll',

  // ════════════════════════════════════════════════════════
  // FOOD / COOKING
  // ════════════════════════════════════════════════════════
  [pairKey('fire', 'flour')]: 'bread',
  [pairKey('flour', 'water')]: 'bread',
  [pairKey('bee', 'flower')]: 'honey',
  [pairKey('bee', 'tree')]: 'honey',
  [pairKey('fruit', 'sun')]: 'wine',
  [pairKey('grape', 'sun')]: 'wine',
  [pairKey('grain', 'water')]: 'beer',
  [pairKey('wheat', 'water')]: 'beer',
  [pairKey('fish', 'water')]: 'soup',
  [pairKey('mushroom', 'water')]: 'soup',
  [pairKey('meat', 'water')]: 'soup',
  [pairKey('leaf', 'water')]: 'tea',
  [pairKey('herb', 'water')]: 'tea',
  [pairKey('fire', 'seed')]: 'oil',
  [pairKey('olive', 'stone')]: 'oil',
  [pairKey('ocean', 'sun')]: 'salt',
  [pairKey('fire', 'animal')]: 'meat',
  [pairKey('deer', 'fire')]: 'meat',
  [pairKey('fish', 'fire')]: 'meat',
  [pairKey('fire', 'wine')]: 'alcohol',
  [pairKey('beer', 'grain')]: 'alcohol',
  [pairKey('cow', 'human')]: 'milk',
  [pairKey('life', 'cow')]: 'milk',
  [pairKey('milk', 'time')]: 'cheese',
  [pairKey('milk', 'salt')]: 'cheese',
  [pairKey('milk', 'fire')]: 'butter',
  [pairKey('milk', 'churn')]: 'butter',
  [pairKey('plant', 'fire')]: 'sugar',
  [pairKey('cane', 'fire')]: 'sugar',
  [pairKey('sugar', 'bean')]: 'chocolate',
  [pairKey('cacao', 'fire')]: 'chocolate',
  [pairKey('bean', 'fire')]: 'coffee',
  [pairKey('earth', 'coffee')]: 'coffee',
  [pairKey('fire', 'plant')]: 'spice',
  [pairKey('herb', 'fire')]: 'spice',
  [pairKey('fish', 'salt')]: 'soup',

  // ════════════════════════════════════════════════════════
  // ALCHEMY / POTIONS
  // ════════════════════════════════════════════════════════
  [pairKey('crystal', 'water')]: 'potion',
  [pairKey('gem', 'water')]: 'potion',
  [pairKey('herb', 'magic')]: 'potion',
  [pairKey('potion', 'magic')]: 'elixir',
  [pairKey('life', 'potion')]: 'elixir',
  [pairKey('rain', 'volcano')]: 'acid',
  [pairKey('smoke', 'water')]: 'acid',
  [pairKey('chemistry', 'fire')]: 'acid',
  [pairKey('coal', 'salt')]: 'gunpowder',
  [pairKey('coal', 'smoke')]: 'gunpowder',
  [pairKey('charcoal', 'salt')]: 'gunpowder',
  [pairKey('snake', 'poison')]: 'venom',
  [pairKey('scorpion', 'venom')]: 'venom',
  [pairKey('plant', 'death')]: 'poison',
  [pairKey('mushroom', 'death')]: 'poison',
  [pairKey('venom', 'water')]: 'poison',
  [pairKey('knowledge', 'potion')]: 'alchemy',
  [pairKey('fire', 'gold')]: 'alchemy',

  // ════════════════════════════════════════════════════════
  // ABSTRACT / ENERGY
  // ════════════════════════════════════════════════════════
  [pairKey('iron', 'lightning')]: 'electricity',
  [pairKey('steel', 'lightning')]: 'electricity',
  [pairKey('copper', 'lightning')]: 'electricity',
  [pairKey('fire', 'gunpowder')]: 'explosion',
  [pairKey('gunpowder', 'lightning')]: 'explosion',
  [pairKey('bomb', 'fire')]: 'explosion',
  [pairKey('fire', 'tornado')]: 'firestorm',
  [pairKey('wildfire', 'tornado')]: 'firestorm',
  [pairKey('storm', 'fire')]: 'firestorm',
  [pairKey('earth', 'volcano')]: 'earthquake',
  [pairKey('earth', 'mountain')]: 'earthquake',
  [pairKey('earthquake', 'ocean')]: 'tsunami',
  [pairKey('volcano', 'ocean')]: 'tsunami',
  [pairKey('mountain', 'snow')]: 'avalanche',
  [pairKey('earthquake', 'mountain')]: 'avalanche',
  [pairKey('electricity', 'light')]: 'light',
  [pairKey('fire', 'night')]: 'light',
  [pairKey('sun', 'room')]: 'light',
  [pairKey('shadow', 'light')]: 'darkness',
  [pairKey('void', 'night')]: 'darkness',
  [pairKey('sun', 'night')]: 'eclipse',
  [pairKey('radiation', 'fire')]: 'nuclear',
  [pairKey('atom', 'fire')]: 'nuclear',
  [pairKey('electricity', 'sun')]: 'solar',
  [pairKey('sun', 'technology')]: 'solar',
  [pairKey('sun', 'energy')]: 'energy',
  [pairKey('fire', 'energy')]: 'energy',
  [pairKey('atom', 'atom')]: 'molecule',
  [pairKey('molecule', 'molecule')]: 'chemistry',
  [pairKey('atom', 'fire')]: 'radiation',
  [pairKey('radiation', 'earth')]: 'mutation',

  // ════════════════════════════════════════════════════════
  // TECHNOLOGY
  // ════════════════════════════════════════════════════════
  [pairKey('iron', 'steam')]: 'steamEngine',
  [pairKey('steam', 'steel')]: 'steamEngine',
  [pairKey('steamEngine', 'wheel')]: 'train',
  [pairKey('steamEngine', 'iron')]: 'engine',
  [pairKey('engine', 'metal')]: 'car',
  [pairKey('electricity', 'engine')]: 'car',
  [pairKey('steamEngine', 'city')]: 'factory',
  [pairKey('engine', 'factory')]: 'machine',
  [pairKey('metal', 'machine')]: 'machine',
  [pairKey('engine', 'air')]: 'airplane',
  [pairKey('airplane', 'sky')]: 'airplane',
  [pairKey('engine', 'space')]: 'rocket',
  [pairKey('rocket', 'sky')]: 'rocket',
  [pairKey('rocket', 'planet')]: 'satellite',
  [pairKey('electricity', 'machine')]: 'computer',
  [pairKey('computer', 'computer')]: 'internet',
  [pairKey('internet', 'world')]: 'internet',
  [pairKey('machine', 'human')]: 'robot',
  [pairKey('computer', 'metal')]: 'robot',
  [pairKey('electricity', 'radio')]: 'phone',
  [pairKey('computer', 'phone')]: 'phone',
  [pairKey('light', 'glass')]: 'camera',
  [pairKey('mirror', 'light')]: 'camera',
  [pairKey('electricity', 'air')]: 'radio',
  [pairKey('electricity', 'wave')]: 'radio',
  [pairKey('radio', 'glass')]: 'television',
  [pairKey('camera', 'radio')]: 'television',
  [pairKey('electricity', 'metal')]: 'battery',
  [pairKey('battery', 'machine')]: 'generator',
  [pairKey('electricity', 'crystal')]: 'laser',
  [pairKey('light', 'crystal')]: 'laser',
  [pairKey('gunpowder', 'metal')]: 'bomb',
  [pairKey('explosion', 'metal')]: 'bomb',
  [pairKey('engine', 'helicopter')]: 'drone',
  [pairKey('robot', 'sky')]: 'drone',
  [pairKey('ship', 'engine')]: 'submarine',
  [pairKey('ship', 'ocean')]: 'submarine',
  [pairKey('glass', 'light')]: 'microscope',
  [pairKey('crystal', 'science')]: 'microscope',
  [pairKey('nuclear', 'energy')]: 'reactor',
  [pairKey('atom', 'electricity')]: 'reactor',
  [pairKey('electricity', 'turbine')]: 'generator',
  [pairKey('water', 'turbine')]: 'generator',
  [pairKey('computer', 'writing')]: 'code',
  [pairKey('human', 'computer')]: 'code',
  [pairKey('computer', 'intelligence')]: 'ai',
  [pairKey('robot', 'knowledge')]: 'ai',
  [pairKey('gun', 'technology')]: 'cannon',
  [pairKey('metal', 'fire')]: 'forge',

  // ════════════════════════════════════════════════════════
  // SPACE
  // ════════════════════════════════════════════════════════
  [pairKey('earth', 'sun')]: 'moon',
  [pairKey('sky', 'water')]: 'moon',
  [pairKey('plasma', 'sky')]: 'star',
  [pairKey('sun', 'sky')]: 'star',
  [pairKey('rock', 'star')]: 'planet',
  [pairKey('earth', 'star')]: 'planet',
  [pairKey('ice', 'sky')]: 'comet',
  [pairKey('ice', 'star')]: 'comet',
  [pairKey('star', 'star')]: 'galaxy',
  [pairKey('nebula', 'star')]: 'galaxy',
  [pairKey('cloud', 'star')]: 'nebula',
  [pairKey('dust', 'star')]: 'nebula',
  [pairKey('gas', 'star')]: 'nebula',
  [pairKey('rock', 'sky')]: 'meteor',
  [pairKey('asteroid', 'atmosphere')]: 'meteor',
  [pairKey('moon', 'sun')]: 'eclipse',
  [pairKey('galaxy', 'galaxy')]: 'cosmos',
  [pairKey('galaxy', 'star')]: 'cosmos',
  [pairKey('comet', 'rock')]: 'asteroid',
  [pairKey('comet', 'earth')]: 'asteroid',
  [pairKey('fire', 'star')]: 'supernova',
  [pairKey('star', 'volcano')]: 'supernova',
  [pairKey('galaxy', 'sun')]: 'blackHole',
  [pairKey('supernova', 'star')]: 'blackHole',
  [pairKey('blackHole', 'star')]: 'quasar',
  [pairKey('energy', 'blackHole')]: 'quasar',
  [pairKey('blackHole', 'cosmos')]: 'wormhole',
  [pairKey('space', 'portal')]: 'wormhole',
  [pairKey('rocket', 'human')]: 'spaceship',
  [pairKey('technology', 'rocket')]: 'spaceship',
  [pairKey('human', 'spaceship')]: 'astronaut',
  [pairKey('science', 'space')]: 'astronaut',
  [pairKey('planet', 'life')]: 'alien',
  [pairKey('cosmos', 'life')]: 'alien',

  // ════════════════════════════════════════════════════════
  // MYTHOLOGY / RELIGION
  // ════════════════════════════════════════════════════════
  [pairKey('life', 'smoke')]: 'spirit',
  [pairKey('human', 'smoke')]: 'spirit',
  [pairKey('death', 'human')]: 'spirit',
  [pairKey('dragon', 'human')]: 'myth',
  [pairKey('human', 'lightning')]: 'myth',
  [pairKey('knowledge', 'myth')]: 'legend',
  [pairKey('human', 'myth')]: 'legend',
  [pairKey('crystal', 'moon')]: 'magic',
  [pairKey('gem', 'moon')]: 'magic',
  [pairKey('wizard', 'wand')]: 'magic',
  [pairKey('religion', 'sun')]: 'sunGod',
  [pairKey('empire', 'sun')]: 'sunGod',
  [pairKey('magic', 'human')]: 'wizard',
  [pairKey('knowledge', 'magic')]: 'wizard',
  [pairKey('magic', 'woman')]: 'witch',
  [pairKey('herb', 'moon')]: 'witch',
  [pairKey('magic', 'fairy')]: 'fairy',
  [pairKey('flower', 'magic')]: 'fairy',
  [pairKey('giant', 'mountain')]: 'titan',
  [pairKey('giant', 'earth')]: 'titan',
  [pairKey('human', 'mountain')]: 'giant',
  [pairKey('stone', 'life')]: 'giant',
  [pairKey('light', 'human')]: 'angel',
  [pairKey('heaven', 'life')]: 'angel',
  [pairKey('darkness', 'human')]: 'demon',
  [pairKey('hell', 'life')]: 'demon',
  [pairKey('forest', 'magic')]: 'elf',
  [pairKey('magic', 'human')]: 'elf',
  [pairKey('mine', 'human')]: 'dwarf',
  [pairKey('mountain', 'human')]: 'dwarf',
  [pairKey('war', 'human')]: 'orc',
  [pairKey('darkness', 'warrior')]: 'orc',
  [pairKey('bridge', 'giant')]: 'troll',
  [pairKey('cave', 'giant')]: 'troll',
  [pairKey('death', 'magic')]: 'necromancer',
  [pairKey('death', 'wizard')]: 'necromancer',
  [pairKey('spirit', 'dark')]: 'wraith',
  [pairKey('soul', 'darkness')]: 'wraith',
  [pairKey('spirit', 'death')]: 'banshee',
  [pairKey('soul', 'fear')]: 'banshee',
  [pairKey('death', 'magic')]: 'curse',
  [pairKey('witch', 'magic')]: 'curse',
  [pairKey('stone', 'magic')]: 'rune',
  [pairKey('writing', 'magic')]: 'rune',
  [pairKey('human', 'night')]: 'vampire',
  [pairKey('bat', 'human')]: 'vampire',
  [pairKey('zombie', 'death')]: 'zombie',
  [pairKey('human', 'death')]: 'zombie',
  [pairKey('necromancer', 'human')]: 'zombie',

  // ════════════════════════════════════════════════════════
  // SCIENCE
  // ════════════════════════════════════════════════════════
  [pairKey('molecule', 'life')]: 'dna',
  [pairKey('cell', 'cell')]: 'dna',
  [pairKey('dna', 'time')]: 'evolution',
  [pairKey('life', 'time')]: 'evolution',
  [pairKey('mass', 'energy')]: 'gravity',
  [pairKey('earth', 'physics')]: 'gravity',
  [pairKey('iron', 'electricity')]: 'magnetism',
  [pairKey('metal', 'electricity')]: 'magnetism',
  [pairKey('molecule', 'fire')]: 'chemistry',
  [pairKey('mineral', 'science')]: 'chemistry',
  [pairKey('cell', 'science')]: 'biology',
  [pairKey('life', 'science')]: 'biology',
  [pairKey('energy', 'science')]: 'physics',
  [pairKey('atom', 'science')]: 'physics',
  [pairKey('number', 'science')]: 'math',
  [pairKey('logic', 'science')]: 'math',
  [pairKey('bacteria', 'life')]: 'virus',
  [pairKey('organism', 'sickness')]: 'virus',
  [pairKey('water', 'life')]: 'bacteria',
  [pairKey('organism', 'earth')]: 'bacteria',
  [pairKey('atom', 'life')]: 'cell',
  [pairKey('bacteria', 'light')]: 'cell',
  [pairKey('cell', 'life')]: 'gene',
  [pairKey('dna', 'science')]: 'gene',
  [pairKey('medicine', 'virus')]: 'vaccine',
  [pairKey('science', 'medicine')]: 'vaccine',
  [pairKey('atom', 'energy')]: 'radiation',
  [pairKey('nuclear', 'atom')]: 'radiation',

  // ════════════════════════════════════════════════════════
  // ABSTRACT / EMOTIONS
  // ════════════════════════════════════════════════════════
  [pairKey('air', 'electricity')]: 'sound',
  [pairKey('wave', 'air')]: 'sound',
  [pairKey('sound', 'human')]: 'music',
  [pairKey('drum', 'harp')]: 'music',
  [pairKey('color', 'human')]: 'art',
  [pairKey('paint', 'human')]: 'art',
  [pairKey('human', 'heart')]: 'love',
  [pairKey('love', 'human')]: 'emotion',
  [pairKey('human', 'danger')]: 'fear',
  [pairKey('monster', 'human')]: 'fear',
  [pairKey('storm', 'order')]: 'chaos',
  [pairKey('void', 'life')]: 'chaos',
  [pairKey('law', 'city')]: 'order',
  [pairKey('knowledge', 'law')]: 'order',
  [pairKey('chaos', 'order')]: 'balance',
  [pairKey('light', 'darkness')]: 'balance',
  [pairKey('life', 'time')]: 'death',
  [pairKey('void', 'life')]: 'death',
  [pairKey('death', 'spirit')]: 'soul',
  [pairKey('human', 'dream')]: 'soul',
  [pairKey('brain', 'life')]: 'mind',
  [pairKey('human', 'knowledge')]: 'mind',
  [pairKey('mind', 'sleep')]: 'dream',
  [pairKey('soul', 'night')]: 'dream',
  [pairKey('star', 'human')]: 'time',
  [pairKey('cosmos', 'flow')]: 'time',
  [pairKey('space', 'darkness')]: 'void',
  [pairKey('blackHole', 'universe')]: 'void',
  [pairKey('cosmos', 'cosmos')]: 'infinity',
  [pairKey('void', 'cosmos')]: 'infinity',
  [pairKey('knowledge', 'time')]: 'wisdom',
  [pairKey('elder', 'knowledge')]: 'wisdom',
  [pairKey('chaos', 'mind')]: 'madness',
  [pairKey('void', 'mind')]: 'madness',
  [pairKey('sun', 'soul')]: 'hope',
  [pairKey('rainbow', 'human')]: 'hope',
  [pairKey('void', 'soul')]: 'despair',
  [pairKey('darkness', 'soul')]: 'despair',
  [pairKey('mind', 'time')]: 'memory',
  [pairKey('soul', 'image')]: 'memory',
  [pairKey('mind', 'question')]: 'thought',
  [pairKey('brain', 'electricity')]: 'thought',
  [pairKey('love', 'fear')]: 'emotion',
  [pairKey('soul', 'mind')]: 'consciousness',
  [pairKey('mind', 'life')]: 'consciousness',

  // ════════════════════════════════════════════════════════
  // CROSS-CATEGORY CHAINS
  // ════════════════════════════════════════════════════════
  [pairKey('forge', 'science')]: 'technology',
  [pairKey('human', 'arrow')]: 'bow',
  [pairKey('warrior', 'horse')]: 'chariot',
  [pairKey('warrior', 'metal')]: 'armor',
  [pairKey('science', 'magic')]: 'alchemy',
  [pairKey('human', 'magic')]: 'wizard',
  [pairKey('ocean', 'magic')]: 'siren',
  [pairKey('desert', 'magic')]: 'sphinx',
  [pairKey('storm', 'dragon')]: 'stormDragon',
  [pairKey('ocean', 'dragon')]: 'seaDragon',
  [pairKey('snow', 'dragon')]: 'iceDragon',
  [pairKey('human', 'computer')]: 'ai',
  [pairKey('robot', 'learning')]: 'ai',
  [pairKey('electricity', 'computer')]: 'code',
  [pairKey('satellite', 'computer')]: 'internet',
  [pairKey('library', 'internet')]: 'internet',

  // ════════════════════════════════════════════════════════
  // NEW RECIPES — BATCH 1: NIGHT / DAY / COLD / HEAT / WIND
  // ════════════════════════════════════════════════════════
  [pairKey('night', 'wind')]: 'storm',
  [pairKey('night', 'cold')]: 'frost',
  [pairKey('night', 'fog')]: 'ghost',
  [pairKey('night', 'wolf')]: 'werewolf',
  [pairKey('night', 'thunder')]: 'storm',
  [pairKey('night', 'rain')]: 'mist',
  [pairKey('night', 'moon')]: 'dream',
  [pairKey('night', 'magic')]: 'spell',
  [pairKey('night', 'owl')]: 'wisdom',
  [pairKey('night', 'witch')]: 'ritual',
  [pairKey('night', 'darkness')]: 'void',
  [pairKey('night', 'star')]: 'moon',
  [pairKey('night', 'ocean')]: 'tide',
  [pairKey('night', 'lightning')]: 'storm',

  [pairKey('day', 'rain')]: 'rainbow',
  [pairKey('day', 'storm')]: 'rainbow',
  [pairKey('day', 'night')]: 'eclipse',
  [pairKey('day', 'fog')]: 'dew',
  [pairKey('day', 'heat')]: 'heatwave',
  [pairKey('day', 'cold')]: 'snow',
  [pairKey('day', 'sun')]: 'heatwave',
  [pairKey('day', 'flower')]: 'pollen',
  [pairKey('day', 'moon')]: 'eclipse',

  [pairKey('cold', 'rain')]: 'snow',
  [pairKey('cold', 'cloud')]: 'snow',
  [pairKey('cold', 'wind')]: 'blizzard',
  [pairKey('cold', 'mountain')]: 'glacier',
  [pairKey('cold', 'ocean')]: 'ice',
  [pairKey('cold', 'river')]: 'ice',
  [pairKey('cold', 'fire')]: 'steam',
  [pairKey('cold', 'air')]: 'frost',
  [pairKey('cold', 'lake')]: 'ice',
  [pairKey('cold', 'fog')]: 'frost',
  [pairKey('cold', 'magma')]: 'obsidian',
  [pairKey('cold', 'lava')]: 'rock',
  [pairKey('cold', 'desert')]: 'tundra',

  [pairKey('heat', 'water')]: 'steam',
  [pairKey('heat', 'sand')]: 'glass',
  [pairKey('heat', 'metal')]: 'forge',
  [pairKey('heat', 'ice')]: 'water',
  [pairKey('heat', 'forest')]: 'wildfire',
  [pairKey('heat', 'fire')]: 'inferno',
  [pairKey('heat', 'volcano')]: 'eruption',
  [pairKey('heat', 'earth')]: 'desert',
  [pairKey('heat', 'rock')]: 'magma',
  [pairKey('heat', 'clay')]: 'brick',
  [pairKey('heat', 'grain')]: 'flour',
  [pairKey('heat', 'milk')]: 'butter',
  [pairKey('heat', 'ocean')]: 'vapor',
  [pairKey('heat', 'air')]: 'drought',

  [pairKey('wind', 'fire')]: 'wildfire',
  [pairKey('wind', 'water')]: 'wave',
  [pairKey('wind', 'cloud')]: 'storm',
  [pairKey('wind', 'rain')]: 'storm',
  [pairKey('wind', 'mountain')]: 'cliff',
  [pairKey('wind', 'seed')]: 'pollen',
  [pairKey('wind', 'sand')]: 'sandstorm',
  [pairKey('wind', 'snow')]: 'blizzard',
  [pairKey('wind', 'lightning')]: 'storm',
  [pairKey('wind', 'ship')]: 'sailor',
  [pairKey('wind', 'leaf')]: 'autumn',
  [pairKey('wind', 'desert')]: 'sandstorm',
  [pairKey('wind', 'kite')]: 'sky',

  // ════════════════════════════════════════════════════════
  // NEW RECIPES — BATCH 2: GAS / MASS / SPACE
  // ════════════════════════════════════════════════════════
  [pairKey('gas', 'fire')]: 'plasma',
  [pairKey('gas', 'air')]: 'atmosphere',
  [pairKey('gas', 'electricity')]: 'plasma',
  [pairKey('gas', 'heat')]: 'plasma',
  [pairKey('gas', 'cold')]: 'fog',
  [pairKey('gas', 'volcano')]: 'eruption',
  [pairKey('gas', 'pressure')]: 'explosion',
  [pairKey('gas', 'water')]: 'acid',
  [pairKey('gas', 'metal')]: 'rust',
  [pairKey('gas', 'planet')]: 'atmosphere',

  [pairKey('mass', 'star')]: 'blackHole',
  [pairKey('mass', 'earth')]: 'gravity',
  [pairKey('mass', 'water')]: 'tide',
  [pairKey('mass', 'space')]: 'blackHole',
  [pairKey('mass', 'void')]: 'blackHole',
  [pairKey('mass', 'metal')]: 'iron',
  [pairKey('mass', 'rock')]: 'mountain',
  [pairKey('mass', 'planet')]: 'gravity',

  [pairKey('space', 'star')]: 'galaxy',
  [pairKey('space', 'earth')]: 'planet',
  [pairKey('space', 'time')]: 'cosmos',
  [pairKey('space', 'life')]: 'alien',
  [pairKey('space', 'technology')]: 'rocket',
  [pairKey('space', 'human')]: 'astronaut',
  [pairKey('space', 'cold')]: 'comet',
  [pairKey('space', 'rock')]: 'asteroid',
  [pairKey('space', 'dust')]: 'nebula',
  [pairKey('space', 'ship')]: 'spaceship',

  // ════════════════════════════════════════════════════════
  // NEW RECIPES — BATCH 3: WAX / RESIN / FIBER / SEASONS
  // ════════════════════════════════════════════════════════
  [pairKey('wax', 'bee')]: 'honey',
  [pairKey('wax', 'fire')]: 'candle',
  [pairKey('wax', 'flower')]: 'scent',
  [pairKey('wax', 'water')]: 'soap',
  [pairKey('wax', 'paint')]: 'art',
  [pairKey('wax', 'resin')]: 'amber',

  [pairKey('resin', 'fire')]: 'smoke',
  [pairKey('resin', 'earth')]: 'amber',
  [pairKey('resin', 'mineral')]: 'amber',
  [pairKey('resin', 'plant')]: 'medicine',
  [pairKey('resin', 'water')]: 'glue',

  [pairKey('fiber', 'plant')]: 'rope',
  [pairKey('fiber', 'wool')]: 'cloth',
  [pairKey('fiber', 'cotton')]: 'cloth',
  [pairKey('fiber', 'silk')]: 'cloth',
  [pairKey('fiber', 'water')]: 'paper',
  [pairKey('fiber', 'dye')]: 'cloth',

  [pairKey('autumn', 'tree')]: 'leaf',
  [pairKey('autumn', 'rain')]: 'flood',
  [pairKey('autumn', 'wind')]: 'storm',
  [pairKey('autumn', 'harvest')]: 'grain',

  // ════════════════════════════════════════════════════════
  // NEW RECIPES — BATCH 4: MATERIALS
  // ════════════════════════════════════════════════════════
  [pairKey('rubber', 'tree')]: 'resin',
  [pairKey('rubber', 'oil')]: 'plastic',
  [pairKey('rubber', 'fire')]: 'smoke',
  [pairKey('rubber', 'car')]: 'road',
  [pairKey('rubber', 'electricity')]: 'battery',

  [pairKey('wool', 'sheep')]: 'cloth',
  [pairKey('wool', 'water')]: 'cloth',
  [pairKey('wool', 'fire')]: 'ash',
  [pairKey('wool', 'dye')]: 'cloth',
  [pairKey('wool', 'human')]: 'cloth',

  [pairKey('silk', 'worm')]: 'cloth',
  [pairKey('silk', 'insect')]: 'cloth',
  [pairKey('silk', 'water')]: 'dye',
  [pairKey('silk', 'gold')]: 'wealth',
  [pairKey('silk', 'art')]: 'beauty',

  [pairKey('leather', 'fire')]: 'armor',
  [pairKey('leather', 'sword')]: 'armor',
  [pairKey('leather', 'metal')]: 'armor',
  [pairKey('leather', 'animal')]: 'armor',
  [pairKey('leather', 'oil')]: 'armor',

  [pairKey('cloth', 'dye')]: 'art',
  [pairKey('cloth', 'fire')]: 'ash',
  [pairKey('cloth', 'gold')]: 'flag',
  [pairKey('cloth', 'wind')]: 'sail',
  [pairKey('cloth', 'water')]: 'soap',
  [pairKey('cloth', 'art')]: 'tapestry',

  [pairKey('brick', 'stone')]: 'wall',
  [pairKey('brick', 'earth')]: 'house',
  [pairKey('brick', 'fire')]: 'kiln',
  [pairKey('brick', 'wall')]: 'fortress',
  [pairKey('brick', 'city')]: 'civilization',

  [pairKey('cement', 'sand')]: 'concrete',
  [pairKey('cement', 'water')]: 'concrete',
  [pairKey('cement', 'stone')]: 'wall',
  [pairKey('cement', 'brick')]: 'house',

  [pairKey('concrete', 'steel')]: 'bridge',
  [pairKey('concrete', 'city')]: 'road',
  [pairKey('concrete', 'water')]: 'dam',
  [pairKey('concrete', 'earthquake')]: 'ruin',

  [pairKey('plastic', 'ocean')]: 'pollution',
  [pairKey('plastic', 'fire')]: 'pollution',
  [pairKey('plastic', 'earth')]: 'pollution',
  [pairKey('plastic', 'oil')]: 'pollution',
  [pairKey('plastic', 'technology')]: 'computer',

  [pairKey('ink', 'paper')]: 'book',
  [pairKey('ink', 'writing')]: 'book',
  [pairKey('ink', 'water')]: 'dye',
  [pairKey('ink', 'art')]: 'painting',
  [pairKey('ink', 'scroll')]: 'legend',

  [pairKey('dye', 'water')]: 'color',
  [pairKey('dye', 'plant')]: 'ink',
  [pairKey('dye', 'flower')]: 'color',
  [pairKey('dye', 'cloth')]: 'art',
  [pairKey('dye', 'art')]: 'painting',

  [pairKey('paint', 'wall')]: 'art',
  [pairKey('paint', 'cave')]: 'art',
  [pairKey('paint', 'stone')]: 'art',
  [pairKey('paint', 'water')]: 'dye',
  [pairKey('paint', 'fire')]: 'light',
  [pairKey('paint', 'brush')]: 'art',

  [pairKey('color', 'light')]: 'rainbow',
  [pairKey('color', 'rain')]: 'rainbow',
  [pairKey('color', 'sun')]: 'rainbow',
  [pairKey('color', 'art')]: 'beauty',
  [pairKey('color', 'flower')]: 'beauty',

  [pairKey('glue', 'wood')]: 'house',
  [pairKey('glue', 'paper')]: 'book',
  [pairKey('glue', 'clay')]: 'pottery',
  [pairKey('glue', 'tree')]: 'resin',
  [pairKey('glue', 'sand')]: 'cement',

  [pairKey('soap', 'water')]: 'bubble',
  [pairKey('soap', 'oil')]: 'soap',
  [pairKey('soap', 'fire')]: 'ash',
  [pairKey('soap', 'human')]: 'medicine',
  [pairKey('soap', 'plant')]: 'soap',

  [pairKey('bubble', 'air')]: 'foam',
  [pairKey('bubble', 'water')]: 'foam',
  [pairKey('bubble', 'glass')]: 'crystal',
  [pairKey('bubble', 'fire')]: 'steam',
  [pairKey('bubble', 'magic')]: 'spell',

  // ════════════════════════════════════════════════════════
  // NEW RECIPES — BATCH 5: HUMAN ROLES
  // ════════════════════════════════════════════════════════
  [pairKey('child', 'human')]: 'tribe',
  [pairKey('child', 'school')]: 'knowledge',
  [pairKey('child', 'time')]: 'human',
  [pairKey('child', 'fire')]: 'warmth',
  [pairKey('child', 'magic')]: 'fairy',

  [pairKey('elder', 'knowledge')]: 'wisdom',
  [pairKey('elder', 'human')]: 'wisdom',
  [pairKey('elder', 'fire')]: 'shaman',
  [pairKey('elder', 'magic')]: 'wizard',
  [pairKey('elder', 'tribe')]: 'legend',
  [pairKey('elder', 'village')]: 'legend',
  [pairKey('elder', 'time')]: 'history',

  [pairKey('doctor', 'human')]: 'medicine',
  [pairKey('doctor', 'plant')]: 'medicine',
  [pairKey('doctor', 'virus')]: 'vaccine',
  [pairKey('doctor', 'knowledge')]: 'biology',
  [pairKey('doctor', 'hospital')]: 'medicine',
  [pairKey('doctor', 'science')]: 'medicine',

  [pairKey('fisherman', 'ocean')]: 'fish',
  [pairKey('fisherman', 'river')]: 'salmon',
  [pairKey('fisherman', 'sea')]: 'lobster',
  [pairKey('fisherman', 'net')]: 'fish',
  [pairKey('fisherman', 'boat')]: 'harbor',
  [pairKey('fisherman', 'village')]: 'harbor',

  [pairKey('merchant', 'city')]: 'market',
  [pairKey('merchant', 'gold')]: 'coin',
  [pairKey('merchant', 'ship')]: 'harbor',
  [pairKey('merchant', 'road')]: 'market',
  [pairKey('merchant', 'silk')]: 'wealth',
  [pairKey('merchant', 'spice')]: 'wealth',

  [pairKey('king', 'army')]: 'empire',
  [pairKey('king', 'gold')]: 'crown',
  [pairKey('king', 'palace')]: 'empire',
  [pairKey('king', 'war')]: 'empire',
  [pairKey('king', 'religion')]: 'sunGod',
  [pairKey('king', 'magic')]: 'wizard',

  [pairKey('knight', 'sword')]: 'warrior',
  [pairKey('knight', 'horse')]: 'chariot',
  [pairKey('knight', 'castle')]: 'fortress',
  [pairKey('knight', 'dragon')]: 'legend',
  [pairKey('knight', 'armor')]: 'warrior',
  [pairKey('knight', 'quest')]: 'legend',

  [pairKey('pirate', 'treasure')]: 'gold',
  [pairKey('pirate', 'ocean')]: 'ship',
  [pairKey('pirate', 'ship')]: 'harbor',
  [pairKey('pirate', 'gold')]: 'treasure',
  [pairKey('pirate', 'island')]: 'treasure',
  [pairKey('pirate', 'storm')]: 'shipwreck',

  [pairKey('sailor', 'ship')]: 'harbor',
  [pairKey('sailor', 'ocean')]: 'fish',
  [pairKey('sailor', 'star')]: 'compass',
  [pairKey('sailor', 'compass')]: 'map',
  [pairKey('sailor', 'storm')]: 'shipwreck',
  [pairKey('sailor', 'island')]: 'harbor',

  [pairKey('farmer', 'cow')]: 'milk',
  [pairKey('farmer', 'pig')]: 'meat',
  [pairKey('farmer', 'earth')]: 'soil',
  [pairKey('farmer', 'wheat')]: 'flour',
  [pairKey('farmer', 'rain')]: 'harvest',
  [pairKey('farmer', 'village')]: 'farm',

  [pairKey('hunter', 'forest')]: 'deer',
  [pairKey('hunter', 'bow')]: 'arrow',
  [pairKey('hunter', 'animal')]: 'meat',
  [pairKey('hunter', 'cave')]: 'bear',
  [pairKey('hunter', 'wolf')]: 'fur',
  [pairKey('hunter', 'mountain')]: 'eagle',

  [pairKey('explorer', 'map')]: 'civilization',
  [pairKey('explorer', 'ocean')]: 'island',
  [pairKey('explorer', 'desert')]: 'oasis',
  [pairKey('explorer', 'mountain')]: 'valley',
  [pairKey('explorer', 'ship')]: 'harbor',
  [pairKey('explorer', 'compass')]: 'map',
  [pairKey('explorer', 'star')]: 'telescope',

  [pairKey('scholar', 'book')]: 'knowledge',
  [pairKey('scholar', 'science')]: 'discovery',
  [pairKey('scholar', 'magic')]: 'wizard',
  [pairKey('scholar', 'history')]: 'legend',
  [pairKey('scholar', 'library')]: 'knowledge',
  [pairKey('scholar', 'alchemy')]: 'theory',

  [pairKey('engineer', 'machine')]: 'factory',
  [pairKey('engineer', 'electricity')]: 'technology',
  [pairKey('engineer', 'metal')]: 'machine',
  [pairKey('engineer', 'water')]: 'mill',
  [pairKey('engineer', 'bridge')]: 'aqueduct',
  [pairKey('engineer', 'science')]: 'invention',

  [pairKey('chef', 'meat')]: 'stew',
  [pairKey('chef', 'fire')]: 'meat',
  [pairKey('chef', 'water')]: 'soup',
  [pairKey('chef', 'spice')]: 'flavor',
  [pairKey('chef', 'bread')]: 'bakery',
  [pairKey('chef', 'fruit')]: 'jam',
  [pairKey('chef', 'flour')]: 'bread',

  [pairKey('priest', 'religion')]: 'temple',
  [pairKey('priest', 'human')]: 'blessing',
  [pairKey('priest', 'death')]: 'ritual',
  [pairKey('priest', 'fire')]: 'ritual',
  [pairKey('priest', 'magic')]: 'blessing',
  [pairKey('priest', 'temple')]: 'religion',

  [pairKey('shaman', 'fire')]: 'ritual',
  [pairKey('shaman', 'spirit')]: 'ritual',
  [pairKey('shaman', 'plant')]: 'medicine',
  [pairKey('shaman', 'drum')]: 'music',
  [pairKey('shaman', 'animal')]: 'totem',
  [pairKey('shaman', 'smoke')]: 'spirit',
  [pairKey('shaman', 'magic')]: 'spell',

  [pairKey('alchemist', 'gold')]: 'elixir',
  [pairKey('alchemist', 'fire')]: 'explosion',
  [pairKey('alchemist', 'metal')]: 'gold',
  [pairKey('alchemist', 'water')]: 'potion',
  [pairKey('alchemist', 'magic')]: 'elixir',
  [pairKey('alchemist', 'science')]: 'discovery',
  [pairKey('alchemist', 'crystal')]: 'gem',

  [pairKey('gladiator', 'arena')]: 'warrior',
  [pairKey('gladiator', 'sword')]: 'warrior',
  [pairKey('gladiator', 'lion')]: 'legend',
  [pairKey('gladiator', 'death')]: 'ghost',
  [pairKey('gladiator', 'colosseum')]: 'glory',

  [pairKey('monk', 'temple')]: 'religion',
  [pairKey('monk', 'meditation')]: 'wisdom',
  [pairKey('monk', 'mountain')]: 'monastery',
  [pairKey('monk', 'knowledge')]: 'wisdom',
  [pairKey('monk', 'fire')]: 'enlightenment',
  [pairKey('monk', 'water')]: 'peace',

  [pairKey('spy', 'city')]: 'war',
  [pairKey('spy', 'technology')]: 'internet',
  [pairKey('spy', 'shadow')]: 'darkness',
  [pairKey('spy', 'night')]: 'darkness',
  [pairKey('spy', 'empire')]: 'war',

  [pairKey('pilot', 'airplane')]: 'sky',
  [pairKey('pilot', 'sky')]: 'airplane',
  [pairKey('pilot', 'storm')]: 'lightning',
  [pairKey('pilot', 'rocket')]: 'astronaut',
  [pairKey('pilot', 'war')]: 'drone',

  // ════════════════════════════════════════════════════════
  // NEW RECIPES — BATCH 6: CIVILIZATION STRUCTURES
  // ════════════════════════════════════════════════════════
  [pairKey('palace', 'king')]: 'empire',
  [pairKey('palace', 'gold')]: 'empire',
  [pairKey('palace', 'stone')]: 'fortress',
  [pairKey('palace', 'garden')]: 'beauty',
  [pairKey('palace', 'fire')]: 'ruin',

  [pairKey('cathedral', 'stone')]: 'religion',
  [pairKey('cathedral', 'religion')]: 'blessing',
  [pairKey('cathedral', 'city')]: 'civilization',
  [pairKey('cathedral', 'bell')]: 'music',
  [pairKey('cathedral', 'glass')]: 'art',

  [pairKey('tavern', 'ale')]: 'alcohol',
  [pairKey('tavern', 'human')]: 'city',
  [pairKey('tavern', 'fire')]: 'warmth',
  [pairKey('tavern', 'music')]: 'joy',
  [pairKey('tavern', 'beer')]: 'alcohol',

  [pairKey('port', 'ship')]: 'harbor',
  [pairKey('port', 'ocean')]: 'harbor',
  [pairKey('port', 'city')]: 'harbor',
  [pairKey('port', 'trade')]: 'market',
  [pairKey('port', 'merchant')]: 'market',

  [pairKey('wall', 'stone')]: 'fortress',
  [pairKey('wall', 'castle')]: 'fortress',
  [pairKey('wall', 'city')]: 'fortress',
  [pairKey('wall', 'fire')]: 'ruin',
  [pairKey('wall', 'earth')]: 'fortress',

  [pairKey('camp', 'fire')]: 'tribe',
  [pairKey('camp', 'army')]: 'war',
  [pairKey('camp', 'human')]: 'tribe',
  [pairKey('camp', 'tent')]: 'village',
  [pairKey('camp', 'war')]: 'fortress',

  [pairKey('road', 'stone')]: 'civilization',
  [pairKey('road', 'city')]: 'civilization',
  [pairKey('road', 'empire')]: 'civilization',
  [pairKey('road', 'wheel')]: 'chariot',
  [pairKey('road', 'car')]: 'city',

  [pairKey('university', 'knowledge')]: 'science',
  [pairKey('university', 'city')]: 'civilization',
  [pairKey('university', 'human')]: 'scholar',
  [pairKey('university', 'science')]: 'technology',
  [pairKey('university', 'book')]: 'knowledge',

  [pairKey('theater', 'art')]: 'music',
  [pairKey('theater', 'music')]: 'emotion',
  [pairKey('theater', 'city')]: 'civilization',
  [pairKey('theater', 'fire')]: 'light',
  [pairKey('theater', 'human')]: 'art',

  [pairKey('parliament', 'city')]: 'civilization',
  [pairKey('parliament', 'war')]: 'peace',
  [pairKey('parliament', 'law')]: 'order',
  [pairKey('parliament', 'empire')]: 'civilization',
  [pairKey('parliament', 'knowledge')]: 'justice',

  [pairKey('guild', 'metal')]: 'forge',
  [pairKey('guild', 'city')]: 'market',
  [pairKey('guild', 'human')]: 'tribe',
  [pairKey('guild', 'knowledge')]: 'university',
  [pairKey('guild', 'weapon')]: 'army',

  [pairKey('dungeon', 'castle')]: 'prison',
  [pairKey('dungeon', 'monster')]: 'fear',
  [pairKey('dungeon', 'dark')]: 'ghost',
  [pairKey('dungeon', 'treasure')]: 'quest',
  [pairKey('dungeon', 'death')]: 'skeleton',

  [pairKey('graveyard', 'death')]: 'ghost',
  [pairKey('graveyard', 'magic')]: 'necromancer',
  [pairKey('graveyard', 'night')]: 'ghost',
  [pairKey('graveyard', 'human')]: 'tomb',
  [pairKey('graveyard', 'moonlight')]: 'zombie',

  [pairKey('tower', 'stone')]: 'castle',
  [pairKey('tower', 'fire')]: 'lighthouse',
  [pairKey('tower', 'wizard')]: 'magic',
  [pairKey('tower', 'lightning')]: 'electricity',
  [pairKey('tower', 'city')]: 'civilization',

  // ════════════════════════════════════════════════════════
  // NEW RECIPES — BATCH 7: FOOD CHAINS
  // ════════════════════════════════════════════════════════
  [pairKey('grape', 'sun')]: 'wine',
  [pairKey('grape', 'water')]: 'juice',
  [pairKey('grape', 'time')]: 'wine',
  [pairKey('grape', 'sugar')]: 'wine',
  [pairKey('grape', 'harvest')]: 'wine',

  [pairKey('apple', 'sun')]: 'cider',
  [pairKey('apple', 'water')]: 'juice',
  [pairKey('apple', 'sugar')]: 'jam',
  [pairKey('apple', 'fire')]: 'cider',
  [pairKey('apple', 'tree')]: 'fruit',

  [pairKey('orange', 'water')]: 'juice',
  [pairKey('orange', 'sun')]: 'vitamin',
  [pairKey('orange', 'sugar')]: 'jam',
  [pairKey('orange', 'acid')]: 'lemon',

  [pairKey('lemon', 'water')]: 'juice',
  [pairKey('lemon', 'sugar')]: 'jam',
  [pairKey('lemon', 'salt')]: 'vinegar',
  [pairKey('lemon', 'acid')]: 'vinegar',

  [pairKey('berry', 'sugar')]: 'jam',
  [pairKey('berry', 'water')]: 'juice',
  [pairKey('berry', 'forest')]: 'medicine',
  [pairKey('berry', 'fire')]: 'wine',
  [pairKey('berry', 'sun')]: 'fruit',

  [pairKey('corn', 'fire')]: 'popcorn',
  [pairKey('corn', 'water')]: 'soup',
  [pairKey('corn', 'sun')]: 'grain',
  [pairKey('corn', 'earth')]: 'grain',
  [pairKey('corn', 'mill')]: 'flour',

  [pairKey('potato', 'fire')]: 'food',
  [pairKey('potato', 'water')]: 'soup',
  [pairKey('potato', 'earth')]: 'grain',
  [pairKey('potato', 'salt')]: 'food',
  [pairKey('potato', 'oil')]: 'food',

  [pairKey('bean', 'fire')]: 'coffee',
  [pairKey('bean', 'water')]: 'soup',
  [pairKey('bean', 'earth')]: 'plant',
  [pairKey('bean', 'sugar')]: 'chocolate',
  [pairKey('bean', 'salt')]: 'food',

  [pairKey('olive', 'stone')]: 'oil',
  [pairKey('olive', 'sun')]: 'oil',
  [pairKey('olive', 'water')]: 'oil',
  [pairKey('olive', 'salt')]: 'food',

  [pairKey('cacao', 'fire')]: 'chocolate',
  [pairKey('cacao', 'sugar')]: 'chocolate',
  [pairKey('cacao', 'milk')]: 'chocolate',
  [pairKey('cacao', 'water')]: 'chocolate',

  [pairKey('cane', 'fire')]: 'sugar',
  [pairKey('cane', 'water')]: 'sugar',
  [pairKey('cane', 'sun')]: 'sugar',
  [pairKey('cane', 'mill')]: 'sugar',

  [pairKey('egg', 'fire')]: 'food',
  [pairKey('egg', 'flour')]: 'bread',
  [pairKey('egg', 'sugar')]: 'cake',
  [pairKey('egg', 'milk')]: 'pudding',
  [pairKey('egg', 'butter')]: 'cake',
  [pairKey('egg', 'bird')]: 'bird',
  [pairKey('egg', 'heat')]: 'food',

  [pairKey('nut', 'tree')]: 'seed',
  [pairKey('nut', 'fire')]: 'food',
  [pairKey('nut', 'oil')]: 'food',
  [pairKey('nut', 'sugar')]: 'chocolate',
  [pairKey('nut', 'water')]: 'milk',

  [pairKey('iceCream', 'ice')]: 'iceCream',
  [pairKey('iceCream', 'milk')]: 'iceCream',
  [pairKey('iceCream', 'sugar')]: 'iceCream',
  [pairKey('ice', 'milk')]: 'iceCream',
  [pairKey('ice', 'sugar')]: 'iceCream',

  [pairKey('cake', 'sugar')]: 'cake',
  [pairKey('cake', 'flour')]: 'cake',
  [pairKey('cake', 'egg')]: 'cake',
  [pairKey('flour', 'sugar')]: 'cookie',
  [pairKey('flour', 'egg')]: 'noodle',
  [pairKey('flour', 'water')]: 'bread',

  [pairKey('cookie', 'sugar')]: 'cookie',
  [pairKey('cookie', 'chocolate')]: 'cookie',
  [pairKey('cookie', 'fire')]: 'cookie',

  [pairKey('pizza', 'bread')]: 'pizza',
  [pairKey('pizza', 'cheese')]: 'pizza',
  [pairKey('pizza', 'tomato')]: 'pizza',
  [pairKey('bread', 'cheese')]: 'pizza',
  [pairKey('bread', 'meat')]: 'food',
  [pairKey('bread', 'oil')]: 'food',

  [pairKey('noodle', 'water')]: 'soup',
  [pairKey('noodle', 'meat')]: 'soup',
  [pairKey('noodle', 'fire')]: 'noodle',
  [pairKey('flour', 'salt')]: 'noodle',
  [pairKey('wheat', 'salt')]: 'noodle',

  [pairKey('salad', 'plant')]: 'salad',
  [pairKey('salad', 'water')]: 'salad',
  [pairKey('salad', 'olive')]: 'salad',
  [pairKey('grass', 'salt')]: 'salad',
  [pairKey('leaf', 'salt')]: 'salad',

  [pairKey('stew', 'meat')]: 'stew',
  [pairKey('stew', 'fire')]: 'stew',
  [pairKey('stew', 'potato')]: 'stew',
  [pairKey('meat', 'potato')]: 'stew',
  [pairKey('meat', 'vegetable')]: 'stew',

  [pairKey('juice', 'fruit')]: 'juice',
  [pairKey('juice', 'water')]: 'juice',
  [pairKey('juice', 'sugar')]: 'wine',
  [pairKey('juice', 'time')]: 'wine',

  [pairKey('cider', 'apple')]: 'cider',
  [pairKey('cider', 'grain')]: 'beer',
  [pairKey('cider', 'fire')]: 'alcohol',

  [pairKey('whiskey', 'grain')]: 'whiskey',
  [pairKey('whiskey', 'water')]: 'whiskey',
  [pairKey('whiskey', 'fire')]: 'alcohol',
  [pairKey('grain', 'fire')]: 'whiskey',
  [pairKey('grain', 'alcohol')]: 'whiskey',

  [pairKey('rum', 'cane')]: 'rum',
  [pairKey('rum', 'sugar')]: 'rum',
  [pairKey('rum', 'ocean')]: 'pirate',
  [pairKey('alcohol', 'cane')]: 'rum',

  [pairKey('vinegar', 'wine')]: 'vinegar',
  [pairKey('vinegar', 'time')]: 'vinegar',
  [pairKey('vinegar', 'acid')]: 'vinegar',
  [pairKey('wine', 'time')]: 'vinegar',

  [pairKey('jam', 'berry')]: 'jam',
  [pairKey('jam', 'fruit')]: 'jam',
  [pairKey('jam', 'sugar')]: 'jam',
  [pairKey('berry', 'heat')]: 'jam',
  [pairKey('fruit', 'heat')]: 'jam',

  [pairKey('yogurt', 'milk')]: 'yogurt',
  [pairKey('yogurt', 'bacteria')]: 'yogurt',
  [pairKey('yogurt', 'time')]: 'cheese',
  [pairKey('milk', 'bacteria')]: 'yogurt',

  [pairKey('pasta', 'flour')]: 'pasta',
  [pairKey('pasta', 'water')]: 'noodle',
  [pairKey('pasta', 'egg')]: 'pasta',
  [pairKey('pasta', 'cheese')]: 'pizza',
  [pairKey('pasta', 'meat')]: 'stew',

  // ════════════════════════════════════════════════════════
  // NEW RECIPES — BATCH 8: ABSTRACT / EMOTIONS
  // ════════════════════════════════════════════════════════
  [pairKey('peace', 'war')]: 'balance',
  [pairKey('peace', 'order')]: 'civilization',
  [pairKey('peace', 'wisdom')]: 'justice',
  [pairKey('peace', 'love')]: 'joy',
  [pairKey('peace', 'chaos')]: 'balance',

  [pairKey('freedom', 'human')]: 'civilization',
  [pairKey('freedom', 'bird')]: 'sky',
  [pairKey('freedom', 'war')]: 'peace',
  [pairKey('freedom', 'knowledge')]: 'civilization',
  [pairKey('freedom', 'soul')]: 'joy',

  [pairKey('power', 'human')]: 'king',
  [pairKey('power', 'electricity')]: 'energy',
  [pairKey('power', 'war')]: 'empire',
  [pairKey('power', 'magic')]: 'wizard',
  [pairKey('power', 'knowledge')]: 'technology',

  [pairKey('justice', 'war')]: 'peace',
  [pairKey('justice', 'law')]: 'order',
  [pairKey('justice', 'knowledge')]: 'wisdom',
  [pairKey('justice', 'city')]: 'prison',
  [pairKey('justice', 'scale')]: 'balance',

  [pairKey('truth', 'lie')]: 'chaos',
  [pairKey('truth', 'knowledge')]: 'wisdom',
  [pairKey('truth', 'light')]: 'discovery',
  [pairKey('truth', 'myth')]: 'legend',
  [pairKey('truth', 'magic')]: 'prophecy',

  [pairKey('fate', 'star')]: 'prophecy',
  [pairKey('fate', 'human')]: 'death',
  [pairKey('fate', 'magic')]: 'prophecy',
  [pairKey('fate', 'time')]: 'death',
  [pairKey('fate', 'luck')]: 'balance',

  [pairKey('luck', 'gold')]: 'treasure',
  [pairKey('luck', 'human')]: 'joy',
  [pairKey('luck', 'stone')]: 'gem',
  [pairKey('luck', 'star')]: 'fate',
  [pairKey('luck', 'magic')]: 'blessing',

  [pairKey('joy', 'music')]: 'dance',
  [pairKey('joy', 'love')]: 'emotion',
  [pairKey('joy', 'sun')]: 'day',
  [pairKey('joy', 'human')]: 'laughter',
  [pairKey('joy', 'child')]: 'laughter',

  [pairKey('anger', 'fire')]: 'inferno',
  [pairKey('anger', 'human')]: 'war',
  [pairKey('anger', 'lightning')]: 'storm',
  [pairKey('anger', 'war')]: 'chaos',
  [pairKey('anger', 'love')]: 'emotion',

  [pairKey('pride', 'warrior')]: 'glory',
  [pairKey('pride', 'human')]: 'civilization',
  [pairKey('pride', 'victory')]: 'glory',
  [pairKey('pride', 'king')]: 'empire',
  [pairKey('pride', 'fall')]: 'chaos',

  [pairKey('greed', 'gold')]: 'empire',
  [pairKey('greed', 'human')]: 'corruption',
  [pairKey('greed', 'king')]: 'war',
  [pairKey('greed', 'merchant')]: 'wealth',
  [pairKey('greed', 'dragon')]: 'treasure',

  [pairKey('courage', 'warrior')]: 'hero',
  [pairKey('courage', 'fear')]: 'balance',
  [pairKey('courage', 'human')]: 'warrior',
  [pairKey('courage', 'death')]: 'hero',
  [pairKey('courage', 'dragon')]: 'legend',

  [pairKey('glory', 'war')]: 'empire',
  [pairKey('glory', 'warrior')]: 'legend',
  [pairKey('glory', 'sun')]: 'sunGod',
  [pairKey('glory', 'death')]: 'legend',
  [pairKey('glory', 'victory')]: 'empire',

  [pairKey('honor', 'warrior')]: 'knight',
  [pairKey('honor', 'death')]: 'legend',
  [pairKey('honor', 'sword')]: 'knight',
  [pairKey('honor', 'king')]: 'knight',
  [pairKey('honor', 'code')]: 'law',

  [pairKey('beauty', 'flower')]: 'rose',
  [pairKey('beauty', 'art')]: 'museum',
  [pairKey('beauty', 'music')]: 'song',
  [pairKey('beauty', 'gold')]: 'jewelry',
  [pairKey('beauty', 'magic')]: 'enchantment',

  // ════════════════════════════════════════════════════════
  // NEW RECIPES — BATCH 9: FANTASY CONCEPTS
  // ════════════════════════════════════════════════════════
  [pairKey('ritual', 'fire')]: 'magic',
  [pairKey('ritual', 'death')]: 'necromancer',
  [pairKey('ritual', 'magic')]: 'spell',
  [pairKey('ritual', 'blood')]: 'curse',
  [pairKey('ritual', 'night')]: 'spell',

  [pairKey('prophecy', 'star')]: 'fate',
  [pairKey('prophecy', 'legend')]: 'myth',
  [pairKey('prophecy', 'magic')]: 'spell',
  [pairKey('prophecy', 'dragon')]: 'legend',
  [pairKey('prophecy', 'death')]: 'curse',

  [pairKey('blessing', 'rain')]: 'life',
  [pairKey('blessing', 'human')]: 'angel',
  [pairKey('blessing', 'magic')]: 'spell',
  [pairKey('blessing', 'god')]: 'angel',
  [pairKey('blessing', 'light')]: 'angel',

  [pairKey('artifact', 'gold')]: 'treasure',
  [pairKey('artifact', 'magic')]: 'rune',
  [pairKey('artifact', 'ancient')]: 'rune',
  [pairKey('artifact', 'legend')]: 'myth',
  [pairKey('artifact', 'cave')]: 'treasure',

  [pairKey('quest', 'hero')]: 'legend',
  [pairKey('quest', 'dragon')]: 'legend',
  [pairKey('quest', 'knight')]: 'legend',
  [pairKey('quest', 'treasure')]: 'gold',
  [pairKey('quest', 'magic')]: 'artifact',

  [pairKey('treasure', 'cave')]: 'gem',
  [pairKey('treasure', 'ocean')]: 'pearl',
  [pairKey('treasure', 'pirate')]: 'gold',
  [pairKey('treasure', 'dragon')]: 'gold',
  [pairKey('treasure', 'map')]: 'island',

  [pairKey('ghost', 'castle')]: 'haunting',
  [pairKey('ghost', 'death')]: 'wraith',
  [pairKey('ghost', 'darkness')]: 'wraith',
  [pairKey('ghost', 'human')]: 'fear',
  [pairKey('ghost', 'fire')]: 'spirit',

  [pairKey('skeleton', 'death')]: 'necromancer',
  [pairKey('skeleton', 'magic')]: 'zombie',
  [pairKey('skeleton', 'cave')]: 'tomb',
  [pairKey('skeleton', 'warrior')]: 'undead',
  [pairKey('skeleton', 'fire')]: 'ash',

  [pairKey('spell', 'fire')]: 'inferno',
  [pairKey('spell', 'water')]: 'tsunami',
  [pairKey('spell', 'earth')]: 'earthquake',
  [pairKey('spell', 'air')]: 'tornado',
  [pairKey('spell', 'light')]: 'enchantment',
  [pairKey('spell', 'darkness')]: 'curse',
  [pairKey('spell', 'life')]: 'healing',

  [pairKey('enchantment', 'sword')]: 'artifact',
  [pairKey('enchantment', 'ring')]: 'artifact',
  [pairKey('enchantment', 'armor')]: 'artifact',
  [pairKey('enchantment', 'darkness')]: 'curse',
  [pairKey('enchantment', 'light')]: 'blessing',

  [pairKey('portal', 'magic')]: 'wormhole',
  [pairKey('portal', 'fire')]: 'volcano',
  [pairKey('portal', 'darkness')]: 'void',
  [pairKey('portal', 'light')]: 'rainbow',
  [pairKey('portal', 'space')]: 'wormhole',

  [pairKey('labyrinth', 'stone')]: 'dungeon',
  [pairKey('labyrinth', 'monster')]: 'minotaur',
  [pairKey('labyrinth', 'human')]: 'quest',
  [pairKey('labyrinth', 'magic')]: 'enchantment',
  [pairKey('labyrinth', 'gold')]: 'treasure',

  // ════════════════════════════════════════════════════════
  // NEW RECIPES — BATCH 10: SCIENCE CONCEPTS
  // ════════════════════════════════════════════════════════
  [pairKey('pressure', 'water')]: 'geyser',
  [pairKey('pressure', 'rock')]: 'diamond',
  [pairKey('pressure', 'gas')]: 'explosion',
  [pairKey('pressure', 'earth')]: 'earthquake',
  [pairKey('pressure', 'metal')]: 'steel',
  [pairKey('pressure', 'coal')]: 'diamond',

  [pairKey('catalyst', 'fire')]: 'explosion',
  [pairKey('catalyst', 'chemistry')]: 'reaction',
  [pairKey('catalyst', 'metal')]: 'rust',
  [pairKey('catalyst', 'life')]: 'evolution',
  [pairKey('catalyst', 'science')]: 'discovery',

  [pairKey('fossil', 'rock')]: 'coal',
  [pairKey('fossil', 'earth')]: 'oil',
  [pairKey('fossil', 'science')]: 'evolution',
  [pairKey('fossil', 'dinosaur')]: 'coal',
  [pairKey('fossil', 'time')]: 'oil',

  [pairKey('experiment', 'science')]: 'discovery',
  [pairKey('experiment', 'alchemy')]: 'potion',
  [pairKey('experiment', 'electricity')]: 'technology',
  [pairKey('experiment', 'life')]: 'mutation',
  [pairKey('experiment', 'chemistry')]: 'acid',

  [pairKey('theory', 'science')]: 'physics',
  [pairKey('theory', 'knowledge')]: 'discovery',
  [pairKey('theory', 'math')]: 'physics',
  [pairKey('theory', 'time')]: 'discovery',
  [pairKey('theory', 'mind')]: 'philosophy',

  [pairKey('discovery', 'science')]: 'invention',
  [pairKey('discovery', 'knowledge')]: 'civilization',
  [pairKey('discovery', 'island')]: 'civilization',
  [pairKey('discovery', 'explorer')]: 'civilization',
  [pairKey('discovery', 'fire')]: 'civilization',

  [pairKey('invention', 'science')]: 'technology',
  [pairKey('invention', 'metal')]: 'machine',
  [pairKey('invention', 'electricity')]: 'technology',
  [pairKey('invention', 'human')]: 'technology',
  [pairKey('invention', 'fire')]: 'steamEngine',

  // ════════════════════════════════════════════════════════
  // NEW RECIPES — BATCH 11: NEW ANIMALS
  // ════════════════════════════════════════════════════════
  [pairKey('zebra', 'grass')]: 'prairie',
  [pairKey('zebra', 'lion')]: 'savanna',
  [pairKey('zebra', 'horse')]: 'prairie',
  [pairKey('zebra', 'africa')]: 'safari',

  [pairKey('giraffe', 'tree')]: 'jungle',
  [pairKey('giraffe', 'sun')]: 'desert',
  [pairKey('giraffe', 'grass')]: 'savanna',
  [pairKey('giraffe', 'elephant')]: 'savanna',

  [pairKey('camel', 'desert')]: 'oasis',
  [pairKey('camel', 'sand')]: 'oasis',
  [pairKey('camel', 'sun')]: 'drought',
  [pairKey('camel', 'human')]: 'chariot',
  [pairKey('camel', 'warrior')]: 'army',

  [pairKey('kangaroo', 'grass')]: 'prairie',
  [pairKey('kangaroo', 'desert')]: 'oasis',
  [pairKey('kangaroo', 'earth')]: 'prairie',
  [pairKey('kangaroo', 'sun')]: 'drought',

  [pairKey('koala', 'tree')]: 'forest',
  [pairKey('koala', 'eucalyptus')]: 'forest',
  [pairKey('koala', 'leaf')]: 'forest',
  [pairKey('koala', 'sleep')]: 'dream',

  [pairKey('panda', 'bamboo')]: 'forest',
  [pairKey('panda', 'mountain')]: 'forest',
  [pairKey('panda', 'bear')]: 'forest',
  [pairKey('panda', 'forest')]: 'bamboo',

  [pairKey('monkey', 'tree')]: 'jungle',
  [pairKey('monkey', 'jungle')]: 'gorilla',
  [pairKey('monkey', 'human')]: 'evolution',
  [pairKey('monkey', 'intelligence')]: 'evolution',
  [pairKey('monkey', 'banana')]: 'jungle',

  [pairKey('parrot', 'bird')]: 'jungle',
  [pairKey('parrot', 'jungle')]: 'bird',
  [pairKey('parrot', 'human')]: 'civilization',
  [pairKey('parrot', 'pirate')]: 'ship',
  [pairKey('parrot', 'color')]: 'beauty',

  [pairKey('flamingo', 'water')]: 'lake',
  [pairKey('flamingo', 'marsh')]: 'bird',
  [pairKey('flamingo', 'bird')]: 'marsh',
  [pairKey('flamingo', 'pink')]: 'beauty',

  [pairKey('swan', 'water')]: 'lake',
  [pairKey('swan', 'lake')]: 'beauty',
  [pairKey('swan', 'ice')]: 'frost',
  [pairKey('swan', 'bird')]: 'lake',
  [pairKey('swan', 'magic')]: 'fairy',

  [pairKey('duck', 'water')]: 'pond',
  [pairKey('duck', 'pond')]: 'bird',
  [pairKey('duck', 'egg')]: 'bird',
  [pairKey('duck', 'rain')]: 'pond',

  [pairKey('chicken', 'egg')]: 'bird',
  [pairKey('chicken', 'farm')]: 'egg',
  [pairKey('chicken', 'fire')]: 'meat',
  [pairKey('chicken', 'human')]: 'farm',
  [pairKey('chicken', 'grain')]: 'egg',

  [pairKey('rat', 'plague')]: 'virus',
  [pairKey('rat', 'city')]: 'virus',
  [pairKey('rat', 'cave')]: 'mouse',
  [pairKey('rat', 'human')]: 'virus',
  [pairKey('rat', 'ship')]: 'plague',

  [pairKey('mouse', 'cat')]: 'fear',
  [pairKey('mouse', 'cave')]: 'rat',
  [pairKey('mouse', 'grain')]: 'pest',
  [pairKey('mouse', 'computer')]: 'technology',

  [pairKey('hedgehog', 'forest')]: 'insect',
  [pairKey('hedgehog', 'night')]: 'bat',
  [pairKey('hedgehog', 'earth')]: 'worm',
  [pairKey('hedgehog', 'thorn')]: 'defense',

  [pairKey('beaver', 'wood')]: 'dam',
  [pairKey('beaver', 'river')]: 'dam',
  [pairKey('beaver', 'water')]: 'dam',
  [pairKey('beaver', 'tree')]: 'wood',

  [pairKey('otter', 'water')]: 'river',
  [pairKey('otter', 'fish')]: 'river',
  [pairKey('otter', 'river')]: 'fish',
  [pairKey('otter', 'ocean')]: 'seal',

  [pairKey('raccoon', 'night')]: 'darkness',
  [pairKey('raccoon', 'city')]: 'chaos',
  [pairKey('raccoon', 'forest')]: 'insect',
  [pairKey('raccoon', 'water')]: 'river',

  [pairKey('moose', 'forest')]: 'deer',
  [pairKey('moose', 'mountain')]: 'bear',
  [pairKey('moose', 'lake')]: 'river',
  [pairKey('moose', 'snow')]: 'tundra',

  [pairKey('bison', 'prairie')]: 'horse',
  [pairKey('bison', 'grass')]: 'prairie',
  [pairKey('bison', 'thunder')]: 'storm',
  [pairKey('bison', 'hunter')]: 'meat',

  [pairKey('rhino', 'earth')]: 'rock',
  [pairKey('rhino', 'grass')]: 'savanna',
  [pairKey('rhino', 'horn')]: 'rock',
  [pairKey('rhino', 'mud')]: 'swamp',

  [pairKey('hippo', 'water')]: 'river',
  [pairKey('hippo', 'mud')]: 'swamp',
  [pairKey('hippo', 'river')]: 'crocodile',
  [pairKey('hippo', 'sun')]: 'swamp',

  [pairKey('llama', 'mountain')]: 'goat',
  [pairKey('llama', 'wool')]: 'cloth',
  [pairKey('llama', 'desert')]: 'camel',
  [pairKey('llama', 'human')]: 'farmer',

  [pairKey('peacock', 'forest')]: 'bird',
  [pairKey('peacock', 'color')]: 'beauty',
  [pairKey('peacock', 'sun')]: 'beauty',
  [pairKey('peacock', 'rain')]: 'rainbow',

  [pairKey('crow', 'magic')]: 'raven',
  [pairKey('crow', 'night')]: 'raven',
  [pairKey('crow', 'death')]: 'omen',
  [pairKey('crow', 'intelligence')]: 'wisdom',
  [pairKey('crow', 'forest')]: 'raven',

  [pairKey('seahorse', 'coral')]: 'reef',
  [pairKey('seahorse', 'ocean')]: 'fish',
  [pairKey('seahorse', 'seaweed')]: 'reef',
  [pairKey('seahorse', 'magic')]: 'siren',

  [pairKey('narwhal', 'ice')]: 'unicorn',
  [pairKey('narwhal', 'ocean')]: 'whale',
  [pairKey('narwhal', 'horn')]: 'unicorn',
  [pairKey('narwhal', 'magic')]: 'unicorn',

  [pairKey('walrus', 'ice')]: 'seal',
  [pairKey('walrus', 'ocean')]: 'whale',
  [pairKey('walrus', 'tundra')]: 'seal',
  [pairKey('walrus', 'fish')]: 'seal',

  [pairKey('orca', 'ocean')]: 'whale',
  [pairKey('orca', 'seal')]: 'whale',
  [pairKey('orca', 'shark')]: 'leviathan',
  [pairKey('orca', 'storm')]: 'kraken',

  [pairKey('axolotl', 'water')]: 'frog',
  [pairKey('axolotl', 'cave')]: 'fish',
  [pairKey('axolotl', 'magic')]: 'fairy',
  [pairKey('axolotl', 'mutation')]: 'evolution',

  [pairKey('chameleon', 'desert')]: 'lizard',
  [pairKey('chameleon', 'forest')]: 'lizard',
  [pairKey('chameleon', 'color')]: 'magic',
  [pairKey('chameleon', 'magic')]: 'enchantment',

  [pairKey('iguana', 'desert')]: 'lizard',
  [pairKey('iguana', 'sun')]: 'lizard',
  [pairKey('iguana', 'tree')]: 'lizard',
  [pairKey('iguana', 'island')]: 'dragon',

  [pairKey('capybara', 'water')]: 'river',
  [pairKey('capybara', 'grass')]: 'prairie',
  [pairKey('capybara', 'peace')]: 'joy',
  [pairKey('capybara', 'swamp')]: 'frog',

  [pairKey('sloth', 'tree')]: 'forest',
  [pairKey('sloth', 'jungle')]: 'forest',
  [pairKey('sloth', 'time')]: 'peace',
  [pairKey('sloth', 'leaf')]: 'forest',

  [pairKey('toucan', 'jungle')]: 'bird',
  [pairKey('toucan', 'fruit')]: 'jungle',
  [pairKey('toucan', 'color')]: 'beauty',
  [pairKey('toucan', 'tree')]: 'jungle',

  [pairKey('stork', 'water')]: 'marsh',
  [pairKey('stork', 'child')]: 'village',
  [pairKey('stork', 'sky')]: 'bird',
  [pairKey('stork', 'river')]: 'marsh',

  [pairKey('vulture', 'death')]: 'desert',
  [pairKey('vulture', 'desert')]: 'eagle',
  [pairKey('vulture', 'mountain')]: 'eagle',
  [pairKey('vulture', 'sun')]: 'desert',

  // ════════════════════════════════════════════════════════
  // NEW RECIPES — BATCH 12: EXTRA CROSS-CATEGORY COMBOS
  // ════════════════════════════════════════════════════════
  [pairKey('dam', 'river')]: 'lake',
  [pairKey('dam', 'water')]: 'electricity',
  [pairKey('dam', 'stone')]: 'bridge',
  [pairKey('dam', 'concrete')]: 'electricity',

  [pairKey('shipwreck', 'ocean')]: 'treasure',
  [pairKey('shipwreck', 'coral')]: 'reef',
  [pairKey('shipwreck', 'time')]: 'fossil',

  [pairKey('monastery', 'mountain')]: 'monk',
  [pairKey('monastery', 'knowledge')]: 'library',
  [pairKey('monastery', 'religion')]: 'cathedral',

  [pairKey('harvest', 'wheat')]: 'flour',
  [pairKey('harvest', 'grain')]: 'flour',
  [pairKey('harvest', 'sun')]: 'grain',
  [pairKey('harvest', 'farmer')]: 'grain',
  [pairKey('harvest', 'farm')]: 'grain',

  [pairKey('bakery', 'flour')]: 'bread',
  [pairKey('bakery', 'fire')]: 'bread',
  [pairKey('bakery', 'city')]: 'market',
  [pairKey('bakery', 'human')]: 'chef',

  [pairKey('savanna', 'lion')]: 'tiger',
  [pairKey('savanna', 'grass')]: 'prairie',
  [pairKey('savanna', 'sun')]: 'desert',
  [pairKey('savanna', 'elephant')]: 'prairie',
  [pairKey('savanna', 'fire')]: 'wildfire',

  [pairKey('plague', 'city')]: 'virus',
  [pairKey('plague', 'rat')]: 'virus',
  [pairKey('plague', 'ship')]: 'virus',
  [pairKey('plague', 'war')]: 'death',

  [pairKey('ruin', 'time')]: 'fossil',
  [pairKey('ruin', 'stone')]: 'monument',
  [pairKey('ruin', 'war')]: 'monument',
  [pairKey('ruin', 'earthquake')]: 'dust',

  [pairKey('philosophy', 'human')]: 'wisdom',
  [pairKey('philosophy', 'mind')]: 'consciousness',
  [pairKey('philosophy', 'knowledge')]: 'wisdom',
  [pairKey('philosophy', 'time')]: 'infinity',

  [pairKey('song', 'music')]: 'art',
  [pairKey('song', 'human')]: 'music',
  [pairKey('song', 'love')]: 'emotion',
  [pairKey('song', 'bird')]: 'music',

  [pairKey('dance', 'music')]: 'art',
  [pairKey('dance', 'human')]: 'emotion',
  [pairKey('dance', 'fire')]: 'ritual',
  [pairKey('dance', 'magic')]: 'spell',

  [pairKey('laughter', 'human')]: 'joy',
  [pairKey('laughter', 'child')]: 'joy',
  [pairKey('laughter', 'music')]: 'joy',
  [pairKey('laughter', 'joy')]: 'peace',

  [pairKey('wealth', 'human')]: 'greed',
  [pairKey('wealth', 'city')]: 'empire',
  [pairKey('wealth', 'gold')]: 'greed',
  [pairKey('wealth', 'merchant')]: 'market',

  [pairKey('corruption', 'city')]: 'dystopia',
  [pairKey('corruption', 'king')]: 'war',
  [pairKey('corruption', 'gold')]: 'greed',
  [pairKey('corruption', 'empire')]: 'war',

  [pairKey('hero', 'dragon')]: 'legend',
  [pairKey('hero', 'sword')]: 'knight',
  [pairKey('hero', 'quest')]: 'legend',
  [pairKey('hero', 'death')]: 'legend',
  [pairKey('hero', 'warrior')]: 'glory',

  [pairKey('undead', 'magic')]: 'zombie',
  [pairKey('undead', 'necromancer')]: 'zombie',
  [pairKey('undead', 'death')]: 'wraith',
  [pairKey('undead', 'night')]: 'vampire',

  [pairKey('haunting', 'castle')]: 'ghost',
  [pairKey('haunting', 'night')]: 'ghost',
  [pairKey('haunting', 'death')]: 'wraith',
  [pairKey('haunting', 'magic')]: 'curse',

  [pairKey('scent', 'flower')]: 'beauty',
  [pairKey('scent', 'plant')]: 'herb',
  [pairKey('scent', 'fire')]: 'incense',
  [pairKey('scent', 'magic')]: 'enchantment',

  [pairKey('tapestry', 'art')]: 'museum',
  [pairKey('tapestry', 'castle')]: 'fortress',
  [pairKey('tapestry', 'silk')]: 'beauty',
  [pairKey('tapestry', 'story')]: 'legend',

  [pairKey('painting', 'art')]: 'museum',
  [pairKey('painting', 'cave')]: 'legend',
  [pairKey('painting', 'artist')]: 'museum',
  [pairKey('painting', 'history')]: 'museum',

  [pairKey('defense', 'castle')]: 'fortress',
  [pairKey('defense', 'army')]: 'peace',
  [pairKey('defense', 'wall')]: 'fortress',
  [pairKey('defense', 'technology')]: 'robot',

  [pairKey('omen', 'night')]: 'prophecy',
  [pairKey('omen', 'crow')]: 'death',
  [pairKey('omen', 'star')]: 'fate',
  [pairKey('omen', 'magic')]: 'prophecy',

  [pairKey('pest', 'crop')]: 'famine',
  [pairKey('pest', 'farm')]: 'famine',
  [pairKey('pest', 'grain')]: 'famine',
  [pairKey('pest', 'locust')]: 'famine',

  [pairKey('famine', 'city')]: 'war',
  [pairKey('famine', 'war')]: 'death',
  [pairKey('famine', 'drought')]: 'death',
  [pairKey('famine', 'plague')]: 'death',

  [pairKey('incense', 'temple')]: 'ritual',
  [pairKey('incense', 'fire')]: 'smoke',
  [pairKey('incense', 'prayer')]: 'blessing',
  [pairKey('incense', 'magic')]: 'ritual',

  [pairKey('popcorn', 'fire')]: 'popcorn',
  [pairKey('popcorn', 'theater')]: 'art',
  [pairKey('popcorn', 'salt')]: 'food',

  [pairKey('totem', 'animal')]: 'ritual',
  [pairKey('totem', 'shaman')]: 'spirit',
  [pairKey('totem', 'tribe')]: 'religion',
  [pairKey('totem', 'wood')]: 'statue',

  [pairKey('healing', 'magic')]: 'elixir',
  [pairKey('healing', 'water')]: 'life',
  [pairKey('healing', 'herb')]: 'medicine',
  [pairKey('healing', 'light')]: 'blessing',

  [pairKey('enlightenment', 'meditation')]: 'wisdom',
  [pairKey('enlightenment', 'fire')]: 'light',
  [pairKey('enlightenment', 'knowledge')]: 'consciousness',
  [pairKey('enlightenment', 'void')]: 'infinity',

  [pairKey('meditation', 'fire')]: 'enlightenment',
  [pairKey('meditation', 'mountain')]: 'monk',
  [pairKey('meditation', 'water')]: 'peace',
  [pairKey('meditation', 'knowledge')]: 'wisdom',

  [pairKey('history', 'human')]: 'legend',
  [pairKey('history', 'book')]: 'knowledge',
  [pairKey('history', 'city')]: 'civilization',
  [pairKey('history', 'war')]: 'myth',
  [pairKey('history', 'time')]: 'memory',

  [pairKey('fur', 'human')]: 'cloth',
  [pairKey('fur', 'animal')]: 'leather',
  [pairKey('fur', 'cold')]: 'warmth',
  [pairKey('fur', 'fire')]: 'ash',

  [pairKey('warmth', 'human')]: 'life',
  [pairKey('warmth', 'cold')]: 'steam',
  [pairKey('warmth', 'fire')]: 'light',
  [pairKey('warmth', 'animal')]: 'fur',

  [pairKey('sail', 'wind')]: 'ship',
  [pairKey('sail', 'ocean')]: 'ship',
  [pairKey('sail', 'cloth')]: 'ship',
  [pairKey('sail', 'wood')]: 'ship',

  [pairKey('vitamin', 'plant')]: 'medicine',
  [pairKey('vitamin', 'fruit')]: 'medicine',
  [pairKey('vitamin', 'science')]: 'medicine',
  [pairKey('vitamin', 'sun')]: 'life',

  [pairKey('safari', 'desert')]: 'oasis',
  [pairKey('safari', 'animal')]: 'zoo',
  [pairKey('safari', 'explorer')]: 'discovery',
  [pairKey('safari', 'lion')]: 'pride',

  [pairKey('zoo', 'animal')]: 'city',
  [pairKey('zoo', 'city')]: 'civilization',
  [pairKey('zoo', 'child')]: 'joy',
  [pairKey('zoo', 'science')]: 'biology',

  [pairKey('jewelry', 'gold')]: 'crown',
  [pairKey('jewelry', 'gem')]: 'ring',
  [pairKey('jewelry', 'silver')]: 'ring',
  [pairKey('jewelry', 'magic')]: 'enchantment',

  [pairKey('meditation', 'silence')]: 'wisdom',
  [pairKey('philosophy', 'death')]: 'soul',
  [pairKey('philosophy', 'void')]: 'infinity',

  [pairKey('crop', 'rain')]: 'harvest',
  [pairKey('crop', 'sun')]: 'harvest',
  [pairKey('crop', 'earth')]: 'grain',
  [pairKey('crop', 'farm')]: 'harvest',

  [pairKey('food', 'fire')]: 'smoke',
  [pairKey('food', 'human')]: 'civilization',
  [pairKey('food', 'animal')]: 'life',

  [pairKey('vegetable', 'water')]: 'salad',
  [pairKey('vegetable', 'fire')]: 'food',
  [pairKey('vegetable', 'earth')]: 'plant',
  [pairKey('vegetable', 'sun')]: 'salad',
};
