export const pairKey = (aId, bId) => {
  return [aId, bId].sort().join(':');
};

export const RECIPES = {
  [pairKey('fire', 'water')]: 'steam',
  [pairKey('water', 'earth')]: 'mud',
  [pairKey('air', 'water')]: 'cloud',
  [pairKey('air', 'earth')]: 'atmosphere',
  [pairKey('air', 'fire')]: 'smoke',
  [pairKey('earth', 'fire')]: 'volcano',

  [pairKey('water', 'water')]: 'ocean',
  [pairKey('air', 'air')]: 'oxygen',
  [pairKey('fire', 'fire')]: 'inferno',
  [pairKey('earth', 'earth')]: 'mountain',

  [pairKey('atmosphere', 'fire')]: 'plasma',
  [pairKey('smoke', 'earth')]: 'smog',
  [pairKey('mud', 'atmosphere')]: 'smog',
  [pairKey('mud', 'air')]: 'dust',
  [pairKey('cloud', 'earth')]: 'atmosphere',
  [pairKey('ocean', 'air')]: 'atmosphere',
  [pairKey('smoke', 'atmosphere')]: 'smog',

  [pairKey('inferno', 'earth')]: 'volcano',
  [pairKey('atmosphere', 'sea')]: 'ocean',

  [pairKey('atmosphere', 'air')]: 'sky',
  [pairKey('steam', 'fire')]: 'dragon',
  [pairKey('oxygen', 'ocean')]: 'sea',
  [pairKey('ocean', 'water')]: 'sea',
  [pairKey('steam', 'air')]: 'vapor',
  [pairKey('mud', 'earth')]: 'clay',
  [pairKey('mud', 'fire')]: 'lava',
  [pairKey('ocean', 'fire')]: 'lava',
  [pairKey('fire', 'volcano')]: 'lava',
  [pairKey('atmosphere', 'water')]: 'humidity',
  [pairKey('humidity', 'plasma')]: 'steam',

  [pairKey('sky', 'fire')]: 'sun',
  [pairKey('fire', 'plasma')]: 'sun',
  [pairKey('air', 'inferno')]: 'wildfire',
  [pairKey('air', 'volcano')]: 'ashCloud',
  [pairKey('lava', 'air')]: 'magma',
  [pairKey('lava', 'plasma')]: 'magma',
  [pairKey('steam', 'vapor')]: 'mist',
  [pairKey('smoke', 'lava')]: 'volcano',
  [pairKey('ocean', 'plasma')]: 'bioluminescense',
  [pairKey('oxygen', 'plasma')]: 'fire',
  [pairKey('earth', 'smog')]: 'dystopia',
  [pairKey('fire', 'mountain')]: 'volcano',
  [pairKey('clay', 'humidity')]: 'mud',
  [pairKey('sea', 'inferno')]: 'lava ocean',
  [pairKey('humidity', 'mountain')]: 'cloud',
  [pairKey('cloud', 'clay')]: 'cumulus',
  [pairKey('dust', 'air')]: 'pollution',
  [pairKey('atmosphere', 'volcano')]: 'eruption',
  [pairKey('oxygen', 'steam')]: 'water vapor',
  [pairKey('atmosphere', 'clay')]: 'terra cotta',
  [pairKey('fire', 'inferno')]: 'blaze',
  [pairKey('steam', 'earth')]: 'geothermal',

  // [pairKey('mountain', 'air')]: 'altitude',
  // [pairKey('inferno', 'oxygen')]: 'combustion',
  // [pairKey('cloud', 'fire')]: 'pyrocumulus',
  // [pairKey('atmosphere', 'mountain')]: 'stratosphere',

  // ─── WEATHER ──────────────────────────────────────
  [pairKey('cloud', 'water')]: 'rain',
  [pairKey('cloud', 'ocean')]: 'rain',
  [pairKey('cloud', 'mist')]: 'rain',
  [pairKey('mountain', 'water')]: 'ice',
  [pairKey('cloud', 'ice')]: 'snow',
  [pairKey('atmosphere', 'ice')]: 'snow',
  [pairKey('lightning', 'rain')]: 'storm',
  [pairKey('cloud', 'cloud')]: 'storm',
  [pairKey('air', 'rain')]: 'storm',
  [pairKey('cloud', 'fire')]: 'lightning',
  [pairKey('cloud', 'plasma')]: 'lightning',
  [pairKey('air', 'lightning')]: 'thunder',
  [pairKey('lightning', 'thunder')]: 'storm',
  [pairKey('air', 'storm')]: 'tornado',
  [pairKey('storm', 'storm')]: 'hurricane',
  [pairKey('air', 'ice')]: 'frost',
  [pairKey('earth', 'ice')]: 'tundra',
  [pairKey('snow', 'storm')]: 'blizzard',
  [pairKey('ice', 'storm')]: 'hail',
  [pairKey('rain', 'sun')]: 'rainbow',
  [pairKey('mist', 'sun')]: 'rainbow',
  [pairKey('earth', 'mist')]: 'fog',
  [pairKey('earth', 'vapor')]: 'fog',
  [pairKey('atmosphere', 'plasma')]: 'aurora',
  [pairKey('ocean', 'rain')]: 'monsoon',
  [pairKey('fire', 'ice')]: 'water',
  [pairKey('ice', 'sun')]: 'water',
  [pairKey('fire', 'snow')]: 'water',
  [pairKey('snow', 'sun')]: 'water',

  // ─── GEOLOGY / MATERIALS ────────────────────────────────
  [pairKey('earth', 'lava')]: 'rock',
  [pairKey('magma', 'earth')]: 'rock',
  [pairKey('rock', 'mountain')]: 'stone',
  [pairKey('stone', 'ocean')]: 'sand',
  [pairKey('rock', 'wave')]: 'sand',
  [pairKey('fire', 'sand')]: 'glass',
  [pairKey('lava', 'sand')]: 'glass',
  [pairKey('lava', 'water')]: 'obsidian',
  [pairKey('magma', 'ocean')]: 'obsidian',
  [pairKey('earth', 'blaze')]: 'coal',
  [pairKey('mud', 'inferno')]: 'coal',
  [pairKey('rock', 'fire')]: 'mineral',
  [pairKey('mine', 'rock')]: 'mineral',
  [pairKey('fire', 'mineral')]: 'metal',
  [pairKey('inferno', 'rock')]: 'metal',
  [pairKey('earth', 'metal')]: 'iron',
  [pairKey('metal', 'rock')]: 'iron',
  [pairKey('metal', 'water')]: 'copper',
  [pairKey('metal', 'sun')]: 'gold',
  [pairKey('iron', 'sun')]: 'gold',
  [pairKey('metal', 'moon')]: 'silver',
  [pairKey('iron', 'moon')]: 'silver',
  [pairKey('coal', 'iron')]: 'steel',
  [pairKey('iron', 'iron')]: 'steel',
  [pairKey('iron', 'rain')]: 'rust',
  [pairKey('rain', 'steel')]: 'rust',
  [pairKey('mineral', 'water')]: 'crystal',
  [pairKey('glass', 'earth')]: 'crystal',
  [pairKey('glass', 'glass')]: 'crystal',
  [pairKey('crystal', 'fire')]: 'gem',
  [pairKey('cave', 'crystal')]: 'gem',
  [pairKey('gem', 'inferno')]: 'diamond',
  [pairKey('crystal', 'volcano')]: 'diamond',
  [pairKey('copper', 'iron')]: 'bronze',
  [pairKey('fire', 'stone')]: 'marble',
  [pairKey('rock', 'rock')]: 'cave',
  [pairKey('earth', 'rock')]: 'soil',

  // ─── WATER FEATURES ────────────────────────────────
  [pairKey('mountain', 'rain')]: 'river',
  [pairKey('ice', 'mountain')]: 'glacier',
  [pairKey('storm', 'water')]: 'wave',
  [pairKey('mud', 'tree')]: 'swamp',
  [pairKey('mountain', 'river')]: 'waterfall',
  [pairKey('earth', 'rain')]: 'pond',
  [pairKey('moon', 'ocean')]: 'tide',
  [pairKey('rain', 'river')]: 'flood',
  [pairKey('glacier', 'sun')]: 'flood',
  [pairKey('ocean', 'river')]: 'delta',
  [pairKey('river', 'grass')]: 'marsh',
  [pairKey('river', 'river')]: 'lake',

  // ─── LANDFORMS ────────────────────────────────
  [pairKey('ocean', 'volcano')]: 'island',
  [pairKey('mountain', 'ocean')]: 'island',
  [pairKey('sand', 'sun')]: 'desert',
  [pairKey('river', 'rock')]: 'canyon',
  [pairKey('ocean', 'sand')]: 'beach',
  [pairKey('desert', 'water')]: 'oasis',

  // ─── LIFE ────────────────────────────────
  [pairKey('lightning', 'ocean')]: 'life',
  [pairKey('lightning', 'sea')]: 'life',
  [pairKey('lightning', 'water')]: 'life',
  [pairKey('mud', 'lightning')]: 'life',
  [pairKey('ocean', 'sun')]: 'life',

  // ─── PLANTS / NATURE ────────────────────────────────
  [pairKey('clay', 'earth')]: 'soil',
  [pairKey('soil', 'sun')]: 'plant',
  [pairKey('soil', 'water')]: 'plant',
  [pairKey('plant', 'earth')]: 'grass',
  [pairKey('grass', 'sun')]: 'flower',
  [pairKey('plant', 'rain')]: 'flower',
  [pairKey('seed', 'soil')]: 'tree',
  [pairKey('rain', 'tree')]: 'forest',
  [pairKey('tree', 'tree')]: 'forest',
  [pairKey('forest', 'humidity')]: 'jungle',
  [pairKey('forest', 'rain')]: 'jungle',
  [pairKey('rock', 'tree')]: 'wood',
  [pairKey('fire', 'wood')]: 'charcoal',
  [pairKey('air', 'tree')]: 'leaf',
  [pairKey('stone', 'water')]: 'moss',
  [pairKey('cave', 'water')]: 'moss',
  [pairKey('lake', 'sun')]: 'algae',
  [pairKey('water', 'plant')]: 'algae',
  [pairKey('algae', 'ocean')]: 'seaweed',
  [pairKey('soil', 'humidity')]: 'mushroom',
  [pairKey('wood', 'water')]: 'mushroom',
  [pairKey('flower', 'tree')]: 'fruit',
  [pairKey('fruit', 'earth')]: 'seed',
  [pairKey('air', 'flower')]: 'pollen',
  [pairKey('plant', 'tree')]: 'vine',
  [pairKey('plant', 'desert')]: 'cactus',
  [pairKey('grass', 'humidity')]: 'bamboo',
  [pairKey('stone', 'sea')]: 'coral',
  [pairKey('mushroom', 'air')]: 'spore',
  [pairKey('earth', 'grass')]: 'prairie',
  [pairKey('forest', 'fire')]: 'wildfire',
  [pairKey('plant', 'sun')]: 'grain',

  // ─── ANIMALS ────────────────────────────────
  [pairKey('life', 'water')]: 'fish',
  [pairKey('life', 'sea')]: 'fish',
  [pairKey('life', 'plant')]: 'insect',
  [pairKey('life', 'soil')]: 'worm',
  [pairKey('flower', 'insect')]: 'bee',
  [pairKey('insect', 'pollen')]: 'bee',
  [pairKey('insect', 'sun')]: 'butterfly',
  [pairKey('life', 'sky')]: 'bird',
  [pairKey('life', 'tree')]: 'bird',
  [pairKey('bird', 'mountain')]: 'eagle',
  [pairKey('bird', 'moon')]: 'owl',
  [pairKey('life', 'rock')]: 'snake',
  [pairKey('desert', 'life')]: 'snake',
  [pairKey('snake', 'sun')]: 'lizard',
  [pairKey('life', 'pond')]: 'frog',
  [pairKey('life', 'swamp')]: 'frog',
  [pairKey('life', 'mountain')]: 'wolf',
  [pairKey('forest', 'mountain')]: 'bear',
  [pairKey('forest', 'life')]: 'bear',
  [pairKey('forest', 'grass')]: 'deer',
  [pairKey('grass', 'life')]: 'horse',
  [pairKey('fish', 'fish')]: 'whale',
  [pairKey('fish', 'storm')]: 'shark',
  [pairKey('fish', 'wave')]: 'dolphin',
  [pairKey('earth', 'ocean')]: 'crab',
  [pairKey('rock', 'sea')]: 'turtle',
  [pairKey('earth', 'lizard')]: 'dinosaur',
  [pairKey('glacier', 'horse')]: 'mammoth',
  [pairKey('bird', 'fire')]: 'phoenix',
  [pairKey('ocean', 'storm')]: 'kraken',
  [pairKey('crystal', 'horse')]: 'unicorn',
  [pairKey('eagle', 'wolf')]: 'griffin',
  [pairKey('kraken', 'ocean')]: 'leviathan',
  [pairKey('fire', 'lizard')]: 'dragon',
  [pairKey('coral', 'ocean')]: 'reef',
  [pairKey('life', 'ocean')]: 'coral',
  [pairKey('earth', 'life')]: 'human',

  // ─── HUMAN / CIVILIZATION ────────────────────────────────
  [pairKey('fire', 'life')]: 'human',
  [pairKey('human', 'human')]: 'tribe',
  [pairKey('earth', 'tribe')]: 'village',
  [pairKey('tribe', 'wood')]: 'village',
  [pairKey('village', 'village')]: 'city',
  [pairKey('wood', 'wood')]: 'house',
  [pairKey('house', 'stone')]: 'castle',
  [pairKey('human', 'stone')]: 'tool',
  [pairKey('metal', 'tool')]: 'weapon',
  [pairKey('forge', 'iron')]: 'sword',
  [pairKey('forge', 'steel')]: 'armor',
  [pairKey('ocean', 'wood')]: 'ship',
  [pairKey('fire', 'metal')]: 'forge',
  [pairKey('human', 'mountain')]: 'mine',
  [pairKey('rock', 'wood')]: 'wheel',
  [pairKey('river', 'stone')]: 'bridge',
  [pairKey('clay', 'human')]: 'writing',
  [pairKey('human', 'leaf')]: 'writing',
  [pairKey('human', 'writing')]: 'knowledge',
  [pairKey('army', 'city')]: 'empire',
  [pairKey('city', 'city')]: 'empire',
  [pairKey('human', 'weapon')]: 'army',
  [pairKey('tribe', 'weapon')]: 'army',
  [pairKey('human', 'village')]: 'market',
  [pairKey('human', 'mushroom')]: 'medicine',
  [pairKey('human', 'plant')]: 'medicine',
  [pairKey('human', 'sun')]: 'religion',
  [pairKey('human', 'volcano')]: 'religion',
  [pairKey('grass', 'human')]: 'farm',
  [pairKey('city', 'ocean')]: 'harbor',
  [pairKey('fire', 'glass')]: 'lighthouse',
  [pairKey('gold', 'human')]: 'crown',
  [pairKey('city', 'knowledge')]: 'library',
  [pairKey('glass', 'sky')]: 'telescope',
  [pairKey('human', 'knowledge')]: 'science',
  [pairKey('army', 'army')]: 'war',
  [pairKey('human', 'sand')]: 'pyramid',
  [pairKey('water', 'wheel')]: 'mill',
  [pairKey('earth', 'iron')]: 'compass',
  [pairKey('empire', 'knowledge')]: 'civilization',
  [pairKey('metal', 'science')]: 'technology',
  [pairKey('city', 'electricity')]: 'technology',

  // ─── FOOD / ALCHEMY ────────────────────────────────
  [pairKey('grain', 'stone')]: 'flour',
  [pairKey('grain', 'mill')]: 'flour',
  [pairKey('fire', 'flour')]: 'bread',
  [pairKey('flour', 'water')]: 'bread',
  [pairKey('ocean', 'sun')]: 'salt',
  [pairKey('fire', 'sea')]: 'salt',
  [pairKey('bee', 'flower')]: 'honey',
  [pairKey('bee', 'tree')]: 'honey',
  [pairKey('fruit', 'sun')]: 'wine',
  [pairKey('grain', 'water')]: 'beer',
  [pairKey('fish', 'water')]: 'soup',
  [pairKey('mushroom', 'water')]: 'soup',
  [pairKey('leaf', 'water')]: 'tea',
  [pairKey('fire', 'seed')]: 'oil',
  [pairKey('crystal', 'water')]: 'potion',
  [pairKey('gem', 'water')]: 'potion',
  [pairKey('rain', 'volcano')]: 'acid',
  [pairKey('smoke', 'water')]: 'acid',
  [pairKey('coal', 'salt')]: 'gunpowder',
  [pairKey('coal', 'smoke')]: 'gunpowder',
  [pairKey('deer', 'fire')]: 'meat',
  [pairKey('fish', 'fire')]: 'meat',
  [pairKey('fire', 'wine')]: 'alcohol',
  [pairKey('beer', 'grain')]: 'alcohol',

  // ─── ABSTRACT / ENERGY ────────────────────────────────
  [pairKey('iron', 'lightning')]: 'electricity',
  [pairKey('steel', 'lightning')]: 'electricity',
  [pairKey('fire', 'gunpowder')]: 'explosion',
  [pairKey('gunpowder', 'lightning')]: 'explosion',
  [pairKey('crystal', 'moon')]: 'magic',
  [pairKey('gem', 'moon')]: 'magic',
  [pairKey('knowledge', 'potion')]: 'alchemy',
  [pairKey('fire', 'gold')]: 'alchemy',
  [pairKey('dragon', 'human')]: 'myth',
  [pairKey('human', 'lightning')]: 'myth',
  [pairKey('knowledge', 'myth')]: 'legend',
  [pairKey('human', 'myth')]: 'legend',
  [pairKey('forge', 'science')]: 'technology',
  [pairKey('iron', 'steam')]: 'steam engine',
  [pairKey('steam', 'steel')]: 'steam engine',
  [pairKey('fire', 'tornado')]: 'firestorm',
  [pairKey('wildfire', 'tornado')]: 'firestorm',
  [pairKey('earth', 'volcano')]: 'earthquake',
  [pairKey('earth', 'mountain')]: 'earthquake',
  [pairKey('earthquake', 'ocean')]: 'tsunami',
  [pairKey('ocean', 'volcano')]: 'tsunami',
  [pairKey('mountain', 'snow')]: 'avalanche',
  [pairKey('earthquake', 'mountain')]: 'avalanche',
  [pairKey('wildfire', 'forest')]: 'ash cloud',
  [pairKey('volcano', 'forest')]: 'ash cloud',

  // ─── SPACE ────────────────────────────────
  [pairKey('earth', 'sun')]: 'moon',
  [pairKey('sky', 'water')]: 'moon',
  [pairKey('plasma', 'sky')]: 'star',
  [pairKey('sun', 'sky')]: 'star',
  [pairKey('rock', 'star')]: 'planet',
  [pairKey('earth', 'star')]: 'planet',
  [pairKey('ice', 'sky')]: 'comet',
  [pairKey('ice', 'star')]: 'comet',
  [pairKey('star', 'star')]: 'galaxy',
  [pairKey('nebula', 'star')]: 'galaxy',
  [pairKey('cloud', 'star')]: 'nebula',
  [pairKey('dust', 'star')]: 'nebula',
  [pairKey('rock', 'sky')]: 'meteor',
  [pairKey('asteroid', 'atmosphere')]: 'meteor',
  [pairKey('moon', 'sun')]: 'eclipse',
  [pairKey('galaxy', 'galaxy')]: 'cosmos',
  [pairKey('galaxy', 'star')]: 'cosmos',
  [pairKey('comet', 'rock')]: 'asteroid',
  [pairKey('comet', 'earth')]: 'asteroid',
  [pairKey('fire', 'star')]: 'supernova',
  [pairKey('star', 'volcano')]: 'supernova',
  [pairKey('galaxy', 'sun')]: 'black hole',
  [pairKey('supernova', 'star')]: 'black hole',

  // ─── MYTHOLOGY / ADVANCED ────────────────────────────────
  [pairKey('religion', 'sun')]: 'sun god',
  [pairKey('empire', 'sun')]: 'sun god',
  [pairKey('dragon', 'ocean')]: 'sea dragon',
  [pairKey('dragon', 'sea')]: 'sea dragon',
  [pairKey('dragon', 'ice')]: 'ice dragon',
  [pairKey('dragon', 'glacier')]: 'ice dragon',
  [pairKey('dragon', 'storm')]: 'storm dragon',
  [pairKey('dragon', 'lightning')]: 'storm dragon',
  [pairKey('clay', 'life')]: 'golem',
  [pairKey('rock', 'life')]: 'golem',
  [pairKey('life', 'smoke')]: 'spirit',
  [pairKey('human', 'smoke')]: 'spirit',
  [pairKey('geothermal', 'water')]: 'geyser',
  [pairKey('volcano', 'water')]: 'geyser',
  [pairKey('coral', 'rock')]: 'reef',
};
